Here is another mock SQL practice set in the exact same format and style, this time using an **Airline Flight Management System** scenario. 

As requested, I have only provided the questions and the raw data to be inserted, without the SQL query answers.

***

PROMPT "1] CREATE THE RESPECTIVE TABLES & INSERT THE VALUES AS SHOWN BELOW."
PROMPT sqlplus>

FLIGHT_SCHEDULES

The following table:
"DEP_CITY", "FLIGHT_DATE", "RETURN_DATE", "ECONOMY_SEATS", "BUSINESS_SEATS"
"MUMBAI", "10-OCT-25", "15-OCT-25", "180", "45"
"DELHI", "12-OCT-25", "18-OCT-25", "220", "60"
"CHENNAI", "15-OCT-25", "22-OCT-25", "150", "30"
"KOLKATA", "18-OCT-25", "25-OCT-25", "120", "20"
"BANGALORE", "20-OCT-25", "28-OCT-25", "200", "50"

PASSENGERS

The following table:
"P_ID", "PNAME", "CLASS_TYPE", "MEAL_PREF", "DEP_CITY"
"P_01", "VIKRAM", "ECONOMY", "VEG", "MUMBAI"
"P_02", "ANJALI", "BUSINESS", , "DELHI"
"P_03", "ROHAN", "ECONOMY", "NON-VEG", "CHENNAI"
"P_04", "SNEHAL", "BUSINESS", "VEG", "KOLKATA"
"P_05", "KABIR", "FIRST", "VEGAN", "BANGALORE"
"P_06", "ANJALI", "ECONOMY", "NON-VEG", "MUMBAI"
"P_07", "SAMEER", "BUSINESS", "VEG", "DELHI"
"P_08", "VIKRAM", "ECONOMY", "NON-VEG", "BANGALORE"

CREW_MEMBERS

The following table:
"EMP_ID", "NAME", "AGE", "BASE_LOC", "CONTACT_NO"
"401", "RAVI", "32", "MUMBAI", "9812345670"
"402", "SONIA", "28", "DELHI", "8765123490"
"403", "AMIT", "35", "BANGALORE", "7654981230"
"404", "SONIA", "29", "CHENNAI", 
"405", "TARUN", "41", "KOLKATA", "6543871209"
"406", "RAVI", "38", "DELHI", 
"407", "POOJA", "26", "MUMBAI", "9988112233"

AIRCRAFT_STATS

The following table:
"AIRCRAFT_TYPE", "TOTAL_FLEET", "ON_TIME_RATE", "MAINTENANCE_HUB"
"BOEING 737", "45", "88.50", "MUMBAI"
"AIRBUS A320", "60", "91.20", "DELHI"
"BOEING 777", "15", "85.40", "BANGALORE"
"AIRBUS A350", "10", "94.90", "CHENNAI"
"ATR 72", "25", "78.60", "KOLKATA"

---

PROMPT "2] MODIFY PASSENGER SAMEER CLASS_TYPE TO FIRST."
PROMPT sqlplus>

PROMPT "3] DELETE ATR 72 RECORD FROM AIRCRAFT_STATS"
PROMPT sqlplus>

PROMPT "4] DELETE CONTACT_NO OF AMIT"
PROMPT sqlplus>

PROMPT "5] GIVE THE PERMISSION OF DELETING RECORD OF CREW_MEMBERS TO AUDITOR, LOG IN AS AUDITOR TO DELETE 405 RECORD, LATER TAKE BACK THE PERMISSION."
PROMPT sqlplus>