1] WAQTD NAMES OF EMP'S, THEIR DAILY SALARY (ASSUMING 30 DAYS IN A MONTH) AND ANNUAL SALARY IF THE EMP NAME STARTS WITH 'A' OR 'S' AND THEIR MONTHLY SALARY IS NOT IN THE RANGE OF 1500 TO 2500 RPS EXCEPT THE DEPTNO 10 EMP'S.

2] WAQTD NUMBER OF EMP'S AND AVERAGE SALARY IN EACH JOB DESIGNATION IF THE AVERAGE SALARY IS MORE THAN 2000 RPS AND THERE ARE AT LEAST 2 EMP'S IN THAT DESIGNATION, EXCEPT THE 'SALESMAN'.

3] WAQTD THE O/P IN THE FOLLOWING FORMAT :
HELLO ENAME, YOUR DESIGNATION IS JOB AND YOUR TOTAL EARNINGS INCLUDING 500 RPS BONUS IS [SAL+500]
[IF EMP HIRED IN THE YEAR 1981 OR 1982 AND DOES NOT REPORT TO MANAGER NUMBER 7839].

4] WAQTD DETAILS OF EMP'S IF EMP NAME HAS CHAR 'A' AS THE 2ND CHARACTER AND ENDS WITH CHAR 'N', WHO ARE EARNING COMMISSION AND BELONG TO DEPTNO 20 OR 30. [SORT THE DATA BASED ON HIREDATE LATEST TO OLDEST].

5] WAQTD NUMBER OF EMP'S, TOTAL COMMISSION, AND MAXIMUM SALARY IN EACH DEPTNO IF EMP IS HIRED BEFORE 1983, MAXIMUM SALARY EXCEEDS 2800 RPS AND TOTAL COMMISSION IS AT LEAST 500 RPS. [SORT DATA BASED ON TOTAL COMMISSION].

6] WAQTD ENAME, SALARY AND QUARTERLY SALARY (3 MONTHS SALARY) OF EMP'S IF THEY WERE HIRED IN THE MONTH OF JANUARY, MAY OR DECEMBER EXCEPT THOSE WHO ARE WORKING AS 'CLERK' OR 'ANALYST'.

7] WAQTD NAMES OF EMP'S WHO ARE NOT EARNING ANY COMMISSION BUT REPORTING TO A MANAGER, EARNING A SALARY MORE THAN 1200 RPS, AND THEIR NAME DOES NOT CONTAIN CHAR 'M' OR 'T'.

8] WAQTD TOTAL SALARY AND NUMBER OF EMP'S IN EACH DESIGNATION IF THE DESIGNATION CONTAINS CHAR 'E' AND TOTAL SALARY OF THAT DESIGNATION IS A 4 DIGIT NUMBER OR A 5 DIGIT NUMBER CROSSING 10000 RPS.
    
9] WAQTD NAMES AND SALARY OF EMP'S WHOSE NAME EXACTLY HAS 5 CHARACTERS, EARNING SALARY IN THE RANGE OF 1250 TO 3000 RPS EXCEPT THE EMPLOYEES WHO GOT HIRED IN THE YEAR 1980. [SORT THE RESULT BY SALARY IN ASCENDING ORDER].

10] WAQTD EMPNO, ENAME AND JOB OF THE EMP WHO IS EARNING LESS THAN 3000 BUT MORE THAN 800, SHOULD NOT BE WORKING IN DEPTNO 40, THE NAME SHOULD NOT START WITH A VOWEL (A,E,I,O,U), AND EMP SHOULD HAVE BEEN HIRED IN THE FIRST HALF OF THE YEAR (JAN TO JUN). [SORT THE DATA BY DEPTNO ASCENDING AND SALARY DESCENDING].