--  >>>>>>>>>>>>>BASIC SQL ASSIGNMENT >>>>>>

-- 1) WHAT IS SEQUEL AND EXPLAIN HISTORY OF SEQUEL ?
-- 2) EXPLAIN DATA WITH EXAMPLE
-- 3) WHAT IS DATABASE  AND EXPLAIN IT ?
-- 4) WHAT DOES DBMS AND RDBMS EXPLAIN WITH DIFFERENCES ?
-- 5) EXPLAIN THE RULES OF AN E.F CODD ?
-- 6) WHAT IS DATATYPE AND EXPLAIN ALL THE DATATYPES WITH SYNTAX ?
-- 7) DIFFERENCES BETWEEN CHAR AND VARCHAR ?
-- 8) EXPLAIN CONSTRAINTS WITH SYNTAX FOR EACH CONSTRAINTS ?
-- 9) DIFFERENCES BETWEEN PRIMARY KEY AND FOREIGN KEY 
-- 10) DIFFERENCES BETWEEN UNIQUE AND DISTINCT ?

-- =====================================================
-- QUERIES 11–40 : PROJECTION
-- =====================================================

SELECT '11) EMPLOYEES NAME FROM EMP TABLE';
SELECT ENAME FROM EMP;

SELECT '12) SAL AND EMPLOYEES NAME FROM EMP TABLE';
SELECT SAL, ENAME FROM EMP;

SELECT '13) NAME, DEPTNO AND JOB FROM EMP TABLE';
SELECT ENAME, DEPTNO, JOB FROM EMP;

SELECT '14) HIREDATE AND DEPTNO FOR ALL EMPLOYEES';
SELECT HIREDATE, DEPTNO FROM EMP;

SELECT '15) MGR AND EMPNO FROM EMP TABLE';
SELECT MGR, EMPNO FROM EMP;

SELECT '16) ALL DETAILS OF EMPLOYEES';   
SELECT * FROM EMP;

SELECT '17) DEPARTMENT NAME FROM DEPT TABLE';
SELECT DNAME FROM DEPT;

SELECT '18) LOCATIONS FROM DEPT TABLE';
SELECT LOC FROM DEPT;

SELECT '19) DEPTNO AND LOC FROM DEPT';
SELECT DEPTNO, LOC FROM DEPT;

SELECT '20) ALL DETAILS FROM DEPT';
SELECT * FROM DEPT;

SELECT '21) DIFFERENT JOBS IN EMP TABLE';
SELECT DISTINCT JOB FROM EMP;

SELECT '22) ENAME AND SAL WITHOUT DUPLICATES';
SELECT DISTINCT ENAME, SAL FROM EMP;

SELECT '23) HIREDATE AND SAL WITHOUT DUPLICATES';
SELECT DISTINCT HIREDATE, SAL FROM EMP;

SELECT '24) JOB SAL DEPTNO WITHOUT DUPLICATES';
SELECT DISTINCT JOB, SAL, DEPTNO FROM EMP;

SELECT '25) ALL DETAILS WITHOUT DUPLICATES';
SELECT DISTINCT * FROM EMP;

SELECT '26) ANNUAL SALARY';
SELECT ENAME, SAL*12  "ANNUAL_SALARY" FROM EMP;

SELECT '27) HALF TERM SALARY';
SELECT ENAME, SAL*6 "HALF_TERM" FROM EMP;

SELECT '28) ENAME AND ANNUAL SALARY';
SELECT ENAME, SAL*12 "ANNUAL_SALARY" FROM EMP;

SELECT '29) SAL WITH 10% HIKE';
SELECT DEPTNO, JOB, SAL*1.10 SAL_HIKE FROM EMP;

SELECT '30) ALL DETAILS WITH ANNUAL SALARY';
SELECT EMP.*, SAL*12 ANNUAL_SALARY FROM EMP;

SELECT '31) ALL DETAILS WITH 10% HIKE IN ANNUAL SALARY';
SELECT EMP.*, SAL*12*1.10 HIKE_ANNUAL FROM EMP;

SELECT '32) SAL, ANNUAL, HALF AND QUARTER SALARY';
SELECT SAL, SAL*12, SAL*6, SAL*3 FROM EMP;

SELECT '33) ANNUAL SALARY WITH 20% DEDUCTION';
SELECT SAL*12*0.80 FROM EMP;

SELECT '34) DETAILS WITH 100 RS PENALTY';
SELECT EMP.*, SAL-100 FROM EMP;

SELECT '35) TOTAL SALARY FOR EACH EMPLOYEE';
SELECT ENAME, SAL + IFNULL(COMM,0) FROM EMP;

SELECT '36) ANNUAL AND HALF TERM WITH ALIAS';
SELECT SAL*12 ANNUAL, SAL*6 HALF_TERM FROM EMP;

SELECT '37) DETAILS WITH 12% HIKE IN ANNUAL SALARY';
SELECT EMP.*, SAL*12*1.12 HIKE_ANNUAL FROM EMP;

SELECT '38) JOB DESIGNATION, HIREDATE JOINING DATE, MGR REPORTING MANAGER';
SELECT JOB DESIGNATION, HIREDATE JOINING_DATE, MGR REPORTING_MANAGER FROM EMP;

SELECT '39) JOB DESIGNATION AND DEPTNO DNO';
SELECT JOB DESIGNATION, DEPTNO DNO FROM EMP;

SELECT '40) DETAILS WITH 50 RS BONUS';
SELECT EMP.*, SAL+50 BONUS FROM EMP;

-- =====================================================
-- QUERIES 41–60 : SELECTION
-- =====================================================

SELECT '41) SAL > 1000';
SELECT * FROM EMP WHERE SAL > 1000;

SELECT '42) ENAME AND SAL WHERE DEPTNO=20';
SELECT ENAME, SAL FROM EMP WHERE DEPTNO=20;

SELECT '43) JOB AND DEPTNO WHERE JOB=MANAGER';
SELECT JOB, DEPTNO FROM EMP WHERE JOB='MANAGER';

SELECT '44) DETAILS OF KING';
SELECT * FROM EMP WHERE ENAME='KING';

SELECT '45) EMP HIRED ON 1981-01-01';
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE='1981-01-01';

SELECT '46) HIRED AFTER 1981';
SELECT * FROM EMP WHERE YEAR(HIREDATE)>1981;

SELECT '47) HIRED BEFORE 1987';
SELECT * FROM EMP WHERE YEAR(HIREDATE)<1987;

SELECT '48) SAL<5000 WITH ANNUAL SALARY';
SELECT EMP.*, SAL*12 FROM EMP WHERE SAL<5000;

SELECT '49) JOB=MANAGER';
SELECT * FROM EMP WHERE JOB='MANAGER';

SELECT '50) EMPLOYEES IN DEPT 30';
SELECT ENAME, JOB, DEPTNO FROM EMP WHERE DEPTNO=30;

SELECT '51) JOB NOT SALESMAN';
SELECT * FROM EMP WHERE JOB<>'SALESMAN';

SELECT '52) ENAME AND JOB EXCEPT DEPT20';
SELECT ENAME, JOB FROM EMP WHERE DEPTNO<>20;

SELECT '53) JOB DEPTNO SAL EXCEPT SALESMAN';
SELECT JOB, DEPTNO, SAL FROM EMP WHERE JOB<>'SALESMAN';

SELECT '54) JOB EXCEPT KING';
SELECT JOB FROM EMP WHERE ENAME<>'KING';

SELECT '55) 20% HIKE FOR EMP HIRED AFTER 1985';
SELECT EMP.*, SAL*1.20 FROM EMP WHERE YEAR(HIREDATE)>1985;

SELECT '56) 12% DEDUCTION HIRED BEFORE 1984';
SELECT EMP.*, SAL*0.88 FROM EMP WHERE YEAR(HIREDATE)<1984;

SELECT '57) BONUS 2000 FOR EMPNO 7369';
SELECT EMP.*, SAL+2000 FROM EMP WHERE EMPNO=7369;

SELECT '58) NOT IN DEPT10';
SELECT * FROM EMP WHERE DEPTNO<>10;

SELECT '59) HALF TERM WHERE ANNUAL>14000';
SELECT EMP.*, SAL*6 FROM EMP WHERE SAL*12>14000;

SELECT '60) 20% HIKE HALF TERM>7000';
SELECT EMP.*, SAL*6*1.20 FROM EMP WHERE SAL*6>7000;

-- =====================================================
-- QUERIES 61–80 : LOGICAL OPERATORS
-- =====================================================

SELECT '61) DEPT 10 OR 20';
SELECT * FROM EMP WHERE DEPTNO IN (10,20);

SELECT '62) MANAGER OR SALESMAN';
SELECT * FROM EMP WHERE JOB='MANAGER' OR JOB='SALESMAN';

SELECT '63) SAL BETWEEN 1000 AND 5000';
SELECT * FROM EMP WHERE SAL>1000 AND SAL<5000;

SELECT '64) MANAGER IN DEPT20';
SELECT * FROM EMP WHERE DEPTNO=20 AND JOB='MANAGER';

SELECT '65) HIRED AFTER 81 IN DEPT10';
SELECT ENAME,SAL FROM EMP WHERE YEAR(HIREDATE)>1981 AND DEPTNO=10;

SELECT '66) KING OR SCOTT';
SELECT * FROM EMP WHERE ENAME='KING' OR ENAME='SCOTT';

SELECT '67) SAL 3000 OR 5000';
SELECT * FROM EMP WHERE SAL=3000 OR SAL=5000;

SELECT '68) MANAGER DEPT10 HIRED 17-DEC-82';
SELECT * FROM EMP WHERE DEPTNO=10 AND JOB='MANAGER' AND HIREDATE='1982-12-17';

SELECT '69) PRESIDENT DEPT10 SAL5000';
SELECT * FROM EMP WHERE JOB='PRESIDENT' AND DEPTNO=10 AND SAL=5000;

SELECT '70) MANAGER IN DEPT10 OR 20';
SELECT * FROM EMP WHERE JOB='MANAGER' AND DEPTNO IN(10,20);

SELECT '71) HIRED BETWEEN 81 AND 87';
SELECT ENAME,JOB FROM EMP WHERE YEAR(HIREDATE) BETWEEN 1981 AND 1987;

SELECT '72) SAL 1000-5000 IN DEPT20';
SELECT * FROM EMP WHERE SAL BETWEEN 1000 AND 5000 AND DEPTNO=20;

SELECT '73) MANAGER DEPT10 OR20 COMM400 OR1600';
SELECT * FROM EMP WHERE JOB='MANAGER' AND DEPTNO IN(10,20) AND COMM IN(400,1600);

SELECT '74) ANNUAL SAL>800 SALESMAN DEPT30';
SELECT ENAME,SAL*12 FROM EMP WHERE SAL*12>800 AND JOB='SALESMAN' AND DEPTNO=30;

SELECT '75) ENAME AS A DEPTNO AS B JOB AS C';
SELECT ENAME A,DEPTNO B,JOB C FROM EMP WHERE COMM>100;

SELECT '76) HIRED 03-DEC-81 OR 17-DEC-81';
SELECT * FROM EMP WHERE HIREDATE IN('1981-12-03','1981-12-17') AND DEPTNO=30;

SELECT '77) COMM<2000 SAL>1000';
SELECT JOB,SAL FROM EMP WHERE COMM<2000 AND SAL>1000 AND DEPTNO IN(10,20);

SELECT '78) KING SMITH ALLEN';
SELECT * FROM EMP WHERE ENAME IN('KING','SMITH','ALLEN');

SELECT '79) ANNUAL HALF TERM WITH 25% DEDUCTION';
SELECT SAL*12,SAL*6,SAL*0.75 FROM EMP WHERE SAL*12>6000;

SELECT '80) HALF TERM FOR SALESMAN MANAGER DEPT10 OR30';
SELECT EMP.*,SAL*6 FROM EMP WHERE JOB IN('SALESMAN','MANAGER') AND DEPTNO IN(10,30);

-- =====================================================
-- QUERIES 131–155 : AGGREGATE + GROUP BY
-- =====================================================

SELECT '131) MAX SAL';
SELECT MAX(SAL) FROM EMP;

SELECT '132) MAX AND MIN COMM';
SELECT MAX(COMM),MIN(COMM) FROM EMP;

SELECT '133) TOTAL SAL SALESMAN';
SELECT SUM(SAL) FROM EMP WHERE JOB='SALESMAN';

SELECT '134) COUNT EMP IN DEPT30';
SELECT COUNT(*) FROM EMP WHERE DEPTNO=30;

SELECT '135) COUNT MANAGER DEPT20';
SELECT COUNT(*) FROM EMP WHERE JOB='MANAGER' AND DEPTNO=20;

SELECT '136) MAX SAL NAME START A';
SELECT MAX(SAL) FROM EMP WHERE ENAME LIKE 'A%';

SELECT '137) AVG SAL DEPT10';
SELECT AVG(SAL) FROM EMP WHERE DEPTNO=10;

SELECT '138) SUM AND AVG SAL HIRED 81-87';
SELECT SUM(SAL),AVG(SAL) FROM EMP WHERE YEAR(HIREDATE) BETWEEN 1981 AND 1987;

SELECT '139) COUNT EMP DEPT40';
SELECT COUNT(*) FROM EMP WHERE DEPTNO=40;

SELECT '140) TOTAL SAL REPORTING TO 7839';
SELECT SUM(SAL) FROM EMP WHERE MGR=7839;

SELECT '141) COUNT PRESIDENT SAL>4000';
SELECT COUNT(*) FROM EMP WHERE JOB='PRESIDENT' AND SAL>4000;

SELECT '142) COUNT SALESMAN DEPT30 SAL<5000';
SELECT COUNT(*) FROM EMP WHERE JOB='SALESMAN' AND DEPTNO=30 AND SAL<5000;

SELECT '143) COUNT HIRED 03-DEC-81';
SELECT COUNT(*) FROM EMP WHERE HIREDATE='1981-12-03';

SELECT '144) TOTAL SAL NAME HAVING A';
SELECT SUM(SAL) FROM EMP WHERE ENAME LIKE '%A%';

SELECT '145) AVG SAL SALESMAN DEPT30';
SELECT AVG(SAL) FROM EMP WHERE JOB='SALESMAN' AND DEPTNO=30;



-- =====================================================
-- QUERIES 146–155 :  GROUP BY
-- =====================================================

SELECT '146) EMP COUNT EACH DEPT EXCEPT PRESIDENT';
SELECT DEPTNO,COUNT(*) FROM EMP WHERE JOB<>'PRESIDENT' GROUP BY DEPTNO;

SELECT '147) TOTAL SAL EACH JOB';
SELECT JOB,SUM(SAL) FROM EMP GROUP BY JOB;

SELECT '148) MANAGER COUNT EACH DEPT';
SELECT DEPTNO,COUNT(*) FROM EMP WHERE JOB='MANAGER' GROUP BY DEPTNO;

SELECT '149) AVG SAL EACH DEPT EXCEPT 20';
SELECT DEPTNO,AVG(SAL) FROM EMP WHERE DEPTNO<>20 GROUP BY DEPTNO;

SELECT '150) COUNT NAMES HAVING A EACH JOB';
SELECT JOB,COUNT(*) FROM EMP WHERE ENAME LIKE '%A%' GROUP BY JOB;

SELECT '151) COUNT AND AVG SAL SAL>2000 EACH DEPT';
SELECT DEPTNO,COUNT(*),AVG(SAL) FROM EMP WHERE SAL>2000 GROUP BY DEPTNO;

SELECT '152) TOTAL SAL AND SALESMAN COUNT EACH DEPT';
SELECT DEPTNO,SUM(SAL),COUNT(*) FROM EMP WHERE JOB='SALESMAN' GROUP BY DEPTNO;

SELECT '153) COUNT EMP AND MAX SAL EACH JOB';
SELECT JOB,COUNT(*),MAX(SAL) FROM EMP GROUP BY JOB;

SELECT '154) MAX SAL EACH DEPT';  
SELECT DEPTNO,MAX(SAL) FROM EMP GROUP BY DEPTNO;

SELECT '155) SALARY FREQUENCY';
SELECT SAL,COUNT(*) FROM EMP GROUP BY SAL;


-- =====================================================
-- QUERIES 156–165 :  HAVING CLAUSE
-- =====================================================

PROMPT 156)DNO AND NUMBER OF EMP WORKING IN EACH DEPT IF THERE ARE ATLEAST 2 CLERKS IN EACH DEPT;
SELECT DEPTNO,COUNT(*) FROM EMP WHERE JOB='CLERK' GROUP BY DEPTNO HAVING COUNT(*)>=2;

PROMPT 157) DNO AND TOTAL SAALARY NEEDED TO PAY ALL EMP IN EACH DEPT IF THERE ARE ATLEAST 4 EMP IN EACH DEPT;
SELECT DEPTNO,SUM(SAL) FROM EMP GROUP BY DEPTNO HAVING COUNT(*)>=4;

PROMPT 158) NUMBER OF EMP EARNING SAL MORE THAN 1200 IN EACH JOB AND THE TOTAL SAL NEEDED TO PAY EMP OF EACH JOB MUST EXCEEDS 3800;
SELECT JOB,COUNT(*),SUM(SAL) FROM EMP WHERE SAL>1200 GROUP BY JOB HAVING SUM(SAL)>3800;

PROMPT 159) DEPTNO AND NUMBER OF EMP WORKING ONLY IF THERE ARE 2 EMP WORKING IN EACH DEPT AS MANAGER;
SELECT DEPTNO,COUNT(*) FROM EMP WHERE JOB='MANAGER' GROUP BY DEPTNO HAVING COUNT(*)=2;

PROMPT 160) JOB AND MAX SAL OF EMP IN EACH JOB IF THE MAX SAL EXCEEDS 2600 ;
SELECT JOB,MAX(SAL) FROM EMP GROUP BY JOB HAVING MAX(SAL)>2600;

PROMPT 161) THE SALARIES WHICH ARE REPEATED IN EMP TABLE ;
SELECT SAL FROM EMP GROUP BY SAL HAVING COUNT(*)>1;

PROMPT 162) THE HIREDATE WHICH ARE DUPLICATED IN EMP TABLE;
SELECT HIREDATE FROM EMP GROUP BY HIREDATE HAVING COUNT(*)>1;

PROMPT 164) AVG SALARY OF EACH DEPT IF AVG SAL IS LESS THAN 3000 ;
SELECT DEPTNO,AVG(SAL) FROM EMP GROUP BY DEPTNO HAVING AVG(SAL)<3000;

PROMPT 164) DEPTNO IF THERE ARE ATLEAST 3 EMP IN EACH DEPT WHOS NAME HAS CHAR 'A' OR 'S';
SELECT DEPTNO FROM EMP WHERE ENAME LIKE '%A%' OR ENAME LIKE '%S%' GROUP BY DEPTNO HAVING COUNT(*)>=3;

PROMPT 165) MIN AND MAX SALARIES OF EACH JOB IF MIN SAL IS MORE THAN 1000 AND MAX SAL IS LESS THAN 5000;
SELECT JOB,MIN(SAL),MAX(SAL) FROM EMP GROUP BY JOB HAVING MIN(SAL)>1000 AND MAX(SAL)<5000;


-- PROMPT =====================================================
-- PROMPT QUERIES 166–204 :  SUB QUERIES
-- PROMPT =====================================================

-- PROMPT  >>>>>>>>>>>>>>>>>>>   ASSIGNMENT ON CASE 1


PROMPT 166)NAME OF THE EMPLOYEES EARNING MORE THAN ADAMS 
SELECT ENAME FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'ADAMS');

PROMPT 167) NAME AND SALARY OF THE EMPLOYEES EARNING LESS THAN KING
SELECT ENAME,SAL FROM EMP WHERE SAL < (SELECT SAL FROM EMP WHERE ENAME = 'KING');

PROMPT 168)  NAME AND DEPTNO OF THE EMPLOYEES IF THEY ARE WORKING IN THE SAME DEPT AS JONES
SELECT ENAME,DEPTNO FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'JONES');

PROMPT 169)  NAME AND JOB OF ALL THE EMPLOYEES WORKING IN THE SAME DESIGNATION AS JAMES 
SELECT ENAME,JOB FROM EMP WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME = 'JAMES');

PROMPT 170) EMPNO AND ENAME ALONG WITH ANNUAL SALARY OF ALL THE EMPLOYEES IF THEIR ANNUAL SALARY IS GREATER THAN WARDS ANNUAL SALARY
SELECT EMPNO,ENAME,SAL*12 FROM EMP WHERE SAL*12 > (SELECT SAL*12 FROM EMP WHERE ENAME = 'WARD');


PROMPT 171)  NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED BEFORE SCOTT AND HIRED AFTER THE PRESIDENT 
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME = 'SCOTT') AND HIREDATE > (SELECT HIREDATE FROM EMP WHERE JOB = 'PRESIDENT');


PROMPT 172)  NAME AND SAL OF THE EMPLOYEE IF THEY ARE EARNING SAL LESS THAN THE EMPLOYEE WHOS EMPNO IS 7839
SELECT NAME, SAL FROM EMP WHERE SAL < (SELECT SAL FROM EMP WHERE EMPNO = 7839);


PROMPT 173) ALL THE DETAILS OF THE EMPLOYEES IF THE EMPLOYEES ARE HIRED BEFORE MILLER 
SELECT * FROM EMP WHERE HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME = 'MILLER');


PROMPT 174)  ENAME AND EMPNO OF THE EMPLOYEES IF EMPLOYEES ARE EARNING MORE THAN ALLEN
SELECT ENAME, EMPNO FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'ALLEN');

PROMPT 175) ENAME AND SALARY OF ALL THE EMPLOYEES WHO ARE EARNING MORE THAN MILLER BUT LESS THAN ALLEN
SELECT ENAME, SAL FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'MILLER') AND SAL < (SELECT SAL FROM EMP WHERE ENAME = 'ALLEN');

PROMPT 178) ALL THE DETAILS OF THE EMPLOYEES WORKING IN DEPT 20 AND WORKING IN THE SAME DESIGNATION AS SMITH 
SELECT * FROM EMP WHERE DEPTNO = 20 AND JOB = (SELECT JOB FROM EMP WHERE ENAME = 'SMITH');

PROMPT 179) ALL THE DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE SAME DEPT AS TURNER
SELECT * FROM EMP WHERE JOB = 'MANAGER' AND DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'TURNER');

PROMPT 180) NAME AND HIREDATE OF THE EMPLOYEES HIRED AFTER 1980 AND BEFORE KING 
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE > '1980-01-01' AND HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME = 'KING');

PROMPT 181) ALL THE DETAILS OF EMPLOYEES WHO EARN MORE THAN SCOTT BUT LESS THAN KING
SELECT * FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'SCOTT') AND SAL < (SELECT SAL FROM EMP WHERE ENAME = 'KING');

PROMPT 182) NAME OF THE EMPLOYEES WHOS NAME STARTS WITH 'A' AND WORKS IN THE SAME DEPT AS BLAKE 
SELECT ENAME FROM EMP WHERE ENAME LIKE 'A%' AND DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'BLAKE');

PROMPT 183) NAME AND COMM IF EMPLOYEES EARN COMMISSION AND WORK IN THE SAME DESIGNATION AS SMITH
SELECT ENAME, COMM FROM EMP WHERE COMM IS NOT NULL AND JOB = (SELECT JOB FROM EMP WHERE ENAME = 'SMITH');

PROMPT 184) DETAILS OF ALL THE EMPLOYEES WORKING AS CLERK IN THE SAME DEPT AS TURNER
SELECT * FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'TURNER') AND JOB = 'CLERK';

PROMPT 185) ENAME, SAL AND DESIGNATION OF THE EMPLOYEES WHOS ANNUAL SALARY IS MORE THAN SMITH AND LESS THAN KING
SELECT ENAME, SAL, JOB FROM EMP WHERE SAL*12 > (SELECT SAL*12 FROM EMP WHERE ENAME = 'SMITH') AND SAL*12 < (SELECT SAL*12 FROM EMP WHERE ENAME = 'KING');






-- PROMPT >>>>>>>>>>>>>>>>>>> ASSIGNMENT ON CASE 2:

PROMPT 186) DNAME OF THE EMPLOYEES WHOS NAME IS SMITH 
SELECT DNAME FROM DEPT WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'SMITH');


PROMPT 187) DNAME AND LOC OF THE EMPLOYEE WHOS ENAME IS KING 
SELECT DNAME, LOC FROM DEPT WHERE ENAME = (SELECT ENAME FROM EMP WHERE ENAME = 'KING');

PROMPT 188) LOC OF THE EMP WHOS EMPLOYEE NUMBER IS 7902
SELECT LOC FROM DEPT WHERE ENAME = (SELECT ENAME FROM EMP WHERE EMPNO = 7902);

PROMPT  189)  DNAME AND LOC ALONG WITH DEPTNO OF THE EMPLOYEE WHOS NAME ENDS WITH 'R'
SELECT DNAME, LOC, DEPTNO FROM DEPT WHERE DNAME IN (SELECT DNAME FROM EMP WHERE ENAME LIKE '%R');

PROMPT 190)  DNAME OF THE EMPLOYEE WHOS DESIGNATION IS PRESIDENT
SELECT DNAME FROM DEPT WHERE DNAME IN (SELECT DNAME FROM EMP WHERE JOB = 'PRESIDENT');

PROMPT 191)  NAMES OF THE EMPLOYEES WORKING IN ACCOUNTING DEPARTMENT
SELECT ENAME FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'ACCOUNTING');


PROMPT  192)  ENAME AND SALARIES OF THE EMPLOYEES WHO ARE WORKING IN THE LOCATION CHICAGO
SELECT ENAME, SAL FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = 'CHICAGO');

PROMPT 193)  DETAILS OF THE EMPLOYEES WORKING IN SALES 
SELECT * FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'SALES');

PROMPT 194)  DETAILS OF THE EMP ALONG WITH ANNUAL SALARY IF EMPLOYEES ARE WORKING IN NEW YORK
SELECT *, SAL*12 FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = 'NEW YORK');

PROMPT  195)  NAMES OF EMPLOYEES WORKING IN OPERATIONS DEPARTMENT
SELECT ENAME FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'OPERATIONS');

PROMPT mysql>




-- PROMPT ASSIGNMENT ON CASE 1 & 2

PROMPT 195)  NAMES OF THE EMPLOYEES EARNING MORE THAN SCOTT IN ACCOUNTING DEPT
SELECT ENAME FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'SCOTT') AND DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'ACCOUNTING');

PROMPT 196)  DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE LOCATION CHICAGO 
SELECT * FROM EMP WHERE JOB = 'MANAGER' AND DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = 'CHICAGO');

PROMPT 197)  NAME AND SAL OF THE EMPLOYEES EARNING MORE THAN KING IN THE DEPT ACCOUNTING
SELECT ENAME, SAL FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'KING') AND DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'ACCOUNTING');

PROMPT 198)  DETAILS OF THE EMPLOYEES WORKING AS SALESMAN IN THE DEPARTEMENT SALES 
SELECT * FROM EMP WHERE JOB = 'SALESMAN' AND DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'SALES');

PROMPT 199)  NAME, SAL JOB, HIREDATE OF THE EMPLOYEES WORKING IN OPERATIONS DEPARTMENT AND HIRED BEFORE KING
SELECT ENAME, SAL, JOB, HIREDATE FROM EMP WHERE JOB = 'OPERATIONS' AND HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME = 'KING');


PROMPT 200) DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMET NAMES ENDING 'S'
SELECT ENAME FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME LIKE '%S');

PROMPT 201)  DNAME OF THE EMPLOYEES WHOS NAMES HAS CHARACTER 'A' IN IT
SELECT DNAME FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME LIKE '%A%');

PROMPT 202)   DNAME AND LOC OF THE EMPLOYEES WHOS SALARY IS RUPEES 800 
SELECT DNAME, LOC FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE SAL = 800);

PROMPT 203)  DNAME OF THE EMPLOYEES WHO EARN COMISSION
SELECT DNAME FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE COMM IS NOT NULL);

PROMPT '204)  LOC OF THE EMPLOYEES IF THEY EARN COMISSION IN DEPT 40'
SELECT LOC FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE COMM IS NOT NULL AND DEPTNO = 40);



-- ASSIGNMENT ON TYPES OF SUB QUERY.

PROMPT 205)  NAME OF THE EMPLOYEES EARNING SALARY MORE THAN THE SALESMAN
SELECT ENAME FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE JOB = 'SALESMAN');

PROMPT 206) DETAILS OF THE EMPLOYEES HIRED AFTER ALL THE CLERKS
SELECT * FROM EMP WHERE HIREDATE > (SELECT MAX(HIREDATE) FROM EMP WHERE JOB = 'CLERK');

PROMPT  208) NAME AND HIREDATE OF EMPLOYEES HIRED BEFORE ALL THE MANAGERS
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE < (SELECT MIN(HIREDATE) FROM EMP WHERE JOB = 'MANAGER');

PROMPT 209) NAMES OF THE EMPLOYEES HIRED AFTER ALL THE MANAGERS AND EARNING SALARY MORE THAN ALL THE CLERKS
SELECT ENAME FROM EMP WHERE HIREDATE > (SELECT MAX(HIREDATE) FROM EMP WHERE JOB = 'MANAGER') AND SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB = 'CLERK');

PROMPT 210)  DETAILS OF THE EMPLOYEES WORKING AS CLERK AND HIRED BEFORE ATLEST A SALESMAN 
SELECT * FROM EMP WHERE JOB = 'CLERK' AND HIREDATE < (SELECT MIN(HIREDATE) FROM EMP WHERE JOB = 'SALESMAN');

PROMPT  211) DETAILS OF EMPLOYEES WORKING IN ACCOUNTING OR SALES 
SELECT * FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME = 'ACCOUNTING' OR DNAME = 'SALES');

PROMPT 212) DEPARTMENT NAMES OF THE EMPOYEES WITH NAME SMITH, KING AND MILLER
SELECT DNAME FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME IN ('SMITH', 'KING', 'MILLER'));

PROMPT 213)  DETAILS OF EMPLOYEES WORKING NEWYORK OR CHICAGO
SELECT * FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC = 'NEW YORK' OR LOC = 'CHICAGO');

PROMPT   214) EMP NAMES IF EMPLOYEES ARE HIRED AFTER ALL THE EMPLOYEES OF DEPT 10
SELECT ENAME FROM EMP WHERE HIREDATE > (SELECT MAX(HIREDATE) FROM EMP WHERE DEPTNO = 10);




-- PROMPT =====================================================
-- PROMPT QUERIES 61-70 : NESTED SUB QUERIES
-- PROMPT =====================================================

-- ASSIGNMENT ON NESTED SUB QUERY:

PROMPT 61. WAQTD 2ND MINIMUM SALARY
SELECT MIN(SAL) AS SECOND_MIN_SALARY
FROM EMP
WHERE SAL > (SELECT MIN(SAL) FROM EMP);

PROMPT 62. WAQTD 5TH MAXIMUM SALARY
SELECT MAX(SAL) AS FIFTH_MAX_SALARY
FROM EMP
WHERE SAL < ( SELECT MAX(SAL) FROM EMP
WHERE SAL < (SELECT MAX(SAL) FROM EMP
WHERE SAL < (SELECT MAX(SAL) FROM EMP
WHERE SAL < (SELECT MAX(SAL) FROM EMP))))) ;

PROMPT 63. WAQTD NAME OF THE EMPLOYEE EARNING 3RD MAXIMUM SALARY
SELECT ENAME
FROM EMP
WHERE SAL = (SELECT MAX(SAL) FROM EMP
WHERE SAL < (SELECT MAX(SAL) FROM EMP
WHERE SAL < (SELECT MAX(SAL) FROM EMP))) ) ;

PROMPT 64.WAQTD EMPNO OF THE EMPLOYEE EARNING 2D MAXIMUM SALARY
SELECT EMPNO
FROM EMP
WHERE SAL = (SELECT MAX(SAL) FROM EMP
WHERE SAL < (SELECT MAX(SAL) FROM EMP)) ) ;

PROMPT 65. WAQTD DEPARTMENT NAME OF AN EMPLOYEE GETTING 4TH MAX SAL
SELECT DNAME
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO FROM EMP
WHERE SAL = (SELECT MAX(SAL) FROM EMP
WHERE SAL < (SELECT MAX(SAL) FROM EMP
WHERE SAL < (SELECT MAX(SAL) FROM EMP))) ) ) ;

PROMPT 66. WAQTD DETAILS OF THE EMPLOYEE WHO WAS HIRED 2nd 67.WAQTD NAME OF THE EMPLOYEE HIRED BEFORE THE LAST EMPLOYEE
SELECT *
FROM EMP    
WHERE HIREDATE = (SELECT MAX(HIREDATE) FROM EMP
WHERE HIREDATE < (SELECT MAX(HIREDATE) FROM EMP)) ) ;

PROMPT 68. WAQTD LOC OF THE EMPLOYEE WHO WAS HIRED FIRST
SELECT LOC
FROM DEPT    
WHERE DEPTNO = (SELECT DEPTNO FROM EMP
WHERE HIREDATE = (SELECT MIN(HIREDATE) FROM EMP)) ) ;

PROMPT 69. WAQTD DETAILS OF THE EMPLOYEE EARNING 7TH MINIMUM SALARY
SELECT *
FROM EMP        
WHERE SAL = (SELECT MIN(SAL) FROM EMP
WHERE SAL > (SELECT MIN(SAL) FROM EMP
WHERE SAL > (SELECT MIN(SAL) FROM EMP
WHERE SAL > (SELECT MIN(SAL) FROM EMP
WHERE SAL > (SELECT MIN(SAL) FROM EMP
WHERE SAL > (SELECT MIN(SAL) FROM EMP
WHERE SAL > (SELECT MIN(SAL) FROM EMP
WHERE SAL > (SELECT MIN(SAL) FROM EMP)))))) ) ) ;

PROMPT 70. WAQTD DNAME OF EMPLOYEE GETTING 2ND MAXIMUM SALARY
SELECT DNAME
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO FROM EMP
WHERE SAL = (SELECT MAX(SAL) FROM EMP
WHERE SAL < (SELECT MAX(SAL) FROM EMP)) ) ;


-- PROMPT =====================================================
-- PROMPT QUERIES 61-70 : ASSIGNMENT ON EMP AND MANAGER RELATION
-- PROMPT =====================================================

PROMPT 71 SMITHS REPORTING MANAGER'S NAME'
SELECT MGR FORM EMP WHERE ENAME='SMITH';

PROMPT 72 ADAMS MANAGER'S MANAGER NAME'
SELECT MGR FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='ADAMS');

PROMPT 73 DNAME OF JONES MANAGER
SELECT DNAME FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='JONES'));

PROMPT 74 MILLER'S MANAGER'S SALARY
SELECT SAL FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='MILLER');

PROMPT 75 LOC OF SMITH'S MANAGER'S MANAGER.
SELECT LOC FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='SMITH'))));

PROMPT 76 DNAME OF THE EMPLOYEES REPORTING TO BLAKE
SELECT DNAME FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME='BLAKE'));

PROMPT 77 NUMBER OF EMPLPOYEES REPORTING TO KING
SELECT COUNT(*) FROM EMP WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME='KING');

PROMPT  78 DETAILS OF THE EMPLOYEES REPORTING TO JONES
SELECT * FROM EMP WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME='JONES');

PROMPT 79 ENAMES OF THE EMPLOYEES REPORTING TO BLAKE'S MANAGER';
SELECT ENAME FROM EMP WHERE MGR=(SELECT MGR FROM EMP WHERE EMPNO=(SELECT EMPNO FROM EMP WHERE ENAME='BLAKE'));

PROMPT 80) NUMBER OF EMPLOYEES REPORTING TO FORD'S MANAGER';
SELECT COUNT(*) FROM EMP WHERE MGR=(SELECT MGR FROM EMP WHERE EMPNO=(SELECT EMPNO FROM EMP WHERE ENAME='FORD'));



-- <<<<THEORY QUESTIONS ON JOINS >>>>>>

-- 121) WHAT IS JOINS LIST ALL THE TYPES OF JOINS ?
-- 122) WHAT IS CROSS JOIN EXPLAIN WITH SYNTAX ?
-- 123) WHAT IS INNER JOIN EXPLAIN WITH SYNTAX ?
-- 124) DIFFERENCES BETWEEN CROSS JOIN AND INNER JOIN ?
-- 125) EXPLAIN THE ADVANTAGES AND DISADVANTAGES OF INNER JOIN ?
-- 126) EXPLAIN THE NATURAL JOIN WITH SYNTAX ?
-- 127) WHAT IS OUTER JOIN EXPLAIN ALL OUTER JOIN WITH SYNTAX ?
-- 129) DIFFERENCES BETWEEN LOJ AND ROJ ?
-- 129) WHAT IS SELF JOIN EXPLAIN WITH SYNTAX ?
-- 130) WHAT IS THE USE USING SELF JOIN COMPARE TO SUB QUERY ? 




-- PROMPT =====================================================
-- PROMPT QUERIES 131-150 : INNER JOINS  OR NATURAL JOIN 
-- PROMPT =====================================================

PROMPT 131) WAQTD ENAME AND DNAME FOR ALL THE EMP ?
PROMPT => USING INNER JOIN
SELECT ENAME,DNAME FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO;
PROMPT => BY USING NATURAL JOIN
SELECT ENAME,DNAME FROM EMP NATURAL JOIN DEPT;


PROMPT 132) WAQTD DNAME AND SAL FOR THE EMP WHO ARE WORKING AS MANAGER ?
PROMPT => USING INNER JOIN
SELECT DNAME,SAL FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND JOB='MANAGER';
PROMPT => BY USING NATURAL JOIN
SELECT DNAME, SAL FROM EMP NATURAL JOIN DEPT WHERE JOB='MANAGER';


PROMPT 133) WAQTD SAL AND HIREDATE AND LOC FOR THE EMP  WHOSE NAME HAVING A CHARACTER IN THEIR NAME  ?
PROMPT => USING INNER JOIN
SELECT SAL,HIREDATE,LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND ENAME LIKE '%A%';
PROMPT => BY USING NATURAL JOIN
SELECT SAL,HIREDATE,LOC FROM EMP NATURAL JOIN DEPT WHERE ENAME LIKE '%A%';

PROMPT 134) WAQTD ALL THE DETAILS OF AN EMPLOYEE ALONG WITH LOC FOR AN EMP  WHOSE SAL IS MORE THEN 2000 IN ACCOUNTING DEPARTMENT ?
PROMPT => USING INNER JOIN
SELECT * FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND SAL>2000 AND DNAME='ACCOUNTING';
PROMPT => BY USING NATURAL JOIN
SELECT * FROM EMP NATURAL JOIN DEPT WHERE SAL>2000 AND DNAME='ACCOUNTING';

PROMPT 135) WAQTD DNAME AND SAL AND DEPTNO OF AN EMP  WHOSE JOB IS PRESIDENT  IN DEPTNO 10 ?
PROMPT => USING INNER JOIN
SELECT DNAME,SAL,DEPTNO FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND JOB='PRESIDENT' AND D.DEPTNO=10;
PROMPT => BY USING NATURAL JOIN
SELECT DNAME,SAL,DEPTNO FROM EMP NATURAL JOIN DEPT WHERE JOB='PRESIDENT' AND D.DEPTNO=10;


PROMPT 136) WAQTD ENAME AND DEPTNO AND LOC FOR ALL THE EMP   WHOSE NAME ENDS  WITH VOWELS ?
PROMPT => USING INNER JOIN
SELECT ENAME,DEPTNO,LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND REGEXP_LIKE(ENAME,'[A,E,I,O,U]$');
PROMPT => BY USING NATURAL JOIN
SELECT ENAME, DEPTNO, LOC FROM EMP NATURAL JOIN DEPT WHERE REGEXP_LIKE(ENAME, '[A, E, I, O, U]$');


PROMPT 137) WAQTD HIREDATE AND DEPTNO FOR ALL THE EMP WHOs     ARE WORKING IN  NEW YORK AND HAVING COMM ?
PROMPT => USING INNER JOIN
SELECT HIREDATE,DEPTNO FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND LOC='NEW YORK' AND COMM IS NOT NULL;
PROMPT => BY USING NATURAL JOIN
SELECT HIREDATE,DEPTNO FROM EMP NATURAL JOIN DEPT WHERE LOC = 'NEW YORK' AND COMM IS NOT NULL;


PROMPT 138) WAQTD EMPLOYEE NAME AND DEPARTMENT NAME FOR ALL THE EMPLOYEE WHO  ARE HIRED IN THE MONTH OF FEB INTO ACCOUNTING  DEPARTMENT ?
PROMPT => USING INNER JOIN
SELECT ENAME,DNAME FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND HIREDATE LIKE "%-FEB-%" AND DNAME='ACCOUNTING';
PROMPT => BY USING NATURAL JOIN
SELECT ENAME,DNAEM FROM EMP NATURAL JOIN DEPT WHERE HIREDATE LIKE "%-FEB-%" AND DNAME ='ACCOUNTING';
 

PROMPT 139) WAQTD LOC AND EMPNO AND MGR NO FOR ALL THE EMP WHOSE SAL LESS THEN 5000 IN BOSTON HIRED IN THE YEAR OF 87 ?
PROMPT => USING INNER JOIN
SELECT LOC,EMPNO,MGR FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND SAL<5000 AND LOC='BOSTON' AND HIREDATE = '%-__87';
PROMPT => BY USING NATURAL JOIN
SELECT LOC,EMPNO,MGR FROM EMP NATURAL JOIN DEPT WHERE SAL<5000 AND LOC='BOSTON' AND HIREDATE = '%-__87';


PROMPT 140) WAQTD DNAME AND LOC ALONG WITH 10% HIKE IN THE SALARY OF AN EMPLOYEE   WHO ARE REPORTING TO ALLEN ?
PROMPT => USING INNER JOIN
SELECT DNAME,LOC,SAL*1.10 AS NEW_SAL FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND MGR=(SELECT EMPNO FROM EMP WHERE ENAME='ALLEN');
PROMPT => BY USING NATURAL JOIN
SELECT DNAME,LOC,SAL*1.10 AS NEW_SAL FROM EMP NATURAL JOIN DEPT WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME='ALLEN');


PROMPT 141) WAQTD ANNAUL SALARY AND LOC OF AN EMPLOYEE WHOSE MANAGER NAME IS KING ?
PROMPT => USING INNER JOIN
SELECT SAL*12 AS ANNUAL_SAL,LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND MGR=(SELECT EMPNO FROM EMP WHERE ENAME='KING');
PROMPT => BY USING NATURAL JOIN
SELECT SAL*12 AS ANNUAL_SAL FROM EMP NATURAL JOIN DEPT WHERE MGR=(SELECT ENPNO FROM EMP WHERE ENAME='KING')
;
PROMPT 142) WAQTD ALL TEH DETAILS OF AN EMP AND THEIR DNAME AND  LOC  FOR THE EMPLOYEE WHOSE COMM IS NULL IN DEPTNO 10,20  ?
PROMPT => USING INNER JOIN
SELECT * FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND COMM IS NULL AND D.DEPTNO IN (10,20); 
PROMPT => BY USING NATURAL JOIN
SELECT * FROM EMP NATURAL JOIN DEPT WHERE COMM IS NULL AND DEPTNO IN (10,20);


PROMPT 143) WAQTD DNAME AND ENAME FOR THE EMPLOYEE WHOSE SALARY ENDS WITH 50  IN DEPTNO 10,20,30 AND WORKING IN RESEARCH DEPARTMENT ?
PROMPT => USING INNER JOIN
SELECT DNAME,ENAME FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND SAL LIKE '%50' AND D.DEPTNO IN (10,20,30) AND DNAME='RESEARCH';
PROMPT => BY USING NATURAL JOIN
SELECT DNAME,ENAME FROM EMP NATURAL JOIN DEPT WHERE SAL LIKE '%50' AND DEPTNO IN (10,20,30) AND DNAME='RESEARCH';

PROMPT 144) WAQTD LOC DNAME  AND ENAME OF AN EMP WHO ARE HIRED BEFORE THE LAST TWO EMP ?
PROMPT => USING INNER JOIN
SELECT LOC,DNAME,ENAME FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND HIREDATE<(SELECT MIN(HIREDATE) FROM EMP WHERE HIREDATE > (SELECT MIN(HIREDATE) FROM EMP)));
PROMPT => BY USING NATURAL JOIN
SELECT LOC,DNAME,ENAME FROM EMP NATURAL JOIN DEPT WHERE HIREDATE<(SELECT MIN(HIREDATE) FROM EMP WHERE HIREDATE > (SELECT MIN(HIREDATE) FROM EMP));


PROMPT 145) WAQTD DNAME AND SALARY OF AN EMPLOYEE WHOSE NAME ENDS WITH CONSONANTS ?
PROMPT => USING INNER JOIN
SELECT DNAME,SAL FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND REGEXP_LIKE(ENAME,'[^A,E,I,O,U]$');
PROMPT => BY USING NATURAL JOIN
SELECT DNAME,SAL FROM EMP NATURAL JOIN DEPT WHERE REGEXP_LIKE(ENAME, '[A,I,E,O,U]$');

PROMPT 146) WAQTD MGR SAL AND DEPTNO AND LOC OF AN EMP WHOSE LOC ENDS WITH S ?
PROMPT => USING INNER JOIN
SELECT MGR,SAL,DEPTNO,LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND LOC LIKE '%S';
PROMPT => BY USING NATURAL JOIN
SELECT MGR,SAL,DEPTNO,LOC FROM EMP NATURAL JOIN DEPT WHERE LOC LIKE '%S';


PROMPT 147) WAQTD EMPNO AND LOC FOR THE EMP WHOSE HIREDATE IS '01-JAN-81' IN DALLAS ?
PROMPT => USING INNER JOIN
SELECT EMPNO,LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND HIREDATE='01-JAN-1981' AND LOC='DALLAS';
PROMPT => BY USING NATURAL JOIN
SELECT EMPNO,LOC FROM EMP NATURAL JOIN DEPT WHERE HIREDATE='01-JAN-1981' AND LOC='DALLAS';   


PROMPT 148) WAQTD ENAME AND LOC AND SAL OF AN EMPLOYES WHOSE EMPNO ARE 7369,7488 ?
PROMPT => USING INNER JOIN
SELECT ENAME,LOC,SAL FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND EMPNO IN (7369,7488);
PROMPT => BY USING NATURAL JOIN
SELECT ENAME,LOC,SAL FROM EMP NATURAL JOIN DEPT WHERE EMPNO IN (7369,7488);


PROMPT 149) WAQTD ENAME AND LOC FOR THE EMP WHOSE SAL IS LESS THEN KING AND MORE THEN SMITH IN DEPTNO 30 AND WORKING IN SALES DEPARTMENT ?
PROMPT => USING INNER JOIN
SELECT ENAME,LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND SAL<(SELECT SAL FROM EMP WHERE ENAME='KING') AND SAL>(SELECT SAL FROM EMP WHERE ENAME='SMITH') AND D.DEPTNO=30 AND DNAME='SALES';
PROMPT => BY USING NATURAL JOIN
SELECT ENAME,LOC FROM EMP NATURAL JOIN DEPT WHERE SAL<(SELECT SAL FROM EMP WHERE ENAME='KING') AND SAL>(SELECT SAL FROM EMP WHERE ENAME='SMITH') AND D.DEPTNO=30 AND DNAME='SALES';


PROMPT 150) WAQTD COMM AND LOC FOR THE EMP WHOSE MGR IS 7902 WORKING IN ACCOUNTING AND RESEARCH DEPARTMENT ?
PROMPT => USING INNER JOIN
SELECT COMM,LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND MGR=7902 AND DNAME IN ('ACCOUNTING','RESEARCH');
PROMPT => BY USING NATURAL JOIN
SELECT COMM,LOC CMMO,LOC FROM EMP NATURAL JOIN DEPT WHERE MGR=7902 AND DNAME IN ('ACCOUNTING','RESEARCH');



-- PROMPT =====================================================
-- PROMPT QUERIES 151-170 : ASSIGNMENT ON  OTHER JOINS
-- PROMPT =====================================================



PROMPT 151) WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES OF THE EMPLOYEES NOT WORKING IN ANY DEPARTMENT ?
SELECT ENAME, DNAME FROM EMP LT, DEPT RT WHERE LT.DEPTNO = RT.DEPTNO(+) AND DEPTNO IS NULL;

PROMPT 152) WAQTDALL THE DETAILS OF AMPLOYEES AND THEIR DEPARTMENT DETAILS IF THE DEPARTMENT IN WHICH NO EMPLOYEES ARE WORKING ?
SELECT * FROM EMP LT, DEPT RT WHERE LT.DEPTNO = RT.DEPTNO(+) AND EMPNO IS NULL;

PROMPT 153) WAQTD ALL THE DETAILS OF AN EMPLOYEES AND HIER DEPARTMENT DETAILS IF THE EMPLOYEES NOT WORKING IN ANY DEPARTMENT AND THE DEPARTMENT IN WHICH THE NO EMPLOYEES ARE  WORKING ?
SELECT * FROM EMP LT, DEPT RT WHERE LT.DEPTNO = RT.DEPTNO(+) AND EMPNO IS NULL AND DEPTNO IS NULL;

PROMPT 154) WAQTD ENAME AND SAL AND DNAME FOR THE EMPLOYEES THOSE WHO ARE NOT WORKING IN ANY DEPARTMENT ?
SELECT ENAME, SAL, DNAME FROM EMP LT, DEPT RT WHERE LT.DEPTNO = RT.DEPTNO(+) AND EMPNO IS NULL;

PROMPT 155) WAQTD HIERDATE AND JOB INCLUDING DNAME AND LOC FOR THE DEPARTMENT IN WHICH NO EMPLOYEES ARE WORKING  ?
SELECT HIREDATE, JOB, DNAME, LOC FROM EMP LT, DEPT RT WHERE LT.DEPTNO = RT.DEPTNO(+) AND DEPTNO IS NULL;

PROMPT 156) WAQTD DNAME AND LOC AND JOB FOR THE EMPLOYEES WHO ARE NOT WORKING IN ANY DEPARTMENT AND THE DEPARTMENT NO EMPLOYEES ARE WORKING ?
SELECT DNAME, LOC, JOB FROM EMP LT, DEPT RT WHERE LT.DEPTNO = RT.DEPTNO(+) AND EMPNO IS NULL AND DEPTNO IS NULL;

PROMPT 157) WAQTD EMPLOYEES NAME AND DEPTNAME FOR ALL THE EMPLOYEES WHOSE SALARIES ARE MORE THEN 2000 ?
SELECT ENAME, DNAME FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND SAL > 2000;

PROMPT 158) WAQTDMANAGER NAME AND THE EMPLOYEES SALARY FOR ALL THE EMPLOYEES THOSE WHO ARE WORKING IN DEPTNO 10,20 ?
SELECT MGR, SAL FROM EMP WHERE DEPTNO IN (10,20);
SELECT RT.ENAME, LT.SAL FROM EMP LT SELF JOIN EMP RT ON LT.MGR = RT.ENPNO;

PROMPT 159) WAQTD MANAGERS MANAGER NAME FOR ALL THE MANAGER WHOSE SALARIES ARE LESS THEN EMPLOYES ?
SELECT MGR FROM EMP E1, EMP M1 WHERE E1.MGR = M1.EMPNO AND M1.SAL < E1.SAL;

PROMPT 160) WAQTD EMPLOYEES NAME MANAGER SALARY AND MANAGER MANAGE COMM FOR ALL THE MANAGER WHO HIRED BEFORE THE 87 AS SALESMAN AND EARNING SALARY MORE THEN MANAGERS MANAGER ?
SELECT ENAME, SAL, MGR, COMM FROM EMP E, DEPT D,EMP M WHERE E.DEPTNO = D.DEPTNO AND E.MGR = M.EMPNO AND HIREDATE < '1987-01-01' AND JOB = 'SALESMAN' AND SAL > (SELECT SAL FROM EMP WHERE EMPNO = M.MGR);

PROMPT 161) WAQTD ENAME AND MANAGER HIREDATE AND JOB FOR ALL THE EMPLOYEES WHO ARE WORKING IN NEW YORK ?
SELECT ENAME, HIREDATE, JOB FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND LOC = 'NEW YORK';

PROMPT 162) WAQTD EMPLOYEES DNAME AND MANAGER LOC INCLUDING EMPLOYEES SALARY AND MANAGER DEPTNO FOR ALL THE EMPLOYEES WHO ARE HIRED BEFORE THE MANAGERS MANAGE ?
SELECT ENAME, LOC, SAL, MGR FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND HIREDATE < (SELECT HIREDATE FROM EMP WHERE EMPNO = MGR);
PROMPT 163) WAQTD MANAGERS MANAGER NAME FOR ALL THE EMPLOYEES WHO ARE WORKING IN MANAGERS LOCATION AND NOT WORKING IN MANAGES MANAGERS LOCATION ?
SELECT MGR FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND LOC = (SELECT LOC FROM EMP WHERE EMPNO = MGR) AND LOC <> (SELECT LOC FROM EMP WHERE EMPNO = (SELECT MGR FROM EMP WHERE EMPNO = MGR));
PROMPT 164) WAQTD MANAGER NAME FOR THE MANAGERS MANAGER WHO ARE WORKING IN DEPTNO 20 AS ACTUAL MANAGER AND EARNING SALARY MORE THEN THE EMPLOYEES ?
SELECT MGR FROM EMP WHERE DEPTNO = 20 AND SAL > (SELECT SAL FROM EMP WHERE EMPNO = MGR);
PROMPT 165) WAQTD MANAGERS DNAME AND MANAGERS MANAGER LOC FOR THE EMPLOYEES WHO ARE WORKING IN BOSTON ?
SELECT DNAME, LOC FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND LOC = 'BOSTON' AND MGR IS NOT NULL;
PROMPT 166) WAQTD EMPLOYEES DNAME FOR THE MANAGERS MANAGER WHOSE SAL ARE MORE THAN MANAGER AND LESS THAN EMPLOYEES ?
SELECT DNAME FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND SAL > (SELECT SAL FROM EMP WHERE EMPNO = MGR) AND SAL < (SELECT SAL FROM EMP WHERE EMPNO = MGR);
PROMPT 167) WAQTD EMPLOYEES LOC AND MANAGERS MANAGERS LOC FOR THE MANAGER WHO ARE HIRED BEFORE THE EMPLOYEE AND EARNING SALARY MORE THAN THE EMPLOYEES ?
SELECT LOC FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND HIREDATE < (SELECT HIREDATE FROM EMP WHERE EMPNO = MGR) AND SAL > (SELECT SAL FROM EMP WHERE EMPNO = MGR);
PROMPT 168) WAQTD MANAGERS MANAGERS MANAGER NAME FOR THE EMPLOYEES WHO ARE WORKING IN MANAGERS MANAGERS MANAGERS LOC AND EARNING SALARY LESS THE MANAGERS HIRED BEFORE MANAGERS MANAGERS MANAGER ?
SELECT MGR FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND LOC = (SELECT LOC FROM EMP WHERE EMPNO = (SELECT MGR FROM EMP WHERE EMPNO = MGR)) AND SAL < (SELECT SAL FROM EMP WHERE EMPNO = MGR) AND HIREDATE < (SELECT HIREDATE FROM EMP WHERE EMPNO = MGR);
PROMPT 169) WAQTD DNAME FOR THE EMPLOYEES WHO HIRED BEFORE  THE MANAGERS INTO ACCOUNTING DEPARTMENT IN THE MONTH OF DEC ?
SELECT DNAME FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND HIREDATE < (SELECT HIREDATE FROM EMP WHERE EMPNO = MGR) AND DNAME = 'ACCOUNTING' AND HIREDAT LIKE '%DEC%';
PROMPT 170) WAQTD MANAGERS MANAGERS MANAGERS MANAGER NAME IF THEY ARE HIRED AFTER THE MANAGERS INTO DALLAS ?
SELECT MGR FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND HIREDATE > (SELECT HIREDATE FROM EMP WHERE EMPNO = MGR) AND LOC = 'DALLAS';

-- PROMPT =====================================================
-- PROMPT SOME QUERIES : ADDED QUESTIONS ON OTHER JOINS 
-- PROMPT =====================================================

PROMPT WAQTD ENAME ,LOC , AND SAL OF ALL THE EMPLOYEES EVEN IF THEY NOT ASSIGNED TO ANY DEPARTMENT . WORKING AS SALESMAN AND EARNING SALARY MORE THEN 1000 ?
SELECT ENAME, LOC, SAL FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND DNAME = 'SALESMAN' AND SAL > 1000;
PROMPT WAQTD ENAME ,LOC ,DNAME  AND SAL OF ALL THE DEPARTMENTS EVEN IN THAT THERE IS NO EMPLOYEES ARE WORKING AND LOC BELONGS TO NEW YORK ?

PROMPT WAQTD ENAME ,LOC , AND DNAME ,HIREDATE  SAL OF ALL THE EMPLOYEES EVEN IF THEY NOT ASSIGNED TO ANY DEPARTMENT . WORKING AS SALESMAN AND WHOSE NAME STARTS WITH CONSONANTS  ?

PROMPT WAQTD ALL THE EMPLOYEES DETAILS AND THEIR DEPARTMENT DETAILS EVEN THE EMPLOYEES ARE NOT ASSIGNED TO ANY LOCATION IF DEPARTMENT NAME HAVING A CHARACTERS 


-- ADDED QUESTIONS ON OTHER JOINS 
-- WAQTD ENAME ,LOC , AND SAL OF ALL THE EMPLOYEES EVEN IF THEY NOT ASSIGNED TO ANY DEPARTMENT . WORKING AS SALESMAN AND EARNING SALARY MORE THEN 1000 ?
-- WAQTD ENAME ,LOC ,DNAME  AND SAL OF ALL THE DEPARTMENTS EVEN IN THAT THERE IS NO EMPLOYEES ARE WORKING AND LOC BELONGS TO NEW YORK ?
-- WAQTD ENAME ,LOC , AND DNAME ,HIREDATE  SAL OF ALL THE EMPLOYEES EVEN IF THEY NOT ASSIGNED TO ANY DEPARTMENT . WORKING AS SALESMAN AND WHOSE NAME STARTS WITH CONSONANTS  ?
-- WAQTD ALL THE EMPLOYEES DETAILS AND THEIR DEPARTMENT DETAILS EVEN THE EMPLOYEES ARE NOT ASSIGNED TO ANY LOCATION 
-- IF DEPARTMENT NAME HAVING A CHARACTERS 













-- SCENARIO BASED QUESTIONS 
-- ASSUME STD TABLE AND TRAINER TABLE 
-- STD —(  SID , SNAME , DOB , MNO , COURSE ,TID (FK)) CHILD TABLE
-- TRN –(TID(PK),TNAME ,SAL, HQUALIFICATION,BRANCH) PARENT TABLE
-- Q1. WAQTD SNAME , DOB , TNAME ,BRANCH FOR ALL THE STUDENTS EVEN THE STD ARE NOT ASSIGNED TO ANY TRAINERS  ?
-- Q2.WAQTD ALL THE STUDENTS DETAILS AND THEIR TRAINERS DETAILS 
--    FOR ALL TRAINER EVEN THE TRAINER THEY ARE NOT ASSIGNED TO ANY  STUDENTS ?
-- Q3.WAQTD ALL THE TRAINERS AND STUDENTS DETAILS EVEN THE STUDENTS WHO ARE NOT ASSIGNED TO ANY TRAINERS AND ALSO THE TRAINERS WHO ARE NOT ASSIGNED TO ANY STUDENTS ?

-- ASSUME DOCTOR AND PATIENT TABLES 
-- DOCTOR —- (DID ,DNAME , MNO ,SPEC,EXP)  — PARENT TABLE 
-- PATIENT — (PID ,PNAME , DOB , MNO , GMAIL, ADDRESS) — CHILD TABLE 
-- Q1. WAQME , PID DNAME , PNADRESS FOR ALL THE DOCTORS EVEN THE DOCTORS ARE 
-- NOT ASSIGNED TO ANY PATIENT ?
-- Q2. WAQTD ALL THE DOCTORS DETAILS AND PATIENT DETAILS FOR ALL THE PATIENT EVEN THE PATIENT ARE NOT ASSIGNED TO ANY DOCTORS AND THE PATIENT ADDRESS IS PUNE ?
-- Q3. WAQTD ALL THE DOCTORS DETAILS AND PATINETS DETAILS EVEN THE DOCTORS ARE NOT ASSIGNED TO ANY PATIENT AND ALSO THE PATIENTS ARE NOT ASSIGNED TO ANY DOCTORS ?













-- >>>> ASSIGNMENT ON DDL DML TCL DCL >>>>
-- 171) WAQT CREATE ANY ONE TABLE WITHOUT ANY PRIMARY KEY WITH 5 COLUMNS ?
-- 172) WAQT RENAME THE EMP TABLE NAME TO EMPLOYEES  ?
-- 173) WAQT TRUNCATE THE SALGRADE TABLE  ?
-- 174) WAQT DROP THE EMP ANY ONE TABLE FROM DATABASE AND GET IT BACK  ?
-- 175) WAQT PURGE THE ANY ONE TABLE  ?
-- 176) WAQT CREATE TWO TABLES AND MAKE  THE CONNECTION BETWEEN THESE TWO TABLES  ?
-- 177) WAQT ADD THE ONE COLUMN INTO EMPLOYEES TABLE ?
-- 178) WAQT ADD TWO COLUMN INTO DEPT TABLE ?
-- 179) WAQT DROP THE RECENTLY ADDED COLUMN FROM THE EMP TABLE ?
-- 180) WAQT RENAME THE COLUMN FROM EMP AND DEPT TABLE  FOREIGN KEY AS DNO ?

-- 181) WAQT INSERT 5 RECORDS INTO EMP TABLE ?
-- 182) WAQT DELETE THE EMPLOYEES RECORD WHOSE NAME IS KING ?
-- 183) WAQT UPDATE THE SALARY OF SMITH AS 5000 ?
-- 184) WAQT  UPDATE THE JOB OF ALL THE EMPLOYEES AS MANAGER  WHO ARE GETTING SAL <1600 ?
-- 185) WAQT DELETE THE EMPLOYEES RECORD WHO ARE WORKING IN NEW YORK ?
-- 186) WAQT DELETE THE EMPLOYEES RECORDS WHO ARE EARNING SALARY MORE THEN  SMITH AND HIRED BEFORE SCOTT ?
-- 187) WAQT TO UPDATE THE COMM FOR ALL THE EMPLOYEES WHO ARE REPORTING TO KING  AS 1000 ?
-- 188) WAQT UPDATE THE JOB AS BOSS AND SALARY AS 90000 FOR THE EMPLOYEES WHOSE DNAME HAVING EXACTLY ONE A ?
-- 189) WAQT TAKE PERMISSION FROM THE SCOTT AND DELETE THE RECORDS WHOSE SALARY IS 3000  IN HR DATABASE ?
-- 190) WAQT RETAKE THE PERMISSION FROM HR AND TRY TO DELETE THE RECORDS WHOSE SAL IS MORE THEN 2000 ?







-- >>>>> THEORY  STATEMENT  QUESTIONS  >>>>>>
-- 191) WHAT ARE THE  DIFFERENCE BETWEEN DELETE AND TRUNCATE ?
-- 192) DIFFERENCE BETWEEN DELETE DROP AND TRUNCATE ?
-- 193) DIFFERENCE BETWEEN ALTER AND UPDATE ?
-- 194) SYNTAX FOR CREATE TABLE WITH PRIMARY KEY AND FOREIGN KEY ?
-- 195) SYNTAX FOR GRANT AND REVOKE ?
-- 196) SYNTAX FOR DML ?
-- 197) SYNTAX FOR ALL THE STATEMENT OF DDL ?
-- 198) SYNTAX FOR CHECK THE CONSTRAINTS ?
-- 199) SYNTAX FOR TO CHECK THE TABLE LIST FROM RECYCLE BIN ?
-- 20) SYNTAX FOR TO CHECK THE PERMISSION LIST ?
-- 201) SYNTAX FOR TCL STATEMENTS ?
-- 202) SYNTAX FOR SELECTION AND PROJECTION  ?
-- 203) DIFFERENCE BETWEEN PROJECTION AND SELECTION ?
-- 204) DIFFERENCE BETWEEN DDL AND DML ?
-- 205) SYNTAX FOR TO CREATE THE INDEX ?
-- 206) SYNTAX FOR TO CHECK THE STRUCTURE OF TABLE ?
-- 207) SYNTAX FOR TO ADD THE COLUMN INTO TABLE ?
-- 208) SYNTAX FOR TO DROP THE COLUMN FROM THE TABLE ?
-- 209) SYNTAX FOR TO CHANGE THE DATATYPES ?
-- 210) SYNTAX FOR TO CHANGE FROM NULL TO NOT NULL OR VISE VERSA ?















-- SRF QUESTIONS  /  ASSIGNMENT 

-- 211) WAQTD THE NO OF CHARACTERS PRESENT IN YOUR NAME ?
-- 212) WAQTD THE DEATILS OF THE EMPLOYEES WHOSE NAME HAVING 
--    4 CHARACTERS ?
-- 213) WAQTD ENAME AND LOC OF ALL THE EMPLOYEES WHO ARE EARNING 4 DIGIT OF SALARY ?
-- 214) WAQT GET THE REMINDER VALUES OF 10 /5 ?
-- 215) WAQTD THE DEATILS OF EMPLOYEES WHOSE NAME ENDS WITH VOWELS ?
-- 216) WAQTD ALL THE DEATILS OF THE EMPLOYEES WHO AHEV MORE THEN 513 MONTHS 
--    OF EXPERIANCE ?
-- 217) WAQT REPLACE THE 3RD A FROM THE MALAYALAM ?
-- 218) WAQTD THE FIRST HALF NAME OF EMPLOYEES SAME AND 2ND HALF NAME 
--    OF EMPLOYEES IN REVERSE MANNAER ?
-- 219) WAQT REPLACE THE FIRST 6 NUMBER AS (*) FROM 9900199001 ?
-- 220) WSQTD OF THE EMPLOYEES WHOSE NAME HAVING EXACTLY 2 A IN THEIR NAMES ?
-- 221) WAQTD DNAME AND SAL OF ALL THE EMPLOYEES WHOSE NAMES ARE PALYDROM IN NATURE ?
-- 222) WAQTD DNAME AND ENAME OF ALL THE EMPLOYEES WHOSE 2ND HALF NAME PALYDROM IN NATURE ?
-- 223) WAQTD THE TOTAL SALARY NEEDED TO PAY FOR EACH AND EVERY EMPLOYEES ?(NVL)
-- 224) WAQTD THE DETAILS OF THE EMPLOYEES WHO ARE EARNING 3RD MAX SALARY FROM EMP TABLE ?
-- 225) WAQTD THE 2ND MAX SALARY FROM EACH AND EVERY JOB ?
-- 226) WAQTD THE EMPLOYEES NAME AND THEIR DNAME IN INITCAP FORMAT 
--     AND ALSO DISPLAY THEIR JOB IN LOWER CASE FORMAT ?
-- 227) WAQT GET THE NO OF MONTHS BETWEEN YOUR DATE OF BIRTH TO TODAYS DATE ?
-- 228) WAQT GET THE YOUR CURRENT AGE IN YEAR FORMAT UPTO THE DATE ?
-- 229) WAQT CONCAT ENAME WITH THEIR  HALF DNAME OF ALL THE EMPLOYEES ?
-- 230) WAQT GET THE DEATILS OF THE EMPLOYEES IF THEIR NAME HAVING % AS LAST LETTER ?
-- 231) WAQTD THE DETAILS OF AN EMPLOYEES IF THEIR SALARIES ARE PALYDROM IN NATURE ?
-- 232) WAQTD ALL THE EMPLOYEES IF THEIR NAME AND DNAME STARST WITH SAME LETTER ?
-- 233) WAQTD ALL THE EMPLOYEES IF THEIR NAME AND DNAME STARST AND ENDS WITH SAME LETTER ?
-- 234) WAQTD THE LOC AND DNAME AND JOB OF ALL THE EMPLOYEES IF THEIR NAME MIDDLE 
--     LETTERS ARE VOWELS ?
-- 235) WAQT GET EXACTLY THE MIDDLE NAME FROM  "VIRAT ANUSKHA KHOLI" ?
-- 236) WAQT PRINT THE DEATILS IN GIVEN FLOW 
--     "HI SMITH GOOD MORNING YOUR DESIGNATION IS CLERK AND SALARY IS 800 YOUR 
--     DEPTNO IS 20"  SAME FORMAT FOR ALL THE EMPLOYEES  ?
-- 237) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE HIRED ON WENSEDAY ?
-- 238) WAQTD ALL THE DEATILF OF EMPLOYEES AND THEIR DEPARTMENT IF THEY ARE 
--     HIRED IN THE MONTH OF DEC , JAN , FEB ?
-- 239) WAQTD ALL THE EMPLOYEES IF THEY ARE HIRED IN THE YEAR OF 81, 87, 82 ?
-- 240) WAQT GET THE YOUR CURRENT AGE WITH DAY OF BORN ?



--  DIFFERENCES QUESTIONS IN SQL 
-- 241) DIFFERENCES BETWEEN DMBS AND RDBMS ?
-- 242) DIFFERENCES BETWEEN CHAR AND VARCHAR ?
-- 243) DIFFERENCES BETWEEN SQL AND NO SQL ?
-- 244) DIFFERENCES BETWEEN PROJECTION AND SELECTION ?
-- 245) DIFFERENCES BETWEEN WHERE CLAUSE AND HAVING CLAUSE ?
-- 246) DIFFERENCES BETWEEN ALIAS AND DISTINCT ?
-- 247) DIFFERENCES BETWEEN DISTINCT AND UNIQUE ?
-- 248) DIFFERENCES BETWEEN PRIMARY KEY AND FOREIGN KEY ?
-- 249) DIFFERENCES BETWEEN PRIMARY KEY AND UNIQUE ?
-- 250)DIFFERENCES BETWEEN NULL AND NOT NULL ?
-- 251)DIFFERENCES BETWEEN EXPRESSION AND ALIAS ?
-- 252)DIFFERENCES BETWEEN FUNCTIONS AND OPERATORS ?
-- 253)DIFFERENCES BETWEEN USER DEFINED FUNCTION AND BUILT IN FUNCTIONS ?
-- 254)DIFFERENCES BETWEEN SRF AND MRF ?
-- 255)DIFFERENCES BETWEEN SQSR AND MRSQ ?
-- 256)DIFFERENCES BETWEEN SUB QUERY AND JOINS ?
-- 257)DIFFERENCES BETWEEN ALL AND ANY OPERATORS ?
-- 258)DIFFERENCES BETWEEN INNER JOIN TO CARETESIAN JOIN ?
-- 259)DIFFERENCES BETWEEN NATURAL TO INNER JOIN ?
-- 260)DIFFERENCES BETWEEN OUTER JOIN TO INNER JOIN ?
-- 261)DIFFERENCES BETWEEN DELETE AND TRUNCATE ?
-- 262)DIFFERENCES BETWEEN DROP AND DELETE ?
-- 263)DIFFERENCES BETWEEN FLASHBACK AND ROLLBACK ?
-- 264)DIFFERENCES BETWEEN ALTER AND UPDATE ?
-- 265)DIFFERENCES BETWEEN TABLES AND VIEWS ?



-- RULES OF DDL /DML/
-- DDL :
-- 1) CREATE TABLE 
--    RULE 1. THE TABLE NAME /COLUMN_NAME SHOULDN'Y STARTS WITH ANY 
--             NUMBER /SPECIAL CHARACTERS 
--             EX :1EMP / @EMP  ---- IN VALID TABLE_NAME 
--                  EMP1 / EMP@ /E1MP /E@MP ---- VALID TABLE_NAME 
--                  SAME FOR COLUMN_NAME ALSO 
--     RULE 2. THE TABLE_NAME SHOULDN'T REPEATS IN DATABSE 
--     RULE 3. WHILE CREATING TABLE IF WE CREATE PARENT TABLE FIRST AND
--             CHILD TABLE SECOND IT WILL EASY TO CREATE 
     
-- 2) RENAME TABLE 
--     READ THE 1ST RULE OF TABLE_NAME

-- 3) TRUNCATE TABLE 
--    RULE : IF WE ARE TRUNCATING PARENT TABLE ITS NOT POSSIBLE 
--            UNTILL WE REMOVES THE CONNECTION BETWEEN PT AND CT 

-- 4) DROP TABLE 
--     RULE : IF WE WANT TO DROP THE PARENT TABLE WE NEED TO REMEOVE THE CONNECTION THEN WE CAN OTHER TABLE WE CAN DROP EASILY 







-- 5) ALTER : ITS MEANS MODIFICATION OF TABLE 
--      RULE : ALTER COMMAND MOST OF TIME WILL WORKS FOR EMPTY TABLES 
--            EFW COMMANDS IN ALTER WILL WORKS FOR FILLED TABLE 

--     1) ADD COLUMN 
--        RULE : WE CAN ADD COLUMN FOR ANY TABLE IF TABLE IS EMPTY 
--                OR ELSE WE CAN USE NULL CONSTRAINTTO ADD COLUMN 
--               IF WE USE NOT NULL THEN WE CAN ADD COLUMN ONLY EMPTY TABLE 
--      2) DROP COLUMN 
--         THERE IS NO RUELS 
--      3) RENAME COLUMN 
--         COLUMN_NAME RULES WE NEED FOLLOW 
--      4) CHANGE DATATYPE OF COLUMNS 
--         RULE 1 : FOR EMPTY COLUMN WE CAN CHANGE DATATYPES 
--                  IF COLUMN FILLED WITH DATA WE CAN INCREASE THE SIZE OF 
--                  IT BUT WE CANT ABLE CHANGE IT 
--       5) CHANGE NULL TO NOT NULL 
--          RULE1 : FOR PK ITS NOT VALID 
--       6) MAKE PR / FK 
--          RULE FOR PK 1) ONLY ONE PK SHOULD BE PRESENT IN TABLE 
--          RULE FOR FK 1) THE COLUMN SHOULD BE PK IN ANOTHER/ SAME TABLE 
 
--     NOTE FOR ALTER : MOST OF TIME THE ALTER WILL WORK FOR EMPTY                           TABLE   FEW COMMANDS WILL WORK FOR FILLED TABLE












-- DML RULES 
-- 1) INSERT 
--    RULE1 : WE CAN INSERT FOR ANY TABLE BUT WILE INSERTING INTO 
--            CHILD TABLE THE FOREIGN KEY COLUMN VALUE THAT VALUE 
--            SHOULD BE PRESENT IN PARENT TABLE ALSO 

-- 2) DELETE 
--    RULE1 : WE CAN DELETE ANY RECORD FROM THE ANY TABLE BUT 
--            WHILE DELETING RECORDS FROM THE PARENT TABLE WE NEED TO 
--            REMOVE THE CONNECTION ELSE ITS NOT POSSIBLE 

-- 3) UPDATE 
--    RULE1 : WE CAN UPDATE ANY TABLE BUT WHILE UPDATING 
--            THE VALUE OF PARENT TABLE IN THAT THE PK WE
--            NEED TO USE THE VALUES WHICH ARE PRESENT IN CHILD TABLE /NULL  
--            WHERE AS UPDATING THE CHILD TABLE FK VALUE WE NEED 
--            USE THE VALUE WHICH ARE PRESENT IN PARENT TABLE 



















-- Projects 
-- general project in sql 
-- Create a table Customer with the following columns:(parent table)

-- Cid (Primary Key)
-- cname (Customer Name)
-- Mail (Unique Email)
-- Mno (Mobile Number)
-- Dob (Date of Birth)
-- Address (Customer Address)

-- note
-- insert 10 records to customer table make sure 2
-- customers shouldn't associats to any account 

-- Create a table Bank with the following columns:(child table)

-- Bid (Primary Key)
-- Cid (Foreign Key → Customer.Cid, also UNIQUE)
-- Bname (Bank Name)
-- Acno (Unique Account Number)
-- Available_Balance (Decimal Value)

-- note 
-- insert 8 records which matches 8 customer from customer table 
-- Ensure one-to-one relationship between Customer and Bank.











-- Project 2
-- Create table Boys (parent):
-- bid (Primary Key)
-- bname
-- age
-- height
-- type

-- Create table Girls (child):
-- gid (Primary Key)
-- gname
-- age
-- height
-- type
-- bid (Foreign Key → Boys.bid)

-- Insert 6 Boys records.
-- Insert 18 Girls records with these conditions:
-- At least 2 boys should not have any girlfriends.
-- At least 2 girls should not have any boyfriends (their bid should be NULL).
-- Rest should maintain one-to-many (e.g., Boy1 → 4 girls, Boy2 → 3 girls, Boy3 → 5 girls).














-- Project 3 

-- Create a table named Films with the following columns:
-- fid (NUMBER, Primary Key)
-- fname (VARCHAR2(100)) – film name
-- genre (VARCHAR2(50)) – e.g., Action, Comedy
-- release_year (NUMBER(4)) – year of release
-- budget (NUMBER(10)) – film budget

-- Create a table named Actor with the following columns:
-- aid (NUMBER, Primary Key)
-- aname (VARCHAR2(100)) – actor name
-- dob (DATE) – date of birth
-- nationality (VARCHAR2(50))

-- Create a junction table named Film_Actors to represent
-- the many-to-many relationship between Films and Actors.
-- fid references Films(fid)
-- aid references Actors(aid)
-- role_name (VARCHAR2(50)) – character played in the film
-- salary (NUMBER(10)) – actor’s salary for that film



-- note
-- Ensure (fid, aid) is a Composite Primary Key.
-- Insert at least 5 records into the Films table (cover different genres & years).
-- Insert at least 6 records into the Actors table (mix of male/female, different nationalities).
-- insert records into Film_Actors such that:
-- Each film has at least 2 actors.
-- At least 2 actors appear in more than one film.
-- At least 1 actor has a different role_name in different films.
-- No duplicate (fid, aid) combination is allowed.



-- PROJECT4
-- Q1.Create a table BOOK with the following columns:
-- bid (Primary Key, Number)
-- bname (Varchar2(100), Not Null)
-- price (Number with 2 decimals)
-- no_of_pages (Number)
-- published_date (Date)

-- Q2.Create a table AUTHOR with the following columns:
-- aid (Primary Key, Number)
-- aname (Varchar2(100), Not Null)
-- dob (Date)
-- address (Varchar2(200))

-- Q3.Create a junction table BOOK_AUTHOR with columns:
-- bid (Foreign Key references BOOK)
-- aid (Foreign Key references AUTHOR)
-- Make (bid, aid) as a Composite Primary Key.

-- INSERT 7 RECORDS INTO BOOK 
-- INSERT 12 RECORDS INTO AUTHOR 
-- THEN INSERT JUNCTION TABLE THE RECORDS IN 
-- SUCH A WAY THAT MANY TO MANY CONNECTION BETWEEN BOOK TO AUTHOR 
-- 2 RECORDS FROM BOOK TABLE SHOULDN'T CONNECT TO ANY AUTHOR AND 3 AUTHOR 
-- SHOULDN'T CONNECT TO ANY BOOK 


-- 4) Tables:
-- GAME → gid (PK), gname, genre, price
-- PLAYER → pid (PK), pname, level
-- GAME_PLAYER → junction

-- 5) Tables:
-- SONG → sid (PK), sname, duration, album
-- SINGER → sgid (PK), sgname, country
-- SONG_SINGER → junction


-- *Project 5 
-- * Banking System Database

-- *Description:* Design a database to manage customer accounts, transactions, and employee information for a banking system.

-- *Tables:*
-- 1. *Customers*
--     - Customer ID (primary key)
--     - Name
--     - Address
--     - Phone Number
--     - Email
-- 2. *Accounts*
--     - Account ID (primary key)
--     - Customer ID (foreign key)
--     - Account Type (Savings, Current, etc.)
--     - Balance
-- 3. *Transactions*
--     - Transaction ID (primary key)
--     - Account ID (foreign key)
--     - Transaction Type (Deposit, Withdrawal, etc.)
--     - Amount
--     - Date
-- 4. *Employees*
--     - Employee ID (primary key)
--     - Name
--     - Role
--     - Branch ID (foreign key)


-- 5. *Branches*
--     - Branch ID (primary key)
--     - Branch Name
--     - Address

-- 6. *Loans*
--     - Loan ID (primary key)
--     - Customer ID (foreign key)
--     - Loan Amount
--     - Interest Rate
--     - Repayment Term

-- 7. *Credit Cards*
--     - Credit Card ID (primary key)
--     - Customer ID (foreign key)
--     - Card Type
--     - Limit
--     - Expiry Date

-- *Relationships:*
-- - A customer can have multiple accounts (one-to-many).
-- - An account is owned by one customer (many-to-one).
-- - An account can have multiple transactions (one-to-many).
-- - A transaction belongs to one account (many-to-one).
-- - An employee works at one branch (many-to-one).
-- - A branch can have multiple employees (one-to-many).
-- - A customer can have multiple loans and credit cards (one-to-many).









-- Project 6  (for boys )
--  INDIAN PREMIUM LEAGUE 
-- Create Table Questions (Write Structure + Keys + Datatypes)
-- Create a table TEAM to store IPL team details with:
-- team_id (Primary Key)
-- team_name
-- home_city

-- Create a table COACH to store coach details with:
-- coach_id (Primary Key)
-- coach_name
-- experience_years
-- team_id (Foreign Key referencing TEAM table)

-- Create a table PLAYER to store players with:
-- player_id (Primary Key)
-- player_name
-- role (Batsman / Bowler / All-Rounder / Wicket-Keeper)
-- price_crore
-- team_id (Foreign Key referencing TEAM table)

-- Create a table VENUE to store stadium information with:
-- venue_id (Primary Key)
-- stadium_name
-- city
-- capacity

-- Create a table MATCH to store match schedule with:
-- match_id (Primary Key)
-- match_date
-- venue_id (Foreign Key referencing VENUE table)
-- team1_id (Foreign Key referencing TEAM table)
-- team2_id (Foreign Key referencing TEAM table)

-- Create a table PERFORMANCE to store players match performance with:
-- performance_id (Primary Key)
-- match_id (Foreign Key referencing MATCH table)
-- player_id (Foreign Key referencing PLAYER table)
-- runs_scored
-- wickets_taken
-- catches

-- Relationship Summary
-- TEAM → COACH	1 to 1
-- TEAM → PLAYER	1 to M 
-- VENUE → MATCH	1 to M
-- TEAM → MATCH	M to M
-- MATCH → PERFORMANCE	1 to M
-- PLAYER → PERFORMANCE 1 to M	



-- Project 7 ( for girls+ boys )
-- College Fest Event Participation System

-- Create the following tables with suitable data types.
-- Use Primary Keys and Foreign Keys wherever required.

-- Department table 
-- Dept_ID
-- Dept_Name


-- Organizer table 
-- Organizer_ID
-- Organizer_Name
-- Role (Faculty / Student Coordinator)


-- Venue table 
-- Venue_ID
-- Venue_Name
-- Capacity

-- Student table 
-- Student_ID
-- Student_Name
-- Gender
-- Mobile
-- Dept_ID (should refer Dept_ID in Department table)

-- Event table 
-- Event_ID
-- Event_Name
-- Event_Date
-- Organizer_ID (should refer Organizer_ID in Organizer table)
-- Venue_ID (should refer Venue_ID in Venue table)

-- Participation table 
-- Participation_ID
-- Student_ID (should refer Student_ID in Student table)
-- Event_ID (should refer Event_ID in Event table)
-- Position (Winner / Runner / Participant)


-- RELATIONSHIP DETAILS (Wri
-- Department → Student One-to-Many	
-- Organizer → Event One-to-Many
-- Venue → Event  One-to-Many
-- Student → Participation One-to-Many 
-- Event → Participation	One-to-Many	


-- Project 8(12 Tables )
-- ZOMATO DATABASE PROJECT

-- Create a table named RESTAURANT
-- To store restaurant details.
-- Columns:
-- RESTAURANT_ID
-- NAME
-- PHONE
-- EMAIL
-- CITY
-- AREA
-- RATING
-- CREATED_DATE

-- Create a table named CATEGORY
-- To store food categories like "Chinese", "Indian", etc.
-- Columns:
-- CATEGORY_ID
-- CATEGORY_NAME
-- DESCRIPTION

-- Create a table named RESTAURANT_CATEGORY

-- To store which restaurant serves which category (many-to-many relation).
-- Columns:
-- RESTAURANT_ID
-- CATEGORY_ID

-- Create a table named MENU

-- To store each restaurant’s menu information.
-- Columns:
-- MENU_ID
-- RESTAURANT_ID
-- MENU_NAME
-- CREATED_DATE

-- Create a table named MENU_ITEM
-- To store food items under each menu.
-- Columns:
-- ITEM_ID – Primary Key
-- MENU_ID – Foreign Key references MENU
-- ITEM_NAME – Not Null
-- PRICE – Check (PRICE > 0)
-- AVAILABLE_STATUS – Default ‘YES’, Check (Available_Status IN ('YES', 'NO'))

-- Create a table named CUSTOMER
-- To store customer details.
-- Columns:
-- CUSTOMER_ID – Primary Key
-- FULL_NAME – Not Null
-- PHONE – Unique
-- EMAIL – Unique
-- GENDER – Check (Gender IN ('M','F','O'))
-- REGISTRATION_DATE – Default SYSDATE

-- Create a table named ADDRESS
-- To store multiple addresses for each customer.
-- Columns:
-- ADDRESS_ID – Primary Key
-- CUSTOMER_ID – Foreign Key references CUSTOMER
-- HOUSE_NO
-- STREET
-- CITY
-- PINCODE
-- ADDRESS_TYPE – Check (Address_Type IN ('HOME','OFFICE','OTHER’))

-- Create a table named DELIVERY_PERSON
-- To store details of delivery boys.
-- Columns:
-- DELIVERY_ID – Primary Key
-- NAME – Not Null
-- PHONE – Unique
-- VEHICLE_NO
-- STATUS – Default ‘AVAILABLE’, Check (STATUS IN ('AVAILABLE','BUSY'))


-- Create a table named ORDERS
-- To store customer order details.Columns:
-- ORDER_ID – Primary Key
-- CUSTOMER_ID – Foreign Key references CUSTOMER
-- RESTAURANT_ID – Foreign Key references RESTAURANT
-- DELIVERY_ID – Foreign Key references DELIVERY_PERSON
-- ORDER_DATE – Default SYSDATE
-- TOTAL_AMOUNT – Check (TOTAL_AMOUNT >= 0)
-- ORDER_STATUS – Default ‘PLACED’, Check (Order_Status IN ('PLACED','ONWAY','DELIVERED','CANCELLED'))


-- Create a table named ORDER_ITEM
-- To store all items under each order.
-- Columns:
-- ORDER_ID – Foreign Key references ORDERS
-- ITEM_ID – Foreign Key references MENU_ITEM
-- QUANTITY – Check (QUANTITY > 0)
-- PRICE – Check (PRICE > 0)
-- Combination of ORDER_ID and ITEM_ID – Primary Key


-- Create a table named PAYMENT
-- To store payment details for each order.Columns:
-- PAYMENT_ID – Primary Key
-- ORDER_ID – Foreign Key references ORDERS
-- PAYMENT_MODE – Check (Payment_Mode IN ('CARD','CASH','UPI'))
-- PAYMENT_DATE – Default SYSDATE
-- AMOUNT – Check (AMOUNT >= 0)
-- PAYMENT_STATUS – Default ‘PENDING’, Check (Payment_Status IN ('SUCCESS','FAILED','PENDING'))



-- Create a table named REVIEW
-- To store customer reviews for restaurants.
-- Columns:
-- REVIEW_ID – Primary Key
-- CUSTOMER_ID – Foreign Key references CUSTOMER
-- RESTAURANT_ID – Foreign Key references RESTAURANT
-- RATING – Check (Rating BETWEEN 1 AND 5)
-- COMMENTS
-- REVIEW_DATE – Default SYSDATE


-- Relationship 

-- 1)CUSTOMER→ORDERS 1-to-Many
-- 2)RESTAURANT→ORDERS	1-to-Many
-- 3)MENU_CATEGORY→MENU_ITEM 1-to-Many
-- RESTAURANT→MENU_ITEM	1-to-Many
-- ORDERS→ORDER_DETAILS 1-to-Many 
-- MENU_ITEM →ORDER_DETAILS. 1-to-Many
-- ORDERS→PAYMENT  1-to-1
-- DELIVERY_PERSON	→DELIVERY 1-to-Many
-- ORDERS→DELIVERY 1-to-1
-- CUSTOMER→REVIEW 1-to-Many
-- RESTAURANT→REVIEW 1-to-Many
-- COUPON→ORDER_COUPON 1-to-Many



-- Project 9
-- Train Ticket Booking System - SQL


-- 1. TRAIN
-- - TRAIN_ID (PRIMARY KEY)
-- - TRAIN_NAME
-- - SOURCE
-- - DESTINATION
-- - TOTAL_COACHES

-- 2. COACH
-- - COACH_ID (PRIMARY KEY)
-- - TRAIN_ID (FOREIGN KEY → TRAIN.TRAIN_ID)
-- - COACH_TYPE (Sleeper/AC/General)
-- - TOTAL_SEATS

-- 3. PASSENGER
-- - PASSENGER_ID (PRIMARY KEY)
-- - PASSENGER_NAME
-- - GENDER
-- - AGE

-- 4. TICKET
-- - TICKET_ID (PRIMARY KEY)
-- - PASSENGER_ID (FOREIGN KEY → PASSENGER.PASSENGER_ID)
-- - TRAIN_ID (FOREIGN KEY → TRAIN.TRAIN_ID)
-- - BOOKING_DATE
-- - TRAVEL_DATE

-- 5. SEAT_RESERVATION
-- - RES_ID (PRIMARY KEY)
-- - TICKET_ID (FOREIGN KEY → TICKET.TICKET_ID)
-- - COACH_ID (FOREIGN KEY → COACH.COACH_ID)
-- - SEAT_NO
-- - STATUS (Booked/Cancelled)


-- . Relationships
-- - TRAIN → COACH = One-to-Many
-- - TRAIN → TICKET = One-to-Many
-- - PASSENGER → TICKET = One-to-Many
-- - TICKET → SEAT_RESERVATION = One-to-Many
-- - COACH → SEAT_RESERVATION = One-to-Many


--  Indexes
-- CREATE INDEX On  (TRAIN_NAME);
-- CREATE INDEX on (PASSENGER_NAME)
-- CREATE INDEX ON TICKET(TRAVEL_DATE);

	
