--  >>>>>>>>>>>>>BASIC SQL ASSIGNMENT >>>>>>

-- 1) WHAT IS SEQUEL AND EXPLAIN HISTORY OF SEQUEL ?
-- 2) EXPLAIN DATA WITH EXAMPLE
-- 3) WHAT IS DATABASE  AND EXPLAIN IT ?
-- 4) WHAT DOES DBMS AND RDBMS EXPLAIN WITH DIFFERENCES ?
-- 5) EXPLAIN THE RULES OF AN E.F CODD ?
-- 6) WHAT IS DATATYPE AND EXPLAIN ALL THE DATATYPES WITH SYNTAX ?
-- 7) DIFFERENCES BETWEEN CHAR AND VARCHAR ?
-- 8) EXPLAIN CONSTRAINTS WITH SYNTAX FOR EACH CONSTRAINTS ?
-- 9) DIFFERENCES BETWEEN PRIMARY KEY AND FOREIGN KEY 
-- 10) DIFFERENCES BETWEEN UNIQUE AND DISTINCT ?







-- >>>>>>> QUERIES ON PROJECTION >>>>>>>>>>

-- 11) WAQTD EMPLOYEES NAME FROM EMPLOYEES TABLE ?
-- 12) WAQTD SAL AND EMPLOYEES NAME FROM EMPLOYEE TABLE ?
-- 13) WAQTD NAME AND DEPTNO AND JOBS THAT ARE PRESENT IN EMP TABLE ?
-- 14) WAQTD HIREDATE AND DEPTNO FOR ALL THE EMPLOYEES ?
-- 15) WAQTD MGR AND EMPNO FROM EMPLOYEE TABLE ?
-- 16) WAQTD ALL THE DETAILS OF ALL THE EMPLOYEES ?
-- 17) WAQTD DEPARTMENT NAME FROM DEPT TABLE ?
-- 18) WAQTD LOC THAT ARE PRESENT IN DEPT TABLE
-- 19) WAQTD DEPTNO AND LOC PRESENT IIN DEPT TABLE ?
-- 20) WAQTD ALL THE DETAILS OF DEPT TABLE ? 
-- 21) WAQTD DIFFERENT JOBS PRESENT IN EMPLOYEE TABLE ?
-- 22) WAQTD ENAME AND SAL PRESENT IN EMP TABLE BUT THERE 
--     SHOULD NOT BE ANY REPEATED RECORDS ?
-- 23) WAQTD HIREDATE AND SAL OF AN EMPLOYEES BUT
--     THERE SHOULD NOT BE ANY REPEATED RECORDS ?
-- 24) WAQTD JOB SAL AND DEPTNO OF AN EMPLOYEES BUT
--     THERE SHOULD NOT BE ANY REPEATED RECORDS ?
-- 25) WAQTD ALL THE DETAILS OF AN EMPLOYEES BUT 
--     THERE SHOULD NOT BE ANY REPEATED RECORDS ?
-- 26) WAQTD ANNUAL SALARY FOR ALL THE EMPLOYEES ?
-- 27) WAQTD HALF TERM SALARY FOR ALL THE EMPLOYEES ?
-- 28) WAQTD ENAME AND ANNUAL SALARY FOR ALL THE EMPLOYEES ?
-- 29) WAQTD DEPTNO JOB AND SAL WITH 10% HIKE FOR ALL THE EMPLOYEE ?
-- 30) WAQTD ALL THE DETAILS OF AN EMPLOYEES ALONG WITH ANNUAL SALARY ?



-- 31) WAQTDALL THE DETAILS OF AN EMPLOYEES ALONG WITH 
--     10% HIKE IN ANNUAL SALARY FOR ALL THE EMPLOYEE ?
-- 32) WAQTD SAL ANNAUL SALARY HALF_TERM SALARY AND QUERTER TERM SALARY 
--     FOR ALL THE EMPLOYEES ?
-- 33) WAQTD ANNUAL SALARY WITH 20% DEDUCTION  FOR ALL THE EMPLOYEES ?
-- 34) WAQTD ALL THE DETAILS ALONG WITH 100 RS PENALTY FOR ALL THE EMPLOYEES ?
-- 35) WAQTD TOTAL SALARY NEEDED TO PAY FOR EACH AND EVERY EMPLOYEE ?
-- 36) WAQTD ANNAUL SALARY  AND HALF_TERM SALARY WITH ALIAS NAME 
--     FOR ALL THE EMPLOYEES ?
-- 37) WAQTD ALL THE DETAILS OF AN EMPLOYEES ALONG WITH 12% HIKE 
--     IN ANNUAL SALARY WITH ALIAS NAME FOR ALL THE EMPLOYEES 
-- 38) WAQTD JOB AS DESIGNATION HIREDATE AS JOINING DATE MGR AS 
--     REPORTING MANAGER NUMBER FOR ALL THE EMPLOYEES ?
-- 39) WAQTD JOB  WITH DEPTNO FOR ALL THE EMPLOYEES USING ALIAS AS
--     DESIGNATION FOR THE JOB AND DNO FOR THE DEPTNO ?
-- 40) WAQTD ALL THE DETAILS OF AN EMPLOYEES ALONG WITH 
--     50 RS HIKE IN SAL USE ALIAS AS BONUS FOR ALL THE EMPLOYEE ?
   


-- >>>>>>>>>>> QUERIES ON SELECTION >>>>>>>>>>

-- 41 ) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHOSE SALARY 
--       IS MORE THEN 1000 ?
-- 42) WAQTD ENAME AND SALARY FOR THE EMPLOYEES WHOSE DEPTNO IS 20 ?
-- 43) WAQTD JOB AND DEPTNO OF AN EMPLOYEES WHO ARE  WORKING 
--       AS MANAGER ?
-- 44) WAQTD ALL THE DETAILS OF ALL THE EMPLOYEES WHOSE NAME IS KING ?
-- 45) WAQTD NAME AND HIREDATE OF ALL THE EMPLOYEES WHO HIRED
--     ON ‘01-JAN-81 ?
-- 46) WAQTD HIREDATE AND DEPTNO OF AN EMPLOYEES WHO HIRED 
--      AFTER THE 1981 ?
-- 47) WAQTD ALL THE DETAILS OF AN EMPLOYEES WHO HIRED 
--      BEFORE THE 1987 ?
-- 48) WAQTD ALL THE DETAILS ALONG WITH ANNUAL SALARY FOR ALL
--      THE EMPLOYEES WHOSE SAL IS LESS THEN 5000 ?
-- 49) WAQTD ALL THE DETAILS OF AN EMPLOYEES WHOSE  JOB IS MANAGER ?
-- 50) WAQTD ENAME AND JOB AND DEPTNO OF ALL THE EMPLOYEES WHO ARE 
--      WORKING IN DEPTNO 30 ?


-- 51) WAQTD ALL THE DETAILS OF AN EMPLOYEES WHOSE JOB IS NOT SALESMAN ?
-- 52) WAQTD ENAME AND JOB OF ALL THE EMPLOYEES EXCEPT THE
--     EMPLOYEES OF DEPTNO 20 ?
-- 53) WAQTD JOB EPTNO AND SAL OF AN ALL THE EMPLOYEES EXCEPT
--    THE EMPLOYEES WHO ARE WORKING AS SALESMAN ?
-- 54) WAQTD DESIGNATION OF ALL THE EMPLOYEES EXCEPT KING ?
-- 55) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH THAT 
--      20% HIKE OF IN THEIR SALARY FOR THE EMPLOYEES WHO HIRED
--    AFTER 85 ?
-- 56) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH THAT 
--      12% DEDUCTION  OF IN THEIR SALARY FOR THE EMPLOYEES WHO HIRED
--    BEFORE  84 ?
-- 57) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH THAT 
--      2000 BONUS  OF IN THEIR SALARY FOR THE EMPLOYEES WHOSE 
--      EMPNO IS 7369 ?
-- 58) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE NOT WORKING
--      IN  DEPTNO 10 ?
-- 59) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH HALFTERM SALARY 
--      FOR ALL THE EMPLOYEE WHOSE ANNUAL SALARY IS MORE THEN 14000 ?
-- 60) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH THAT 
--      20% HIKE OF IN THEIR  HALF TERM SALARY FOR ALL THE EMPLOYEES
--     WHOSE HALF TERM SALARY IS MORE THAN 7000 ?






-- >>>>>>>>>>> ASSIGNMENT ON LOGICAL OPERATOR >>>>>>>>>>

-- 61) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING IN DEPTNO
--      10 AND 20?
-- 62) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHO ARE WORKING 
--      AS MANAGER AND SALESMAN ?
-- 63) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SAL IS MORE THEN 
--       1000 AND LESS THEN 5000 ?
-- 64) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE DEPTNO IS 20
--      AND WORKING AS MANAGER ?
-- 65) WAQTD ALL THE EMPLOYEE NAME AND SALARY WHO HIRED AFTER 81
--       INTO DEPTNO 10 ?
-- 66) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE NAME IS 
--       KING AND SCOTT ?
-- 67) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SAL IS 
--       3000 AND 5000 ?
-- 68) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHO ARE WORKING IN DEPTNO      
--       10 AS MANAGER AND HIRED ON ‘17-DEC-82 ?
-- 69) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING AS 
--       PRESIDENT IN DEPTNO 10 AND HAVING SALARY OF 5000 ?
-- 70) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WORKING IN DEPTNO 10,20
--       AS MANAGER ?
-- 71) WAQTD ALL THE EMPLOYEES NAME AND JOB FOR  THE EMPLOYEES
--     WHO HIRED AFTER 81 AND BEFORE 87 ?
-- 72) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SALARY ARE MORE THEN   
--      1000 AND LESS THEN 5000 IN DEPTNO 20 ?
-- 73) WAQTD ALL THE DETAILS OF THE OF THE EMPLOYEES WHO ARE WORKING AS        
--      MANAGER IN DEPTNO 20 AND 10AND EARNING COMMISIONS 400,1600 ?
-- 74) WAQTD ENAME AND ANNAUL SALARY WITH ALISAS NAME FOR THE                  
--     E MPLOYEES WHOSE ANNUAL SALARY IS MORE THEN 800 IN DEPTNO 30 WORKING   AS SALESMAN AND HIRED BEFORE THE 88 ?
-- 75) WAQTD ENAME AS A DEPTNO AS B AND JOB AS C FOR THE EMPLOYEES WHOSE COMM IS MORE THE 100 IN DEPTNO 10,20,30 ?
-- 76) WAQTD ALL THE DETAILS FOR THE EMPLOYEEES WHOSE HIREDATE ARE ‘03-DEC-81’ AND ‘17DEC-81’ INTO DEPTNO 30 ?
-- 77) WAQTD JOB AND SALARY FOR THE EMPLOYEES WHOSE COMM IS LESS THEN 2000 AND SALARIES ARE MORE THEN 1000 IN DEPTNO 10, 20?
-- 78) WAQTD ALL THE DEATILS  FOR THE EMPLOYEES WHOSE NAMES ARE KING AND SMITH AND ALLEN ?
-- 79) WAQTD ANNUAL SALARY HALF TERM SALARY WITH 25% DEDUCTION IN THE SALARY FOR THE EMPLOYEES WHOSE ANNUAL SALARY IS MORE THEN 6000 ?
-- 80) ALL THE DETAILS AND HALF TERM SALARY FOR SALESMAN AND MANAGER IN DEPTNO 10,30 ?






-- >>>>>>>>>>> ASSIGNMENT ON SPECIAL OPERATOR >>>>>>>>>>>
-- 81) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING IN DEPTNO
--      10 AND 20?
-- 82) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHO ARE WORKING 
--      AS MANAGER AND SALESMAN ?
-- 83) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SAL IS MORE THEN 
--       1000 AND LESS THEN 5000 ?
-- 84) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE DEPTNO IS 20
--      AND WORKING AS MANAGER ?
-- 85) WAQTD ALL THE EMPLOYEE NAME AND SALARY WHO HIRED AFTER 81
--       INTO DEPTNO 10 ?
-- 86) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE NAME IS 
--       KING AND SCOTT ?
-- 87) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SAL IS 
--       3000 AND 5000 ?
-- 88) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHO ARE WORKING IN DEPTNO      
--       10 AS MANAGER AND HIRED ON ‘17-DEC-82 ?
-- 89) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING AS 
--       PRESIDENT IN DEPTNO 10 AND HAVING SALARY OF 5000 ?
-- 90) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WORKING IN DEPTNO 10,20
--       AS MANAGER ?
-- 91) WAQTD ALL THE EMPLOYEES NAME AND JOB FRO THE EMPLOYEES
--     WHO HIRED AFTER 81 AND BEFORE 87 ?
-- 92) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SALARY ARE MORE    THEN   1000 AND LESS THEN 5000 IN DEPTNO 20 ?
-- 93) WAQTD ALL THE DETAILS OF THE OF THE EMPLOYEES WHO ARE WORKING AS        
--      MANAGER IN DEPTNO 20 AND 10AND EARNING COMMISIONS 400,1600 ?
-- 94) WAQTD ENAME AND ANNAUL SALARY WITH ALISAS NAME FOR THE                    
--   E MPLOYEES WHOSE ANNUAL SALARY IS MORE THEN 800 IN DEPTNO 30 WORKING AS SALESMAN AND HIRED BEFORE THE 88 ?
-- 95) WAQTD ENAME AS A DEPTNO AS B AND JOB AS C FOR THE EMPLOYEES WHOSE COMM IS MORE THE 100 IN DEPTNO 10,20,30 ?
-- 96) WAQTD ALL THE DETAILS FOR THE EMPLOYEEES WHOSE HIREDATE ARE ‘03-DEC-81’ AND ‘17DEC-81’ INTO DEPTNO 30 ?
-- 97) WAQTD JOB AND SALARY FOR THE EMPLOYEES WHOSE COMM IS LESS THEN 2000 AND SALARIES ARE MORE THEN 1000 IN DEPTNO 10, 20?
-- 98) WAQTD ENAME FOR THE EMPLOYEES WHOSE NAMES ARE KING AND SMITH AND ALLEN ?
-- 99) WAQTD ANNUAL SALARY HALF TERM SALARY WITH 25% DEDUCTION IN THE SALARY FOR THE EMPLOYEES WHOSE ANNUAL SALARY IS MORE THEN 6000 ?
-- 100) ALL THE DETAILS AND HALF TERM SALARY FOR SALESMAN AND MANAGER IN DEPTNO 10,30 ?
-- 101) ) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHOSE HIRED BETWEEN 81 TO 89  INTO DEPTNO 20 ?
-- 102) WAQTD DETAILS FOR THE EMPLOYEES WHOSE SALARY IN THE RANGE OF 1000 TO 5000 IN DEPTNO 10,20 ?
-- 103) WAQTD ENAME AND JOB FOR THE EMPLOYEES WHO ARE WORKING AS ANAGER AND EARNING COMMISION IN THE RANGE OF 100 TO 1000 ?
-- 104) WAQTD ALL THE DEATILS ALONG WITH 3 MONTHS SALARY FOR THE EMPLOYEES WHOSE SALARY IS NOT NULL AND DOESNT HAVING ANY REPORTING 
-- MANAGER  ?
-- 105) WAQTD ENAME AND SALARY AND JIB FOR THE EMPLOYEES WORKING AS SALESMAN IN DEPTNO 30 AND EARNING SALARY BUT NOT COMMISION AND HIRED BETWEEN 82  TO 88 ? 
-- 106) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHO ARE EARNING SALARY ?
-- 107) WAQTD ANNAUL SALARY OF THE EMPLOYEE WHO ARE NOT EARNING COMMISSION ?
-- 108) WAQTD ALL THE DETAILS WITH ANNAUL COMMISSION FOR THE EMPLOYEE WHO  ARE WORKING IN DEPT 10 AND DONT HAVE ANY REPORTING MANAGER ?
-- 109) WAQTD ALL THE DETAILS OF THE EMPLOYEE EXCEPT DEPTNO 10 AND WHO WHO HAVE REPORTING MAMAGER ?
-- 110) WAQTD ENAME AND SALARY. AND COMMISSION OF THE EMPLOYEE WHO EARNING COMMISSION IN DEPT NO 30 AND WORKING AS SALESMAN ?
-- 111) WAQTD ENAME OF THE EMPLOYEE WHOSE NAME START WITH S ?
-- 112 ) WAQTD ALL THE DETAILS FOR THE EMPLOYEE WHOSE NAME 
-- ENDS WITH R ?
-- 113 ) WAQTD SALARY AND DEEPTNO AND NAME FOR THE EMPLOYEE 
-- WHOSE NAME HAVING A CHARACTER ?
-- 114 ) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE HAVING 
-- 2 A IN THEIR NAME ?
-- 115 ) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME HAVING 
-- CONJUGATIVE A IN THEIR NAMES ?
-- 116) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME HAVING 
-- 2ND CHARACTER AS M ?
-- 117) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME HAVING LAST 2ND CHAPTER AS E ?
-- 118) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME START WITH 
-- M HAVING 4TH CHARACTER L AND ENDS WITH R ?
-- 119) WAQTD ALL THE DETAILS OF AN ALL THE EMPLOYEE WHO ARE 
-- EARNING 4 DOGIT OF SALARY AND NAMES STARTS WITH VOWELS ?
-- 120 ) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME 
-- STARTS WITH CONSONANTS. ?
-- 121) WAQTD ENAME AND HIREDATE OF ALL THE EMPLOYEE WHO
-- HIRED IN THE MONTH OF DEC ?
-- 122) WAQTD ALL THE DETAILS FOR THE EMPLOYEE WHO HIRED 
-- DURING 1981 ?
-- 123) WAQTD ALL THE DETAILS OF THE EMPLOYEE EXCEPT 
-- WHOSE NAME HAVING A ?
-- 124) WAQTD SALARY AND NAMES FOR THE EMPLOYEE WHOSE
-- NAME START WITH S EXCEPT THE EMPLOYEE
-- WHOSE SALARY. STARTS WITH 1 ?
-- 125) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE 
-- NAME HAVING 2 TIME CONSUGATIVE. A ?
-- 126) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME START 
-- WITH % ?
-- 127) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME ENDS 
-- WITH % ?
-- 128) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME START 
-- WITH % ENDS WITH _ ?
-- 129) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME HAVING % ?
-- 130) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME START 
-- WITH % HAVING 4TH CHARACTER _ AND ENDS WITH % ?







-- >>>>>>>>>>>>>>ASSINGMENT ON MRF >>>>>>>>>>>>>>>>>>

-- 131) WAQTD MAX SALARY FROM THE EMPLOYEE TABLE ?
-- 132) WAQTD MAX AND MIN COMM FROM EMPLOYEES TABLE ?
-- 133) WAQTD TOTAL SALARY NEEDED TO PAY FOR THE SALESMAN ?
-- 134) WAQTD NUMBER OF EMPLOYEES WORKING IN DEPTNO 30 ?
-- 135) WAQTD NUMBER OF EMPLOYEES WORKING AS MANAGER IN DEPTNO 20?
-- 136) WAQTD MAX SALARY NEEDED TO PAY FOR THE EMPLOYEES WHOSE NAME STARTS WITH A ?
-- 137) WAQTD AVG SALARY NEEDED TO PAY FOR THE EMPLOYEES OF DEPTNO 10 ?
-- 138) WAQTD TOTAL SALARY AND AVG SALARY NEEDED TO PAY FOR THE EMPLOYEES WHO ARE HIRED IN THE RANGE OF 81 TO 87 ?
-- 139) WAQTD NUMBER OF EMPLOYEES WORKING IN DEPTNO 40 ?
-- 140) WAQTD TOTAL SALARY NEEDED TO PAY FOR THE EMPLOYEES WHO ARE REPORTING TO 7839 ?
-- 141) WAQTD HOW MANY EMPLOYEES ARE WORKIN AS PRESIDENT IN DEPTNO 10 AND EARNING SALARY MORE THEN 4000 ?
-- 142) WAQTD HOW MANY EMPLOYEES ARE WORKIN AS SALESMAN IN DEPTNO 30 AND EARNING SALARY LESS THEN 5000 ?
-- 143) WAQTD HOW MANAY EMPLOYEES ARE HIRED ON 03-DEC- 81 iN DEPTNO 10 , 20
-- 144) WAQTD HOW MUCH TOTAL SALARY NEEDE TO PAY FOR THE EMPLOYEE
-- WHOSE MAME HAVING A CHARACTER ?
-- 145) WAQTD AVG SALARY NEEDED TO PAY FOR THE SALESMAN IN DEPTNO 30 ?



 




-- >>>>>>>>> ASSIGNMENT ON GROUP BY CLAUSE >>>>>>>>>>>>>

-- 146).WAQTD NUMBER OF EMPLOYEES WORKING IN EACH DEPARTEMENT EXCEPT PRESIDENT. ?
-- 147)WAQTD TOTAL SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH JOB. ?
-- 148)WAQTD NUMBER OF EMPLOYEEES WORKING AS MANAGER IN EACH DEPARTMENT. ?

-- 149).WAQTD AVG SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH DEPARTMENT EXCLUDING THE EMPLOYEES OF DEPTNO 20 . ? 
-- 150).WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER 'A' IN THEIR NAMES IN EACH JOB.  ?
-- 151).WAQTD NUMBER OF EMPLOYEES AND AVG SALARY NEEDED TO PAY THE EMPLOYEES WHO SALARY IN GREATER THAN 2000 IN EACH DEPT. ?
-- 152)WAQT D TOTAL SALARY NEEDED TO PAY AND NUMBER OF SALESMANS IN EACH DEPT. ?
-- 153)WAQTD NUMBER OF EMPLOYEES WITH THEIR MAXIMUM SALARIES IN EACH JOB. ?
-- 154) WAQTD MAXIMUM SALARIES GIVEN TO AN EMPLOYEE 
-- WORKING IN EACH DEPT. ?
-- 155)WAQTD NUMBER OF TIMES THE SALARIES PRESENT IN EMPLOYEE TABLE. ?














-- <<<<<<<<<<<ASSIGNMENT QUESTIONS ON HAVING CLAUSE>>>>>>>>>>>>

-- 156).WAQTD DNO AND NUMBER OF EMP WORKING IN EACH DEPT IF THERE ARE ATLEAST 2 CLERKS IN EACH DEPT ?

-- 157)WAQTD DNO AND TOTAL SAALARY NEEDED TO PAY ALL EMP IN EACH DEPT IF THERE ARE ATLEAST 4 EMP IN EACH DEPT ?

-- 158).WAQTD NUMBER OF EMP EARNING SAL MORE THAN 1200 IN EACH JOB AND THE TOTAL SAL NEEDED TO PAY EMP OF EACH JOB MUST EXCEEDS 3800 ?

-- 159).WAQTD DEPTNO AND NUMBER OF EMP WORKING ONLY IF THERE ARE 2 EMP WORKING IN EACH DEPT AS MANAGER. ?

-- 160) WAQTD JOB AND MAX SAL OF EMP IN EACH JOB IF THE MAX SAL EXCEEDS 2600 ?

-- 161). WAQTD THE SALARIES WHICH ARE REPEATED IN EMP TABLE ?

-- 162).WAQTD THE HIREDATE WHICH ARE DUPLICATED IN EMP TABLE ?

-- 164) WAQTD AVG SALARY OF EACH DEPT IF AVG SAL IS LESS THAN 3000 ?

-- 164) WAQTD DEPTNO IF THERE ARE ATLEAST 3 EMP IN EACH DEPT WHOS NAME HAS CHAR 'A' OR 'S' ?

-- 165).WAQTD MIN AND MAX SALARIES OF EACH JOB IF MIN SAL IS MORE THAN 1000 AND MAX SAL IS LESS THAN 5000.




-- <<<<<<<<<ASSIGNMENT ON SUB QUERIES>>>> >>>>
-- ASSIGNMENT ON CASE 1


-- 166).WAQTD NAME OF THE EMPLOYEES EARNING MORE THAN ADAMS ?

-- 167).WAQTD NAME AND SALARY OF THE EMPLOYEES EARNING LESS THAN KING

-- 168) WAQTD NAME AND DEPTNO OF THE EMPLOYEES IF THEY ARE WORKING IN THE SAME DEPT AS JONES

-- 169) WAQTD NAME AND JOB OF ALL THE EMPLOYEES WORKING IN THE SAME DESIGNATION AS JAMES 

-- 170)WAQTD EMPNO AND ENAME ALONG WITH ANNUAL SALARY OF ALL THE EMPLOYEES IF THEIR ANNUAL SALARY IS
-- GREATER THAN WARDS ANNUAL SALARY.

-- 171) .WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY
-- ARE HIRED BEFORE SCOTT AND HIRED AFTER THE PRESIDENT ?

-- 172) .WAQTD NAME AND SAL OF THE EMPLOYEE IF THEY ARE EARNING SAL LESS THAN THE EMPLOYEE WHOS EMPNO IS 7839

-- 173).WAQTD ALL THE DETAILS OF THE EMPLOYEES IF THE EMPLOYEES ARE HIRED BEFORE MILLER 

-- 174) .WAQTD ENAME AND EMPNO OF THE EMPLOYEES IF EMPLOYEES ARE EARNING MORE THAN ALLEN

-- 175).WAQTD ENAME AND SALARY OF ALL THE EMPLOYEES WHO ARE EARNING MORE THAN MILLER BUT LESS THAN ALLEN.

-- 178).WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING IN DEPT 20 AND WORKING IN THE SAME DESIGNATION AS SMITH 

-- 179).WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE SAME DEPT AS TURNER

-- 180).WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AFTER 1980 AND BEFORE KING 

-- 181).WAQTD ALL THE DETAILS OF EMPLOYEES WHO EARN MORE THAN SCOTT BUT LESS THAN KING

-- 182).WAQTD NAME OF THE EMPLOYEES WHOS NAME STARTS WITH 'A' AND WORKS IN THE SAME DEPT AS BLAKE 

-- 183).WAQTD NAME AND COMM IF EMPLOYEES EARN COMMISSION
-- AND WORK IN THE SAME DESIGNATION AS SMITH

-- 184).WAQTD DETAILS OF ALL THE EMPLOYEES WORKING AS CLERK IN THE SAME DEPT AS TURNER.

-- 185).WAQTD ENAME, SAL AND DESIGNATION OF THE EMPLOYEES WHOS ANNUAL SALARY IS MORE THAN SMITH AND LESS THAN KING.










-- ASSIGNMENT ON CASE 2:

-- 186).WAQTD DNAME OF THE EMPLOYEES WHOS NAME IS SMITH 

-- 187).WAQTD DNAME AND LOC OF THE EMPLOYEE WHOS
-- ENAME IS KING 

-- 188).WAQTD LOC OF THE EMP WHOS EMPLOYEE NUMBER IS
-- 7902

--  189) WAQTD DNAME AND LOC ALONG WITH DEPTNO OF THE EMPLOYEE WHOS NAME ENDS WITH 'R'.

-- 190) .WAQTD DNAME OF THE EMPLOYEE WHOS DESIGNATION IS PRESIDENT

-- 191) .WAQTD NAMES OF THE EMPLOYEES WORKING IN
-- ACCOUNTING DEPARTMENT


--  192) .WAQTD ENAME AND SALARIES OF THE EMPLOYEES WHO ARE WORKING IN THE LOCATION CHICAGO

-- 193). WAQTD DETAILS OF THE EMPLOYEES WORKING IN SALES 

-- 194) .WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL
-- SALARY IF EMPLOYEES ARE WORKING IN NEW YORK

--  195) .WAQTD NAMES OF EMPLOYEES WORKING IN OPERATIONS DEPARTMENT




















-- ASSIGNMENT ON CASE 1 & 2

-- 195) .WAQTD NAMES OF THE EMPLOYEES EARNING MORE THAN SCOTT IN ACCOUNTING DEPT

-- 196). WAQTD DETAILS OF THE EMPLOYEES WORKING AS
-- MANAGER IN THE LOCATION CHICAGO 

-- 197) .WAQTD NAME AND SAL OF THE EMPLOYEES EARNING MORE THAN KING IN THE DEPT ACCOUNTING

-- 198) .WAQTD DETAILS OF THE EMPLOYEES WORKING AS
-- SALESMAN IN THE DEPARTEMENT SALES 

-- 199) .WAQTD NAME, SAL. JOB, HIREDATE OF THE EMPLOYEES WORKING IN OPERATIONS DEPARTMENT AND HIRED BEFORE KING

-- 200) .DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMET NAMES ENDING 'S'.

-- 201) .WAQTD DNAME OF THE EMPLOYEES WHOS NAMES HAS CHARACTER 'A' IN IT.

-- 202) . WAQTD DNAME AND LOC OF THE EMPLOYEES WHOS
-- SALARY IS RUPEES 800. 

-- 203) .WAQTD DNAME OF THE EMPLOYEES WHO EARN COMISSION

-- 204) .WAQTD LOC OF THE EMPLOYEES IF THEY EARN COMISSION IN DEPT 40




-- ASSIGNMENT ON TYPES OF SUB QUERY.

-- 205) .WAQTD NAME OF THE EMPLOYEES EARNING SALARY MORE THAN THE SALESMAN

-- 206) WAQTD DETAILS OF THE EMPLOYEES HIRED AFTER ALL THE CLERKS

--  208) WAQTD NAME AND HIREDATE OF EMPLOYEES HIRED BEFORE ALL THE MANAGERS

-- 209) .WAQTD NAMES OF THE EMPLOYEES HIRED AFTER ALL THE MANAGERS AND EARNING SALARY MORE THAN ALL THE CLERKS

-- 210) .WAQTD DETAILS OF THE EMPLOYEES WORKING AS CLERK AND HIRED BEFORE ATLEST A SALESMAN 

--  211).WAQTD DETAILS OF EMPLOYEES WORKING IN ACCOUNTING OR SALES DEPT

-- 212) WAQTD DEPARTMENT NAMES OF THE EMPOYEES WITH NAME SMITH, KING AND MILLER

-- 213) .WAQTD DETAILS OF EMPLOYEES WORKING NEWYORK OR CHICAGO

-- 214)  WAQTD EMP NAMES IF EMPLOYEES ARE HIRED AFTER ALL THE EMPLOYEES OF DEPT 10



-- ASSIGNMENT ON NESTED SUB QUERY:

-- 61. WAQTD 2ND MINIMUM SALARY

-- 62. WAQTD 5TH MAXIMUM SALARY

-- 63. WAQTD NAME OF THE EMPLOYEE EARNING 3RD MAXIMUM SALARY

-- 64.WAQTD EMPNO OF THE EMPLOYEE EARNING 2D MAXIMUM SALARY

-- 65. WAQTD DEPARTMENT NAME OF AN EMPLOYEE GETTING 4TH MAX SAL

-- 66. WAQTD DETAILS OF THE EMPLOYEE WHO WAS HIRED 2nd 67.WAQTD NAME OF THE EMPLOYEE HIRED BEFORE THE LAST EMPLOYEE

PROMPT 68  LOC OF THE EMPLOYEE WHO WAS HIRED FIRST
SELECT LOC FROM DEPT WHERE DNO = (SELECT DNO FROM EMP WHERE HIREDATE = (SELECT MIN(HIREDATE) FROM EMP));
PROMPT 69 DETAILS OF THE EMPLOYEE EARNING 7TH MINIMUM SALARY
SELECT * 
FROM EMP 
WHERE SAL = (SELECT MAX(SAL) FROM EMP 
WHERE SAL < (SELECT MAX(SAL) FROM EMP 
WHERE SAL < (SELECT MAX(SAL) FROM EMP 
WHERE SAL < (SELECT MAX(SAL) FROM EMP 
WHERE SAL < (SELECT MAX(SAL) FROM EMP 
WHERE SAL < (SELECT MAX(SAL) FROM EMP 
WHERE SAL < (SELECT MAX(SAL) FROM EMP 
WHERE SAL < (SELECT MAX(SAL) FROM EMP)))))))); 
PROMPT 70 DNAME OF EMPLOYEE GETTING 2ND MAXIMUM SALARY
SELECT DNAME
FROM DEPT 
WHERE DNO = (SELECT DNO FROM EMP 
WHERE SAL = (SELECT MAX(SAL) FROM EMP 
WHERE SAL < (SELECT MAX(SAL) FROM EMP )));

-- ASSIGNMENT ON EMP AND MANAGER RELATION .

PROMPT 71 SMITHS REPORTING MANAGER'S NAME';
SELECT ENAME FROM EMP WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME = 'SMITH');

PROMPT 72 ADAMS MANAGER'S MANAGER NAME';
SELECT ENAME FROM EMP WHERE EMPNO = (SELECT MGR FROM EMP WHERE EMPNO = (SELECT MGR FROM EMP WEHRE ENAME = 'ADAMS'));

PROMPT 73 DNAME OF JONES MANAGER
SELECT DNAME FROM DEPT WHERE DNO = (SELECT DNO FROM EMP WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME = 'JONES'));
PROMPT 74 MILLER'S MANAGER'S SALARY
SELECT SAL FROM EMP WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME = 'MILLER');

PROMPT 75 LOC OF SMITH'S MANAGER'S MANAGER.
SELECT LOC FROM DEPT WHERE DNO = (SELECT DNO FROM EMP WHERE EMPNO = (SELECT MGR FROM EMP WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME = 'SMITH')));

PROMPT 76 DNAME OF THE EMPLOYEES REPORTING TO BLAKE;
SELECT DNAME FROM DEPT WHERE DNO IN (SELECT DNO FROM EMP WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'BLAKE'));

PROMPT 77 NUMBER OF EMPLPOYEES REPORTING TO KING
SELECT COUNT(*) FROM EMP WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'KING');
PROMPT  78 DETAILS OF THE EMPLOYEES REPORTING TO JONES
SELECT * FROM EMP WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'JONES');
PROMPT 79 ENAMES OF THE EMPLOYEES REPORTING TO BLAKE'S MANAGER'
SELECT ENAME FROM EMP WHERE MGR = (SELECT MGR FROM EMP WHERE EN);
PROMPT 80) NUMBER OF EMPLOYEES REPORTING TO FORD'S MANAGER'
SELECT COUNT(*) FROM EMP WHERE MGR = (SELECT MGR FROM EMP WHERE ENAME = 'FORD');
-- <<<<THEORY QUESTIONS ON JOINS >>>>>>

-- 121) WHAT IS JOINS LIST ALL THE TYPES OF JOINS ?
-- 122) WHAT IS CROSS JOIN EXPLAIN WITH SYNTAX ?
-- 123) WHAT IS INNER JOIN EXPLAIN WITH SYNTAX ?
-- 124) DIFFERENCES BETWEEN CROSS JOIN AND INNER JOIN ?
-- 125) EXPLAIN THE ADVANTAGES AND DISADVANTAGES OF INNER JOIN ?
-- 126) EXPLAIN THE NATURAL JOIN WITH SYNTAX ?
-- 127) WHAT IS OUTER JOIN EXPLAIN ALL OUTER JOIN WITH SYNTAX ?
-- 129) DIFFERENCES BETWEEN LOJ AND ROJ ?
-- 129) WHAT IS SELF JOIN EXPLAIN WITH SYNTAX ?
-- 130) WHAT IS THE USE USING SELF JOIN COMPARE TO SUB QUERY ? 



--    ASSIGNMENT ON INNER JOINS  OR NATURAL JOIN 

-- 131) WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES ?
-- 132) WAQTD DNAME AND SAL FOR THE EMPLOYEES WHO ARE
--     WORKING AS MANAGER ?
-- 133) WAQTD SAL AND HIREDATE AND LOC FOR THE EMPLOYEES 
--     WHOSE NAME HAVING A CHARACTER IN THEIR NAME  ?
-- 134) WAQTD ALL THE DETAILS OF AN EMPLOYEE ALONG WITH LOC FOR 
--     AN EMPLOYEES  WHOSE SAL IS MORE THEN 2000 IN ACCOUNTING DEPARTMENT ?
-- 135) WAQTD DNAME AND SAL AND DEPTNO OF AN EMPLOYEES 
--     WHOSE JOB IS PRESIDENT  IN DEPTNO 10 ?
-- 136) WAQTD ENAME AND DEPTNO AND LOC FOR ALL THE EMPLOYEES  
--     WHOSE NAME ENDS  WITH VOWELS ?
-- 137) WAQTD HIREDATE AND DEPTNO FOR ALL THE EMPLOYEES WHO 
--      ARE WORKING IN  NEW YORK AND HAVING COMM ?
-- 138) WAQTD EMPLOYEE NAME AND DEPARTMENT NAME FOR ALL
--     THE EMPLOYEE WHO  ARE HIRED IN THE MONTH OF FEB
--       INTO ACCOUNTING  DEPARTMENT ?
-- 139) WAQTD LOC AND EMPNO AND MGR NO FOR ALL THE EMPLOYEES 
--      WHOSE SAL LESS THEN 5000 IN BOSTON HIRED IN THE YEAR OF 87 ?
-- 140) WAQTD DNAME AND LOC ALONG WITH 10% HIKE IN THE 
--     SALARY OF AN EMPLOYEE   WHO ARE REPORTING TO ALLEN ?
-- 141) WAQTD ANNAUL SALARY AND LOC OF AN EMPLOYEE 
--      WHOSE MANAGER NAME IS KING ?
-- 142) WAQTD ALL TEH DETAILS OF AN EMPLOYEES AND THEIR DNAME AND  LOC  FOR                               
--       THE EMPLOYEE WHOSE COMM IS NULL IN DEPTNO 10,20  ?
-- 143) WAQTD DNAME AND ENAME FOR THE EMPLOYEE WHOSE SALARY ENDS 
--      WITH 50  IN DEPTNO 10,20,30 AND WORKING IN RESEARCH DEPARTMENT ?
-- 144) WAQTD LOC DNAME  AND ENAME OF AN EMPLOYEES WHO 
--       ARE HIRED BEFORE THE LAST TWO EMPLOYEES ?

-- 145) WAQTD DNAME AND SALARY OF AN EMPLOYEE WHOSE 
--      NAME ENDS WITH CONSONANTS ?
-- 146) WAQTD MGR SAL AND DEPTNO AND LOC OF AN EMPLOYEES WHOSE LOC ENDS WITH S ?
-- 147) WAQTD EMPNO AND LOC FOR THE EMPLOYEES WHOSE HIREDATE IS '01-JAN-81' IN DALLAS ?
-- 148) WAQTD ENAME AND LOC AND SAL OF AN EMPLOYES WHOSE EMPNO ARE 7369,7488 ?
-- 149) WAQTD ENAME AND LOC FOR THE EMPLOYEES WHOSE SAL IS LESS THEN KING 
--     AND MORE THEN SMITH IN DEPTNO 30 AND WORKING IN SALES DEPARTMENT ?
-- 150) WAQTD COMM AND LOC FOR THE EMPLOYEES WHOSE MGR IS 7902 WORKING IN
--     ACCOUNTING AND RESEARCH DEPARTMENT ?
















-- >>>>>>>> ASSIGNMENT ON  OTHER JOINS>>>>>>>>>>
-- 151) WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES OF THE EMPLOYEES NOT WORKING IN ANY DEPARTMENT ?
-- 152) WAQTDALL THE DETAILS OF AMPLOYEES AND THEIR DEPARTMENT DETAILS IF THE DEPARTMENT IN WHICH NO EMPLOYEES ARE 
-- WORKING ?
-- 153) WAQTD ALL THE DETAILS OF AN EMPLOYEES AND HIER DEPARTMENT DETAILS IF THE EMPLOYEES NOT WORKING IN ANY DEPARTMENT AND THE DEPARTMENT IN WHICH THE NO EMPLOYEES ARE  WORKING ?
-- 154) WAQTD ENAME AND SAL AND DNAME FOR THE EMPLOYEES THOSE WHO ARE NOT WORKING IN ANY DEPARTMENT ?
-- 155) WAQTD HIERDATE AND JOB INCLUDING DNAME AND LOC FOR THE DEPARTMENT IN WHICH NO EMPLOYEES ARE WORKING  ?
-- 156) WAQTD DNAME AND LOC AND JOB FOR THE EMPLOYEES WHO ARE NOT WORKING IN ANY DEPARTMENT AND THE DEPARTMENT NO EMPLOYEES ARE WORKING ?
-- 157) WAQTD EMPLOYEES NAME AND DEPTNAME FOR ALL THE EMPLOYEES 
-- WHOSE SALARIES ARE MORE THEN 2000 ?
-- 158) WAQTDMANAGER NAME AND THE EMPLOYEES SALARY FOR ALL THE EMPLOYEES THOSE WHO ARE WORKING IN DEPTNO 10,20 ?
-- 159) WAQTD MANAGERS MANAGER NAME FOR ALL THE MANAGER WHOSE SALARIES ARE LESS THEN EMPLOYES ?
-- 160) WAQTD EMPLOYEES NAME MANAGER SALARY AND MANAGER MANAGE COMM FOR ALL THE MANAGER WHO HIRED BEFORE THE 87 AS SALESMAN
-- AND EARNING SALARY MORE THEN MANAGERS MANAGER ?
-- 161) WAQTD ENAME AND MANAGER HIREDATE AND JOB FOR ALL THE EMPLOYEES WHO ARE WORKING IN NEW YORK ?
-- 162) WAQTD EMPLOYEES DNAME AND MANAGER LOC INCLUDING EMPLOYEES SALARY AND MANAGER DEPTNO FOR ALL THE EMPLOYEES WHO ARE HIRED BEFORE THE MANAGERS MANAGE ?
-- 163) WAQTD MANAGERS MANAGER NAME FOR ALL THE EMPLOYEES WHO ARE WORKING IN MANAGERS LOCATION AND NOT WORKING IN MANAGES MANAGERS LOCATION ?
-- 164) WAQTD MANAGER NAME FOR THE MANAGERS MANAGER WHO ARE WORKING IN DEPTNO 20 AS ACTUAL MANAGER AND EARNING SALARY MORE THEN THE EMPLOYEES ?
-- 165) WAQTD MANAGERS DNAME AND MANAGERS MANAGER LOC FOR THE EMPLOYEES WHO ARE WORKING IN BOSTON ?
-- 166) WAQTD EMPLOYEES DNAME FOR THE MANAGERS MANAGER WHOSE SAL ARE MORE THAN MANAGER AND LESS THAN EMPLOYEES ?
-- 167) WAQTD EMPLOYEES LOC AND MANAGERS MANAGERS LOC FOR THE MANAGER WHO ARE HIRED BEFORE THE EMPLOYEE AND EARNING SALARY MORE THAN THE EMPLOYEES ?
-- 168) WAQTD MANAGERS MANAGERS MANAGER NAME FOR THE EMPLOYEES WHO ARE WORKING IN MANAGERS MANAGERS MANAGERS LOC AND EARNING SALARY LESS THE MANAGERS HIRED BEFORE MANAGERS MANAGERS MANAGER ?
-- 169) WAQTD DNAME FOR THE EMPLOYEES WHO HIRED BEFORE  THE MANAGERS INTO ACCOUNTING DEPARTMENT IN THE MONTH OF DEC ?
-- 170) WAQTD MANAGERS MANAGERS MANAGERS MANAGER NAME IF THEY ARE HIRED AFTER THE MANAGERS INTO DALLAS ?

-- ADDED QUESTIONS ON OTHER JOINS 
-- WAQTD ENAME ,LOC , AND SAL OF ALL THE EMPLOYEES EVEN IF THEY NOT ASSIGNED TO ANY DEPARTMENT . WORKING AS SALESMAN AND EARNING SALARY MORE THEN 1000 ?
-- WAQTD ENAME ,LOC ,DNAME  AND SAL OF ALL THE DEPARTMENTS EVEN IN THAT THERE IS NO EMPLOYEES ARE WORKING AND LOC BELONGS TO NEW YORK ?
-- WAQTD ENAME ,LOC , AND DNAME ,HIREDATE  SAL OF ALL THE EMPLOYEES EVEN IF THEY NOT ASSIGNED TO ANY DEPARTMENT . WORKING AS SALESMAN AND WHOSE NAME STARTS WITH CONSONANTS  ?
-- WAQTD ALL THE EMPLOYEES DETAILS AND THEIR DEPARTMENT DETAILS EVEN THE EMPLOYEES ARE NOT ASSIGNED TO ANY LOCATION 
-- IF DEPARTMENT NAME HAVING A CHARACTERS 













-- SCENARIO BASED QUESTIONS 
-- ASSUME STD TABLE AND TRAINER TABLE 
-- STD —(  SID , SNAME , DOB , MNO , COURSE ,TID (FK)) CHILD TABLE
-- TRN –(TID(PK),TNAME ,SAL, HQUALIFICATION,BRANCH) PARENT TABLE
-- Q1. WAQTD SNAME , DOB , TNAME ,BRANCH FOR ALL THE STUDENTS EVEN THE STD ARE NOT ASSIGNED TO ANY TRAINERS  ?
-- Q2.WAQTD ALL THE STUDENTS DETAILS AND THEIR TRAINERS DETAILS 
--    FOR ALL TRAINER EVEN THE TRAINER THEY ARE NOT ASSIGNED TO ANY  STUDENTS ?
-- Q3.WAQTD ALL THE TRAINERS AND STUDENTS DETAILS EVEN THE STUDENTS WHO ARE NOT ASSIGNED TO ANY TRAINERS AND ALSO THE TRAINERS WHO ARE NOT ASSIGNED TO ANY STUDENTS ?

-- ASSUME DOCTOR AND PATIENT TABLES 
-- DOCTOR —- (DID ,DNAME , MNO ,SPEC,EXP)  — PARENT TABLE 
-- PATIENT — (PID ,PNAME , DOB , MNO , GMAIL, ADDRESS) — CHILD TABLE 
-- Q1. WAQME , PID DNAME , PNADRESS FOR ALL THE DOCTORS EVEN THE DOCTORS ARE 
-- NOT ASSIGNED TO ANY PATIENT ?
-- Q2. WAQTD ALL THE DOCTORS DETAILS AND PATIENT DETAILS FOR ALL THE PATIENT EVEN THE PATIENT ARE NOT ASSIGNED TO ANY DOCTORS AND THE PATIENT ADDRESS IS PUNE ?
-- Q3. WAQTD ALL THE DOCTORS DETAILS AND PATINETS DETAILS EVEN THE DOCTORS ARE NOT ASSIGNED TO ANY PATIENT AND ALSO THE PATIENTS ARE NOT ASSIGNED TO ANY DOCTORS ?













-- >>>> ASSIGNMENT ON DDL DML TCL DCL >>>>
-- 171) WAQT CREATE ANY ONE TABLE WITHOUT ANY PRIMARY KEY WITH 5 COLUMNS ?
-- 172) WAQT RENAME THE EMP TABLE NAME TO EMPLOYEES  ?
-- 173) WAQT TRUNCATE THE SALGRADE TABLE  ?
-- 174) WAQT DROP THE EMP ANY ONE TABLE FROM DATABASE AND GET IT BACK  ?
-- 175) WAQT PURGE THE ANY ONE TABLE  ?
-- 176) WAQT CREATE TWO TABLES AND MAKE  THE CONNECTION BETWEEN THESE TWO TABLES  ?
-- 177) WAQT ADD THE ONE COLUMN INTO EMPLOYEES TABLE ?
-- 178) WAQT ADD TWO COLUMN INTO DEPT TABLE ?
-- 179) WAQT DROP THE RECENTLY ADDED COLUMN FROM THE EMP TABLE ?
-- 180) WAQT RENAME THE COLUMN FROM EMP AND DEPT TABLE  FOREIGN KEY AS DNO ?

-- 181) WAQT INSERT 5 RECORDS INTO EMP TABLE ?
-- 182) WAQT DELETE THE EMPLOYEES RECORD WHOSE NAME IS KING ?
-- 183) WAQT UPDATE THE SALARY OF SMITH AS 5000 ?
-- 184) WAQT  UPDATE THE JOB OF ALL THE EMPLOYEES AS MANAGER  WHO ARE GETTING SAL <1600 ?
-- 185) WAQT DELETE THE EMPLOYEES RECORD WHO ARE WORKING IN NEW YORK ?
-- 186) WAQT DELETE THE EMPLOYEES RECORDS WHO ARE EARNING SALARY MORE THEN  SMITH AND HIRED BEFORE SCOTT ?
-- 187) WAQT TO UPDATE THE COMM FOR ALL THE EMPLOYEES WHO ARE REPORTING TO KING  AS 1000 ?
-- 188) WAQT UPDATE THE JOB AS BOSS AND SALARY AS 90000 FOR THE EMPLOYEES WHOSE DNAME HAVING EXACTLY ONE A ?
-- 189) WAQT TAKE PERMISSION FROM THE SCOTT AND DELETE THE RECORDS WHOSE SALARY IS 3000  IN HR DATABASE ?
-- 190) WAQT RETAKE THE PERMISSION FROM HR AND TRY TO DELETE THE RECORDS WHOSE SAL IS MORE THEN 2000 ?







-- >>>>> THEORY  STATEMENT  QUESTIONS  >>>>>>
-- 191) WHAT ARE THE  DIFFERENCE BETWEEN DELETE AND TRUNCATE ?
-- 192) DIFFERENCE BETWEEN DELETE DROP AND TRUNCATE ?
-- 193) DIFFERENCE BETWEEN ALTER AND UPDATE ?
-- 194) SYNTAX FOR CREATE TABLE WITH PRIMARY KEY AND FOREIGN KEY ?
-- 195) SYNTAX FOR GRANT AND REVOKE ?
-- 196) SYNTAX FOR DML ?
-- 197) SYNTAX FOR ALL THE STATEMENT OF DDL ?
-- 198) SYNTAX FOR CHECK THE CONSTRAINTS ?
-- 199) SYNTAX FOR TO CHECK THE TABLE LIST FROM RECYCLE BIN ?
-- 20) SYNTAX FOR TO CHECK THE PERMISSION LIST ?
-- 201) SYNTAX FOR TCL STATEMENTS ?
-- 202) SYNTAX FOR SELECTION AND PROJECTION  ?
-- 203) DIFFERENCE BETWEEN PROJECTION AND SELECTION ?
-- 204) DIFFERENCE BETWEEN DDL AND DML ?
-- 205) SYNTAX FOR TO CREATE THE INDEX ?
-- 206) SYNTAX FOR TO CHECK THE STRUCTURE OF TABLE ?
-- 207) SYNTAX FOR TO ADD THE COLUMN INTO TABLE ?
-- 208) SYNTAX FOR TO DROP THE COLUMN FROM THE TABLE ?
-- 209) SYNTAX FOR TO CHANGE THE DATATYPES ?
-- 210) SYNTAX FOR TO CHANGE FROM NULL TO NOT NULL OR VISE VERSA ?















-- SRF QUESTIONS  /  ASSIGNMENT 

-- 211) WAQTD THE NO OF CHARACTERS PRESENT IN YOUR NAME ?
-- 212) WAQTD THE DEATILS OF THE EMPLOYEES WHOSE NAME HAVING 
--    4 CHARACTERS ?
-- 213) WAQTD ENAME AND LOC OF ALL THE EMPLOYEES WHO ARE EARNING 4 DIGIT OF SALARY ?
-- 214) WAQT GET THE REMINDER VALUES OF 10 /5 ?
-- 215) WAQTD THE DEATILS OF EMPLOYEES WHOSE NAME ENDS WITH VOWELS ?
-- 216) WAQTD ALL THE DEATILS OF THE EMPLOYEES WHO AHEV MORE THEN 513 MONTHS 
--    OF EXPERIANCE ?
-- 217) WAQT REPLACE THE 3RD A FROM THE MALAYALAM ?
-- 218) WAQTD THE FIRST HALF NAME OF EMPLOYEES SAME AND 2ND HALF NAME 
--    OF EMPLOYEES IN REVERSE MANNAER ?
-- 219) WAQT REPLACE THE FIRST 6 NUMBER AS (*) FROM 9900199001 ?
-- 220) WSQTD OF THE EMPLOYEES WHOSE NAME HAVING EXACTLY 2 A IN THEIR NAMES ?
-- 221) WAQTD DNAME AND SAL OF ALL THE EMPLOYEES WHOSE NAMES ARE PALYDROM IN NATURE ?
-- 222) WAQTD DNAME AND ENAME OF ALL THE EMPLOYEES WHOSE 2ND HALF NAME PALYDROM IN NATURE ?
-- 223) WAQTD THE TOTAL SALARY NEEDED TO PAY FOR EACH AND EVERY EMPLOYEES ?(NVL)
-- 224) WAQTD THE DETAILS OF THE EMPLOYEES WHO ARE EARNING 3RD MAX SALARY FROM EMP TABLE ?
-- 225) WAQTD THE 2ND MAX SALARY FROM EACH AND EVERY JOB ?
-- 226) WAQTD THE EMPLOYEES NAME AND THEIR DNAME IN INITCAP FORMAT 
--     AND ALSO DISPLAY THEIR JOB IN LOWER CASE FORMAT ?
-- 227) WAQT GET THE NO OF MONTHS BETWEEN YOUR DATE OF BIRTH TO TODAYS DATE ?
-- 228) WAQT GET THE YOUR CURRENT AGE IN YEAR FORMAT UPTO THE DATE ?
-- 229) WAQT CONCAT ENAME WITH THEIR  HALF DNAME OF ALL THE EMPLOYEES ?
-- 230) WAQT GET THE DEATILS OF THE EMPLOYEES IF THEIR NAME HAVING % AS LAST LETTER ?
-- 231) WAQTD THE DETAILS OF AN EMPLOYEES IF THEIR SALARIES ARE PALYDROM IN NATURE ?
-- 232) WAQTD ALL THE EMPLOYEES IF THEIR NAME AND DNAME STARST WITH SAME LETTER ?
-- 233) WAQTD ALL THE EMPLOYEES IF THEIR NAME AND DNAME STARST AND ENDS WITH SAME LETTER ?
-- 234) WAQTD THE LOC AND DNAME AND JOB OF ALL THE EMPLOYEES IF THEIR NAME MIDDLE 
--     LETTERS ARE VOWELS ?
-- 235) WAQT GET EXACTLY THE MIDDLE NAME FROM  "VIRAT ANUSKHA KHOLI" ?
-- 236) WAQT PRINT THE DEATILS IN GIVEN FLOW 
--     "HI SMITH GOOD MORNING YOUR DESIGNATION IS CLERK AND SALARY IS 800 YOUR 
--     DEPTNO IS 20"  SAME FORMAT FOR ALL THE EMPLOYEES  ?
-- 237) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE HIRED ON WENSEDAY ?
-- 238) WAQTD ALL THE DEATILF OF EMPLOYEES AND THEIR DEPARTMENT IF THEY ARE 
--     HIRED IN THE MONTH OF DEC , JAN , FEB ?
-- 239) WAQTD ALL THE EMPLOYEES IF THEY ARE HIRED IN THE YEAR OF 81, 87, 82 ?
-- 240) WAQT GET THE YOUR CURRENT AGE WITH DAY OF BORN ?



--  DIFFERENCES QUESTIONS IN SQL 
-- 241) DIFFERENCES BETWEEN DMBS AND RDBMS ?
-- 242) DIFFERENCES BETWEEN CHAR AND VARCHAR ?
-- 243) DIFFERENCES BETWEEN SQL AND NO SQL ?
-- 244) DIFFERENCES BETWEEN PROJECTION AND SELECTION ?
-- 245) DIFFERENCES BETWEEN WHERE CLAUSE AND HAVING CLAUSE ?
-- 246) DIFFERENCES BETWEEN ALIAS AND DISTINCT ?
-- 247) DIFFERENCES BETWEEN DISTINCT AND UNIQUE ?
-- 248) DIFFERENCES BETWEEN PRIMARY KEY AND FOREIGN KEY ?
-- 249) DIFFERENCES BETWEEN PRIMARY KEY AND UNIQUE ?
-- 250)DIFFERENCES BETWEEN NULL AND NOT NULL ?
-- 251)DIFFERENCES BETWEEN EXPRESSION AND ALIAS ?
-- 252)DIFFERENCES BETWEEN FUNCTIONS AND OPERATORS ?
-- 253)DIFFERENCES BETWEEN USER DEFINED FUNCTION AND BUILT IN FUNCTIONS ?
-- 254)DIFFERENCES BETWEEN SRF AND MRF ?
-- 255)DIFFERENCES BETWEEN SQSR AND MRSQ ?
-- 256)DIFFERENCES BETWEEN SUB QUERY AND JOINS ?
-- 257)DIFFERENCES BETWEEN ALL AND ANY OPERATORS ?
-- 258)DIFFERENCES BETWEEN INNER JOIN TO CARETESIAN JOIN ?
-- 259)DIFFERENCES BETWEEN NATURAL TO INNER JOIN ?
-- 260)DIFFERENCES BETWEEN OUTER JOIN TO INNER JOIN ?
-- 261)DIFFERENCES BETWEEN DELETE AND TRUNCATE ?
-- 262)DIFFERENCES BETWEEN DROP AND DELETE ?
-- 263)DIFFERENCES BETWEEN FLASHBACK AND ROLLBACK ?
-- 264)DIFFERENCES BETWEEN ALTER AND UPDATE ?
-- 265)DIFFERENCES BETWEEN TABLES AND VIEWS ?



-- RULES OF DDL /DML/
-- DDL :
-- 1) CREATE TABLE 
--    RULE 1. THE TABLE NAME /COLUMN_NAME SHOULDN'Y STARTS WITH ANY 
--             NUMBER /SPECIAL CHARACTERS 
--             EX :1EMP / @EMP  ---- IN VALID TABLE_NAME 
--                  EMP1 / EMP@ /E1MP /E@MP ---- VALID TABLE_NAME 
--                  SAME FOR COLUMN_NAME ALSO 
--     RULE 2. THE TABLE_NAME SHOULDN'T REPEATS IN DATABSE 
--     RULE 3. WHILE CREATING TABLE IF WE CREATE PARENT TABLE FIRST AND
--             CHILD TABLE SECOND IT WILL EASY TO CREATE 
     
-- 2) RENAME TABLE 
--     READ THE 1ST RULE OF TABLE_NAME

-- 3) TRUNCATE TABLE 
--    RULE : IF WE ARE TRUNCATING PARENT TABLE ITS NOT POSSIBLE 
--            UNTILL WE REMOVES THE CONNECTION BETWEEN PT AND CT 

-- 4) DROP TABLE 
--     RULE : IF WE WANT TO DROP THE PARENT TABLE WE NEED TO REMEOVE THE CONNECTION THEN WE CAN OTHER TABLE WE CAN DROP EASILY 







-- 5) ALTER : ITS MEANS MODIFICATION OF TABLE 
--      RULE : ALTER COMMAND MOST OF TIME WILL WORKS FOR EMPTY TABLES 
--            EFW COMMANDS IN ALTER WILL WORKS FOR FILLED TABLE 

--     1) ADD COLUMN 
--        RULE : WE CAN ADD COLUMN FOR ANY TABLE IF TABLE IS EMPTY 
--                OR ELSE WE CAN USE NULL CONSTRAINTTO ADD COLUMN 
--               IF WE USE NOT NULL THEN WE CAN ADD COLUMN ONLY EMPTY TABLE 
--      2) DROP COLUMN 
--         THERE IS NO RUELS 
--      3) RENAME COLUMN 
--         COLUMN_NAME RULES WE NEED FOLLOW 
--      4) CHANGE DATATYPE OF COLUMNS 
--         RULE 1 : FOR EMPTY COLUMN WE CAN CHANGE DATATYPES 
--                  IF COLUMN FILLED WITH DATA WE CAN INCREASE THE SIZE OF 
--                  IT BUT WE CANT ABLE CHANGE IT 
--       5) CHANGE NULL TO NOT NULL 
--          RULE1 : FOR PK ITS NOT VALID 
--       6) MAKE PR / FK 
--          RULE FOR PK 1) ONLY ONE PK SHOULD BE PRESENT IN TABLE 
--          RULE FOR FK 1) THE COLUMN SHOULD BE PK IN ANOTHER/ SAME TABLE 
 
--     NOTE FOR ALTER : MOST OF TIME THE ALTER WILL WORK FOR EMPTY                           TABLE   FEW COMMANDS WILL WORK FOR FILLED TABLE












-- DML RULES 
-- 1) INSERT 
--    RULE1 : WE CAN INSERT FOR ANY TABLE BUT WILE INSERTING INTO 
--            CHILD TABLE THE FOREIGN KEY COLUMN VALUE THAT VALUE 
--            SHOULD BE PRESENT IN PARENT TABLE ALSO 

-- 2) DELETE 
--    RULE1 : WE CAN DELETE ANY RECORD FROM THE ANY TABLE BUT 
--            WHILE DELETING RECORDS FROM THE PARENT TABLE WE NEED TO 
--            REMOVE THE CONNECTION ELSE ITS NOT POSSIBLE 

-- 3) UPDATE 
--    RULE1 : WE CAN UPDATE ANY TABLE BUT WHILE UPDATING 
--            THE VALUE OF PARENT TABLE IN THAT THE PK WE
--            NEED TO USE THE VALUES WHICH ARE PRESENT IN CHILD TABLE /NULL  
--            WHERE AS UPDATING THE CHILD TABLE FK VALUE WE NEED 
--            USE THE VALUE WHICH ARE PRESENT IN PARENT TABLE 



















-- Projects 
-- general project in sql 
-- Create a table Customer with the following columns:(parent table)

-- Cid (Primary Key)
-- cname (Customer Name)
-- Mail (Unique Email)
-- Mno (Mobile Number)
-- Dob (Date of Birth)
-- Address (Customer Address)

-- note
-- insert 10 records to customer table make sure 2
-- customers shouldn't associats to any account 

-- Create a table Bank with the following columns:(child table)

-- Bid (Primary Key)
-- Cid (Foreign Key → Customer.Cid, also UNIQUE)
-- Bname (Bank Name)
-- Acno (Unique Account Number)
-- Available_Balance (Decimal Value)

-- note 
-- insert 8 records which matches 8 customer from customer table 
-- Ensure one-to-one relationship between Customer and Bank.











-- Project 2
-- Create table Boys (parent):
-- bid (Primary Key)
-- bname
-- age
-- height
-- type

-- Create table Girls (child):
-- gid (Primary Key)
-- gname
-- age
-- height
-- type
-- bid (Foreign Key → Boys.bid)

-- Insert 6 Boys records.
-- Insert 18 Girls records with these conditions:
-- At least 2 boys should not have any girlfriends.
-- At least 2 girls should not have any boyfriends (their bid should be NULL).
-- Rest should maintain one-to-many (e.g., Boy1 → 4 girls, Boy2 → 3 girls, Boy3 → 5 girls).














-- Project 3 

-- Create a table named Films with the following columns:
-- fid (NUMBER, Primary Key)
-- fname (VARCHAR2(100)) – film name
-- genre (VARCHAR2(50)) – e.g., Action, Comedy
-- release_year (NUMBER(4)) – year of release
-- budget (NUMBER(10)) – film budget

-- Create a table named Actor with the following columns:
-- aid (NUMBER, Primary Key)
-- aname (VARCHAR2(100)) – actor name
-- dob (DATE) – date of birth
-- nationality (VARCHAR2(50))

-- Create a junction table named Film_Actors to represent
-- the many-to-many relationship between Films and Actors.
-- fid references Films(fid)
-- aid references Actors(aid)
-- role_name (VARCHAR2(50)) – character played in the film
-- salary (NUMBER(10)) – actor’s salary for that film



-- note
-- Ensure (fid, aid) is a Composite Primary Key.
-- Insert at least 5 records into the Films table (cover different genres & years).
-- Insert at least 6 records into the Actors table (mix of male/female, different nationalities).
-- insert records into Film_Actors such that:
-- Each film has at least 2 actors.
-- At least 2 actors appear in more than one film.
-- At least 1 actor has a different role_name in different films.
-- No duplicate (fid, aid) combination is allowed.



-- PROJECT4
-- Q1.Create a table BOOK with the following columns:
-- bid (Primary Key, Number)
-- bname (Varchar2(100), Not Null)
-- price (Number with 2 decimals)
-- no_of_pages (Number)
-- published_date (Date)

-- Q2.Create a table AUTHOR with the following columns:
-- aid (Primary Key, Number)
-- aname (Varchar2(100), Not Null)
-- dob (Date)
-- address (Varchar2(200))

-- Q3.Create a junction table BOOK_AUTHOR with columns:
-- bid (Foreign Key references BOOK)
-- aid (Foreign Key references AUTHOR)
-- Make (bid, aid) as a Composite Primary Key.

-- INSERT 7 RECORDS INTO BOOK 
-- INSERT 12 RECORDS INTO AUTHOR 
-- THEN INSERT JUNCTION TABLE THE RECORDS IN 
-- SUCH A WAY THAT MANY TO MANY CONNECTION BETWEEN BOOK TO AUTHOR 
-- 2 RECORDS FROM BOOK TABLE SHOULDN'T CONNECT TO ANY AUTHOR AND 3 AUTHOR 
-- SHOULDN'T CONNECT TO ANY BOOK 


-- 4) Tables:
-- GAME → gid (PK), gname, genre, price
-- PLAYER → pid (PK), pname, level
-- GAME_PLAYER → junction

-- 5) Tables:
-- SONG → sid (PK), sname, duration, album
-- SINGER → sgid (PK), sgname, country
-- SONG_SINGER → junction


-- *Project 5 
-- * Banking System Database

-- *Description:* Design a database to manage customer accounts, transactions, and employee information for a banking system.

-- *Tables:*
-- 1. *Customers*
--     - Customer ID (primary key)
--     - Name
--     - Address
--     - Phone Number
--     - Email
-- 2. *Accounts*
--     - Account ID (primary key)
--     - Customer ID (foreign key)
--     - Account Type (Savings, Current, etc.)
--     - Balance
-- 3. *Transactions*
--     - Transaction ID (primary key)
--     - Account ID (foreign key)
--     - Transaction Type (Deposit, Withdrawal, etc.)
--     - Amount
--     - Date
-- 4. *Employees*
--     - Employee ID (primary key)
--     - Name
--     - Role
--     - Branch ID (foreign key)


-- 5. *Branches*
--     - Branch ID (primary key)
--     - Branch Name
--     - Address

-- 6. *Loans*
--     - Loan ID (primary key)
--     - Customer ID (foreign key)
--     - Loan Amount
--     - Interest Rate
--     - Repayment Term

-- 7. *Credit Cards*
--     - Credit Card ID (primary key)
--     - Customer ID (foreign key)
--     - Card Type
--     - Limit
--     - Expiry Date

-- *Relationships:*
-- - A customer can have multiple accounts (one-to-many).
-- - An account is owned by one customer (many-to-one).
-- - An account can have multiple transactions (one-to-many).
-- - A transaction belongs to one account (many-to-one).
-- - An employee works at one branch (many-to-one).
-- - A branch can have multiple employees (one-to-many).
-- - A customer can have multiple loans and credit cards (one-to-many).









-- Project 6  (for boys )
--  INDIAN PREMIUM LEAGUE 
-- Create Table Questions (Write Structure + Keys + Datatypes)
-- Create a table TEAM to store IPL team details with:
-- team_id (Primary Key)
-- team_name
-- home_city

-- Create a table COACH to store coach details with:
-- coach_id (Primary Key)
-- coach_name
-- experience_years
-- team_id (Foreign Key referencing TEAM table)

-- Create a table PLAYER to store players with:
-- player_id (Primary Key)
-- player_name
-- role (Batsman / Bowler / All-Rounder / Wicket-Keeper)
-- price_crore
-- team_id (Foreign Key referencing TEAM table)

-- Create a table VENUE to store stadium information with:
-- venue_id (Primary Key)
-- stadium_name
-- city
-- capacity

-- Create a table MATCH to store match schedule with:
-- match_id (Primary Key)
-- match_date
-- venue_id (Foreign Key referencing VENUE table)
-- team1_id (Foreign Key referencing TEAM table)
-- team2_id (Foreign Key referencing TEAM table)

-- Create a table PERFORMANCE to store players match performance with:
-- performance_id (Primary Key)
-- match_id (Foreign Key referencing MATCH table)
-- player_id (Foreign Key referencing PLAYER table)
-- runs_scored
-- wickets_taken
-- catches

-- Relationship Summary
-- TEAM → COACH	1 to 1
-- TEAM → PLAYER	1 to M 
-- VENUE → MATCH	1 to M
-- TEAM → MATCH	M to M
-- MATCH → PERFORMANCE	1 to M
-- PLAYER → PERFORMANCE 1 to M	



-- Project 7 ( for girls+ boys )
-- College Fest Event Participation System

-- Create the following tables with suitable data types.
-- Use Primary Keys and Foreign Keys wherever required.

-- Department table 
-- Dept_ID
-- Dept_Name


-- Organizer table 
-- Organizer_ID
-- Organizer_Name
-- Role (Faculty / Student Coordinator)


-- Venue table 
-- Venue_ID
-- Venue_Name
-- Capacity

-- Student table 
-- Student_ID
-- Student_Name
-- Gender
-- Mobile
-- Dept_ID (should refer Dept_ID in Department table)

-- Event table 
-- Event_ID
-- Event_Name
-- Event_Date
-- Organizer_ID (should refer Organizer_ID in Organizer table)
-- Venue_ID (should refer Venue_ID in Venue table)

-- Participation table 
-- Participation_ID
-- Student_ID (should refer Student_ID in Student table)
-- Event_ID (should refer Event_ID in Event table)
-- Position (Winner / Runner / Participant)


-- RELATIONSHIP DETAILS (Wri
-- Department → Student One-to-Many	
-- Organizer → Event One-to-Many
-- Venue → Event  One-to-Many
-- Student → Participation One-to-Many 
-- Event → Participation	One-to-Many	


-- Project 8(12 Tables )
-- ZOMATO DATABASE PROJECT

-- Create a table named RESTAURANT
-- To store restaurant details.
-- Columns:
-- RESTAURANT_ID
-- NAME
-- PHONE
-- EMAIL
-- CITY
-- AREA
-- RATING
-- CREATED_DATE

-- Create a table named CATEGORY
-- To store food categories like "Chinese", "Indian", etc.
-- Columns:
-- CATEGORY_ID
-- CATEGORY_NAME
-- DESCRIPTION

-- Create a table named RESTAURANT_CATEGORY

-- To store which restaurant serves which category (many-to-many relation).
-- Columns:
-- RESTAURANT_ID
-- CATEGORY_ID

-- Create a table named MENU

-- To store each restaurant’s menu information.
-- Columns:
-- MENU_ID
-- RESTAURANT_ID
-- MENU_NAME
-- CREATED_DATE

-- Create a table named MENU_ITEM
-- To store food items under each menu.
-- Columns:
-- ITEM_ID – Primary Key
-- MENU_ID – Foreign Key references MENU
-- ITEM_NAME – Not Null
-- PRICE – Check (PRICE > 0)
-- AVAILABLE_STATUS – Default ‘YES’, Check (Available_Status IN ('YES', 'NO'))

-- Create a table named CUSTOMER
-- To store customer details.
-- Columns:
-- CUSTOMER_ID – Primary Key
-- FULL_NAME – Not Null
-- PHONE – Unique
-- EMAIL – Unique
-- GENDER – Check (Gender IN ('M','F','O'))
-- REGISTRATION_DATE – Default SYSDATE

-- Create a table named ADDRESS
-- To store multiple addresses for each customer.
-- Columns:
-- ADDRESS_ID – Primary Key
-- CUSTOMER_ID – Foreign Key references CUSTOMER
-- HOUSE_NO
-- STREET
-- CITY
-- PINCODE
-- ADDRESS_TYPE – Check (Address_Type IN ('HOME','OFFICE','OTHER’))

-- Create a table named DELIVERY_PERSON
-- To store details of delivery boys.
-- Columns:
-- DELIVERY_ID – Primary Key
-- NAME – Not Null
-- PHONE – Unique
-- VEHICLE_NO
-- STATUS – Default ‘AVAILABLE’, Check (STATUS IN ('AVAILABLE','BUSY'))


-- Create a table named ORDERS
-- To store customer order details.Columns:
-- ORDER_ID – Primary Key
-- CUSTOMER_ID – Foreign Key references CUSTOMER
-- RESTAURANT_ID – Foreign Key references RESTAURANT
-- DELIVERY_ID – Foreign Key references DELIVERY_PERSON
-- ORDER_DATE – Default SYSDATE
-- TOTAL_AMOUNT – Check (TOTAL_AMOUNT >= 0)
-- ORDER_STATUS – Default ‘PLACED’, Check (Order_Status IN ('PLACED','ONWAY','DELIVERED','CANCELLED'))


-- Create a table named ORDER_ITEM
-- To store all items under each order.
-- Columns:
-- ORDER_ID – Foreign Key references ORDERS
-- ITEM_ID – Foreign Key references MENU_ITEM
-- QUANTITY – Check (QUANTITY > 0)
-- PRICE – Check (PRICE > 0)
-- Combination of ORDER_ID and ITEM_ID – Primary Key


-- Create a table named PAYMENT
-- To store payment details for each order.Columns:
-- PAYMENT_ID – Primary Key
-- ORDER_ID – Foreign Key references ORDERS
-- PAYMENT_MODE – Check (Payment_Mode IN ('CARD','CASH','UPI'))
-- PAYMENT_DATE – Default SYSDATE
-- AMOUNT – Check (AMOUNT >= 0)
-- PAYMENT_STATUS – Default ‘PENDING’, Check (Payment_Status IN ('SUCCESS','FAILED','PENDING'))



-- Create a table named REVIEW
-- To store customer reviews for restaurants.
-- Columns:
-- REVIEW_ID – Primary Key
-- CUSTOMER_ID – Foreign Key references CUSTOMER
-- RESTAURANT_ID – Foreign Key references RESTAURANT
-- RATING – Check (Rating BETWEEN 1 AND 5)
-- COMMENTS
-- REVIEW_DATE – Default SYSDATE


-- Relationship 

-- 1)CUSTOMER→ORDERS 1-to-Many
-- 2)RESTAURANT→ORDERS	1-to-Many
-- 3)MENU_CATEGORY→MENU_ITEM 1-to-Many
-- RESTAURANT→MENU_ITEM	1-to-Many
-- ORDERS→ORDER_DETAILS 1-to-Many 
-- MENU_ITEM →ORDER_DETAILS. 1-to-Many
-- ORDERS→PAYMENT  1-to-1
-- DELIVERY_PERSON	→DELIVERY 1-to-Many
-- ORDERS→DELIVERY 1-to-1
-- CUSTOMER→REVIEW 1-to-Many
-- RESTAURANT→REVIEW 1-to-Many
-- COUPON→ORDER_COUPON 1-to-Many



-- Project 9
-- Train Ticket Booking System - SQL


-- 1. TRAIN
-- - TRAIN_ID (PRIMARY KEY)
-- - TRAIN_NAME
-- - SOURCE
-- - DESTINATION
-- - TOTAL_COACHES

-- 2. COACH
-- - COACH_ID (PRIMARY KEY)
-- - TRAIN_ID (FOREIGN KEY → TRAIN.TRAIN_ID)
-- - COACH_TYPE (Sleeper/AC/General)
-- - TOTAL_SEATS

-- 3. PASSENGER
-- - PASSENGER_ID (PRIMARY KEY)
-- - PASSENGER_NAME
-- - GENDER
-- - AGE

-- 4. TICKET
-- - TICKET_ID (PRIMARY KEY)
-- - PASSENGER_ID (FOREIGN KEY → PASSENGER.PASSENGER_ID)
-- - TRAIN_ID (FOREIGN KEY → TRAIN.TRAIN_ID)
-- - BOOKING_DATE
-- - TRAVEL_DATE

-- 5. SEAT_RESERVATION
-- - RES_ID (PRIMARY KEY)
-- - TICKET_ID (FOREIGN KEY → TICKET.TICKET_ID)
-- - COACH_ID (FOREIGN KEY → COACH.COACH_ID)
-- - SEAT_NO
-- - STATUS (Booked/Cancelled)


-- . Relationships
-- - TRAIN → COACH = One-to-Many
-- - TRAIN → TICKET = One-to-Many
-- - PASSENGER → TICKET = One-to-Many
-- - TICKET → SEAT_RESERVATION = One-to-Many
-- - COACH → SEAT_RESERVATION = One-to-Many


--  Indexes
-- CREATE INDEX On  (TRAIN_NAME);
-- CREATE INDEX on (PASSENGER_NAME)
-- CREATE INDEX ON TICKET(TRAVEL_DATE);

	
prompt mysql>