
PROMPT SRF QUESTIONS  /  ASSIGNMENT 


PROMPT 211) WAQTD THE NO OF CHARACTERS PRESENT IN YOUR NAME ?
SELECT LENGTH('MY NAME') FROM DUAL;
PROMPT 212) WAQTD THE DEATILS OF THE EMPLOYEES WHOSE NAME HAVING  4 CHARACTERS ?
SELECT * FROM EMP WHERE LENGTH(ENAME) = 4;
PROMPT 213) WAQTD ENAME AND LOC OF ALL THE EMPLOYEES WHO ARE EARNING 4 DIGIT OF SALARY ?
SELECT E.ENAME, D.LOC FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND LENGTH(SAL) = 4;
PROMPT 214) WAQT GET THE REMINDER VALUES OF 10 /5 ?
SELECT MOD(10, 5) FROM DUAL;

PROMPT 215) WAQTD THE DEATILS OF EMPLOYEES WHOSE NAME ENDS WITH VOWELS ?
SELECT * FROM EMP WHERE  LOWER(SUBSTR(ENAME, -1)) IN ('A', 'E', 'I', 'O', 'U');

PROMPT 216) WAQTD ALL THE DEATILS OF THE EMPLOYEES WHO AHEV MORE THEN 513 MONTHS  OF EXPERIANCE ?
SELECT * FROM EMP WHERE MONTHS_BETWEEN(SYSDATE, HIREDATE) > 513;

PROMPT 217) WAQT REPLACE THE 3RD A FROM THE MALAYALAM ?
SELECT REPLACE('MALAYALAM', 'A', 'X') FROM DUAL; --Noramal replace all the A in the string with X
SELECT REGEXP_REPLACE('MALAYALAM', 'A', 'X', 1, 3) FROM DUAL; --Replace only the 3rd A in the string with X
SELECT SUBSTR   

PROMPT 218) WAQTD THE FIRST HALF NAME OF EMPLOYEES SAME AND 2ND HALF NAME   OF EMPLOYEES IN REVERSE MANNAER ?
SELECT SUBSTR(ENAME, 1, LENGTH(ENAME)/2) || REVERSE(SUBSTR(ENAME, LENGTH(ENAME)/2 + 1)) AS RESULT FROM EMP;

PROMPT 219) WAQT REPLACE THE FIRST 6 NUMBER AS (*) FROM 9900199001 ?

PROMPT 220) WSQTD OF THE EMPLOYEES WHOSE NAME HAVING EXACTLY 2 A IN THEIR NAMES ?

PROMPT 221) WAQTD DNAME AND SAL OF ALL THE EMPLOYEES WHOSE NAMES ARE PALYDROM IN NATURE ?

PROMPT 222) WAQTD DNAME AND ENAME OF ALL THE EMPLOYEES WHOSE 2ND HALF NAME PALYDROM IN NATURE ?

PROMPT 223) WAQTD THE TOTAL SALARY NEEDED TO PAY FOR EACH AND EVERY EMPLOYEES ?(NVL)

PROMPT 224) WAQTD THE DETAILS OF THE EMPLOYEES WHO ARE EARNING 3RD MAX SALARY FROM EMP TABLE ?

PROMPT 225) WAQTD THE 2ND MAX SALARY FROM EACH AND EVERY JOB ?

PROMPT 226) WAQTD THE EMPLOYEES NAME AND THEIR DNAME IN INITCAP FORMAT  AND ALSO DISPLAY THEIR JOB IN LOWER CASE FORMAT ?

PROMPT 227) WAQT GET THE NO OF MONTHS BETWEEN YOUR DATE OF BIRTH TO TODAYS DATE ?

PROMPT 228) WAQT GET THE YOUR CURRENT AGE IN YEAR FORMAT UPTO THE DATE ?

PROMPT 229) WAQT CONCAT ENAME WITH THEIR  HALF DNAME OF ALL THE EMPLOYEES ?

PROMPT 230) WAQT GET THE DEATILS OF THE EMPLOYEES IF THEIR NAME HAVING % AS LAST LETTER ?

PROMPT 231) WAQTD THE DETAILS OF AN EMPLOYEES IF THEIR SALARIES ARE PALYDROM IN NATURE ?

PROMPT 232) WAQTD ALL THE EMPLOYEES IF THEIR NAME AND DNAME STARST WITH SAME LETTER ?

PROMPT 233) WAQTD ALL THE EMPLOYEES IF THEIR NAME AND DNAME STARST AND ENDS WITH SAME LETTER ?

PROMPT 234) WAQTD THE LOC AND DNAME AND JOB OF ALL THE EMPLOYEES IF THEIR NAME MIDDLE  LETTERS ARE VOWELS ?

PROMPT 235) WAQT GET EXACTLY THE MIDDLE NAME FROM  "VIRAT ANUSKHA KHOLI" ?

PROMPT 236) WAQT PRINT THE DEATILS IN GIVEN FLOW 

PROMPT     "HI SMITH GOOD MORNING YOUR DESIGNATION IS CLERK AND SALARY IS 800 YOUR DEPTNO IS 20"  SAME FORMAT FOR ALL THE EMPLOYEES  ?

PROMPT 237) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE HIRED ON WENSEDAY ?

PROMPT 238) WAQTD ALL THE DEATILF OF EMPLOYEES AND THEIR DEPARTMENT IF THEY ARE 

PROMPT     HIRED IN THE MONTH OF DEC , JAN , FEB ?

PROMPT 239) WAQTD ALL THE EMPLOYEES IF THEY ARE HIRED IN THE YEAR OF 81, 87, 82 ?

PROMPT 240) WAQT GET THE YOUR CURRENT AGE WITH DAY OF BORN ?



PROMPT mysql>