
-- **1. WAQTD NAME OF THE EMPLOYEES EARNING SALARY MORE THAN THE SALESMAN.**

-- ```sql
-- ENAME
-- -----
-- JONES
-- BLAKE
-- CLARK
-- SCOTT
-- KING
-- FORD

-- ```

SELECT ENAME FROM EMP 
WHERE SAL > ALL(SELECT SAL FROM EMP WHERE JOB = 'SALESMAN');

-- **2. WAQTD DETAILS OF THE EMPLOYEES HIRED AFTER ALL THE CLERKS.**

-- ```text
-- no rows selected

-- ``
SELECT * FROM EMP 
WHERE HIREDATE > ALL(SELECT HIREDATE FROM EMP WHERE JOB = 'CLERK');
-- **3. WAQTD NAME AND SALARY FOR ALL THE EMPLOYEES IF THEY ARE EARNING LESS THAN ATLEST A MANAGER.**

-- ```text
-- 10 rows selected

SELECT ENAME, SAL FROM EMP
WHERE SAL < ANY(SELECT SAL FROM EMP WHERE JOB = 'MANAGER');

-- ---

-- **4. WAQTD NAME AND HIREDATE OF EMPLOYEES HIRED BEFORE ALL THE MANAGERS.**

-- ```sql
-- ENAME      HIREDATE
-- -----      --------
-- SMITH      17-DEC-80
-- ALLEN      20-FEB-81
-- WARD       22-FEB-81
SELECT ENAME, HIREDATE FROM EMP 
WHERE HIREDATE < ALL(SELECT HIREDATE FROM EMP WHERE JOB = 'MANAGER');



-- **5. WAQTD NAMES OF THE EMPLOYEES HIRED AFTER ALL THE MANAGERS AND EARNING SALARY MORE THAN ALL THE CLERKS.**

-- ```sql
-- ENAME
-- -----
-- SCOTT
-- KING
-- TURNER
-- FORD

SELECT ENAME FROM EMP
WHERE HIREDATE > ALL(SELECT HIREDATE FROM EMP WHERE JOB = 'MANAGER') AND
SAL > ALL(SELECT SAL FROM EMP WHERE JOB = 'CLERK');

-- **6. WAQTD DETAILS OF THE EMPLOYEES WORKING AS CLERK AND HIRED BEFORE ATLEST A SALESMAN.**

-- ```sql
-- EMPNO  ENAME  JOB    MGR   HIREDATE   SAL  COMM  DEPTNO
-- -----  -----  ---    ---   --------   ---  ----  ------
-- 7369   SMITH  CLERK  7902  17-DEC-80  800        20
SELECT * FROM EMP 
WHERE JOB = 'CLERK' AND
HIREDATE < ANY(SELECT HIREDATE FROM EMP WHERE JOB = 'SALESMAN');

---

-- **7. WAQTD DETAILS OF EMPLOYEES WORKING IN ACCOUNTING OR SALES DEPT.**

-- ```sql
-- EMPNO  ENAME   JOB       MGR   HIREDATE   SAL   COMM  DEPTNO
-- -----  -----   ---       ---   --------   ---   ----  ------
-- 7499   ALLEN   SALESMAN  7698  20-FEB-81  1600   300  30
-- 7521   WARD    SALESMAN  7698  22-FEB-81  1250   500  30
-- 7654   MARTIN  SALESMAN  7698  28-SEP-81  1250  1400  30
-- 7698   BLAKE   MANAGER   7839  01-MAY-81  2850        30
-- 7782   CLARK   MANAGER   7839  09-JUN-81  2450        10
-- 7839   KING    PRESIDENT       17-NOV-81  5000        10
-- 7844   TURNER  SALESMAN  7698  08-SEP-81  1500     0  30
-- 7900   JAMES   CLERK     7698  03-DEC-81   950        30
-- 7934   MILLER  CLERK     7782  23-JAN-82  1300        10

SELECT * FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME IN ('ACCOUNTING', 'SALES'));

-- **8. WAQTD DEPARTMENT NAMES OF THE EMPLOYEES WITH NAME SMITH, KING**

SELECT DNAME FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME IN ('SMITH', 'KING')); 


-- **9. WAQTD DETAILS OF EMPLOYEES WORKING IN NEWYORK OR CHICAGO.**

-- ```sql
-- EMPNO  ENAME   JOB       MGR   HIREDATE   SAL   COMM  DEPTNO
-- -----  -----   ---       ---   --------   ---   ----  ------
-- 7499   ALLEN   SALESMAN  7698  20-FEB-81  1600   300  30
-- 7521   WARD    SALESMAN  7698  22-FEB-81  1250   500  30
-- 7654   MARTIN  SALESMAN  7698  28-SEP-81  1250  1400  30
-- 7698   BLAKE   MANAGER   7839  01-MAY-81  2850        30
-- 7782   CLARK   MANAGER   7839  09-JUN-81  2450        10
-- 7839   KING    PRESIDENT       17-NOV-81  5000        10
-- 7844   TURNER  SALESMAN  7698  08-SEP-81  1500     0  30
-- 7900   JAMES   CLERK     7698  03-DEC-81   950        30
-- 7934   MILLER  CLERK     7782  23-JAN-82  1300        10

    SELECT * FROM EMP
    WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC IN ('NEW YORK', 'CHICAGO'));




-- **10. WAQTD EMP NAMES IF EMPLOYEES ARE HIRED AFTER ALL THE...** *(Text cuts off)*

-- ```sql
-- ENAME
-- -----
-- SCOTT
-- ADAMS

SELECT ENAME FROM EMP 
WHERE HIREDATE > ALL(SELECT HIREDATE FROM EMP WHERE DEPTNO = 10);