

-- A] MR. ABC YOU HIRED ON DEF IN DEPTNO GHI
SELECT 'MR. ' || ENAME || ' YOU HIRED ON ' || HIREDATE || 'IN DEPTNO ' || DEPTNO FROM EMP;


-- B] HEY! ABC YOUR WORKIN AS DEF IN DEPTNO GHI
SELECT  'HEY! ' || ENAME  || ' YOUR WORKIN AS '|| JOB || ' IN DEPTNO ' || DEPTNO FROM EMP;


-- C] OYE! XYZ YOUR SALARY IS RS. ABS AND COMMISSION IS GKL
SELECT  'OYE! ' || ENAME || ' YOUR SALARY IS RS. ' || SAL ||' AND COMMISSION IS'|| COMM FROM EMP;

-- D] HEY DONKEY! WORK MORE AND GIVE ME YOUR ANNUAL SALARY IN ONE SHORT THAT IS FGH
SELECT ' HEY! '|| ENAME || '! WORK MORE AND GIVE ME YOUR ANNUAL SALARY IN ONE SHORT THAT IS ' || (SAL*12) FROM EMP;


-- E] SORY! ABC YOUR SAL IS RS.GHK AND WE ARE DEDUCTING 100 RPS IN IT FOR THAT YOU WILL GET JUST RTY
SELECT 'SORY! '|| ENAME || ' YOUR SAL IS RS.' || SAL ||' AND WE ARE DEDUCTING 100 RPS IN IT FOR THAT YOU WILL GET JUST' || (SAL-100 )FROM EMP;


-- F] HI! ABC YOUR DESIGNATION IS KLO THAT TOO IN DEPTNO TYU
SELECT 'HI! ' || SAL || ' YOUR DESIGNATION IS ' || JOB || 'THAT TOO IN DEPTNO '|| DEPTNO FROM EMP;

-- G] HELLO! QWE YOUR EMP ID IS ERT AND MANAGER ID IS JUI
SELECT 'HELLO! ' || ENAME || ' YOUR EMP ID IS ' || EMPNO || ' AND MANAGER ID IS ' || MGR FROM EMP;

-- H] ABC IS VERY KIND HEARTED WE NEED TO APPRECIATE THAT
SELECT ENAME || ' IS VERY KIND HEARTED WE NEED TO APPRECIATE THAT' FROM EMP;

-- I] MR. ABC YOUR SALARY IS RS.QWE AND HALFTERM IS RS.HJK
SELECT 'MR. ' || ENAME || ' YOUR SALARY IS RS.' || SAL || ' AND HALFTERM IS RS.' || (SAL/2) FROM EMP;

-- J] HEY! AVG YOUR SALARY IS RS.UIO AND YOU GOT 3000 RPS
SELECT 'HEY! ' || ENAME || ' YOUR SALARY IS RS.' || SAL || ' AND YOU GOT 3000 RPS' FROM EMP;