

-- ### 1] WAQTD MIN SALARY IN EACH DEPTNO.

-- | MIN(SAL) | DEPTNO |
-- | --- | --- |
-- | 950 | 30 |
-- | 800 | 20 |
-- | 1300 | 10 

SELECT MIN(SAL), DEPTNO FROM EMP
GROUP BY DEPTNO;



-- ### 2] WAQTD AVERAGE SALARY OF EMP'S IN EACH JOB.

-- | AVG(SAL) | JOB |
-- | --- | --- |
-- | 3000 | ANALYST |
-- | 1037.5 | CLERK |
-- | 1400 | SALESMAN |
-- | 5000 | PRESIDENT |
-- | 2758.33333 | MANAGER |
SELECT AVG(SAL), JOB FROM EMP 
GROUP BY JOB;

-- ### 3] WAQTD NUMBER OF EMP'S IN EACH DEPARTMENT IF THE EMP'S ARE EARNING MORE THAN RS.2000.

-- | COUNT(*) | DEPTNO |
-- | --- | --- |
-- | 1 | 30 |
-- | 3 | 20 |
-- | 2 | 10 |
SELECT COUNT(*), DEPTNO FROM EMP 
WHERE SAL > 2000 
GROUP BY DEPTNO;


-- ### 4] WAQTD NUMBER OF EMP'S WORKING IN EACH DEPT EXCEPT 'PRESIDENT'.

-- | COUNT(*) | DEPTNO |
-- | --- | --- |
-- | 6 | 30 |
-- | 5 | 20 |
-- | 2 | 10 |
SELECT COUNT(*), DEPTNO FROM EMP
WHERE JOB != 'PRESIDENT' 
GROUP BY DEPTNO;

-- ### 5] WAQTD NUMBER OF EMP'S WORKING AS 'MANAGER' IN EACH DEPT.

-- | COUNT(*) | DEPTNO |
-- | --- | --- |
-- | 1 | 30 |
-- | 1 | 20 |
-- | 1 | 10 |
SELECT COUNT(*), DEPTNO FROM EMP 
WHERE JOB = 'MANAGER'
GROUP BY DEPTNO;

-- ### 6] WAQTD AVG SAL NEEDED TO PAY TO ALL THE EMP'S EXCLUDING THE EMP'S WORKING IN DEPT NO 20 IN EACH JOB.

-- | AVG(SAL) | JOB |
-- | --- | --- |
-- | 1400 | SALESMAN |
-- | 1125 | CLERK |
-- | 5000 | PRESIDENT |
-- | 2650 | MANAGER |
SELECT AVG(SAL), JOB FROM EMP 
WHERE DEPTNO NOT IN (20)
GROUP BY JOB;



-- ### 7] WAQTD NUMBER OF EMP'S HAVING CHARACTER 'A' IN THEIR NAME IN EACH JOB.

-- | COUNT(*) | JOB |
-- | --- | --- |
-- | 3 | SALESMAN |
-- | 2 | CLERK |
-- | 2 | MANAGER |
SELECT COUNT(*), JOB FROM EMP 
WHERE ENAME LIKE '%A%'
GROUP BY JOB;
-- ### 8] WAQTD NUMBER OF EMP'S WORKING AS A CLERK IN EACH DEPARTMENT.

-- | COUNT(*) | DEPTNO |
-- | --- | --- |
-- | 1 | 30 |                   
-- | 2 | 20 |
-- | 1 | 10 |

SELECT COUNT(*), DEPTNO FROM EMP
WHERE JOB = 'CLERK'
GROUP BY DEPTNO;


-- ### 9] WAQTD NUMBER OF EMP'S HIRED IN THE YEAR 1981 IN EACH DEPARTMENT.

-- | COUNT(*) | DEPTNO |
-- | --- | --- |
-- | 6 | 30 |
-- | 2 | 20 |
-- | 2 | 10 |
SELECT COUNT(*), DEPTNO FROM EMP
WHERE HIREDATE LIKE '%81'
GROUP BY DEPTNO;


-- ### 10] WAQTD NUMBER OF EMP'S EARNING LESS THAN 1000 IN EACH DEPARTMENT.
-- | COUNT(*) | DEPTNO |
-- | --- | --- |
-- | 1 | 30 |
-- | 1 | 20 |
SELECT COUNT(*), DEPTNO FROM EMP
WHERE SAL < 1000
GROUP BY DEPTNO;


-- ### 11] WAQTD NUMBER OF EMP'S EARNING 3000 RS IN EACH DEPARTMENT.

-- | COUNT(*) | DEPTNO |
-- | --- | --- |
-- | 2 | 20 |
SELECT COUNT(*), DEPTNO FROM EMP
WHERE SAL > 3000;
GROUP BY DEPTNO;


-- ### 12] WAQTD MAXIMUM SALARY GIVEN TO THE EMP WORKING AS A CLERK IN EACH DEPT.

-- | MAX(SAL) | DEPTNO |
-- | --- | --- |
-- | 950 | 30 |
-- | 1100 | 20 |
-- | 1300 | 10 |
SELECT MAX(SAL), DEPTNO FROM EMP
GROUP BY DEPTNO;


-- ### 13] WAQTD NUMBER OF EMP'S HIRED IN THE MONTH OF FEBRUARY IN EACH JOB.
SELECT COUNT(*), JOB FROM EMP 
WHERE HIREDATE LIKE '%-FEB-%'
GROUP BY JOB;


-- ### 14] WAQTD NUMBER OF EMP'S WORKING AS PRESIDENT OR ANALYST AND EARNING MORE THAN 2000 IN EACH DEPARTMENT.

-- | COUNT(*) | DEPTNO |
-- | --- | --- |
-- | 2 | 20 |
-- | 1 | 10 |
SELECT COUNT(*), DEPTNO FROM EMP
WHERE JOB IN ('RESIDENT', 'ANALYST') AND SAL > 2000
GROUP BY DEPTNO;


-- ### 15] WAQTD NUMBER OF EMP'S WORKING IN EACH DEPT EXCEPT PRESIDENT.

-- | COUNT(*) | DEPTNO |
-- | --- | --- |
-- | 6 | 30 |
-- | 5 | 20 |
-- | 2 | 10 |
SELECT COUNT(*), DEPTNO FROM EMP 
WHERE JOB != 'PRESIDENT'
GROUP BY DEPTNO;


-- ### 16] WAQTD TOTAL SALARY NEEDED TO PAY ALL THE EMP'S IN EACH JOB.

-- | SUM(SAL) | JOB |
-- | --- | --- |
-- | 5600 | SALESMAN |
-- | 5000 | PRESIDENT |
-- | 8275 | MANAGER |
-- | 6000 | ANALYST |

SELECT SUM(SAL), JOB FROM EMP 
GROUP BY JOB;

-- ### 17] WAQTD AVERAGE SALARY NEEDED TO PAY ALL THE EMP'S IN EACH DEPT EXCLUDING THE EMP'S OF DEPTNO 20.

-- | AVG(SAL) | DEPTNO |
-- | --- | --- |
-- | 1566.66667 | 30 |
-- | 2916.66667 | 10 |
SELECT AVG(SAL), DEPTNO FROM EMP 
WHERE DEPTNO != 20
GROUP BY DEPTNO;


-- ### 18] WAQTD NUMBER OF EMP'S HAVING CHARACTER 'A' IN THEIR NAMES IN EACH JOB.

-- | COUNT(*) | JOB |
-- | --- | --- |
-- | 3 | SALESMAN |
-- | 2 | CLERK |
-- | 2 | MANAGER |

SELECT COUNT(*), JOB FROM EMP 
WHERE ENAME LIKE '%A%'
GROUP BY JOB;


-- ### 19] WAQTD NUMBER OF EMP'S AND AVG SAL NEEDED TO PAY THE EMP'S WHOSE SAL GREATER THAN 2000 IN EACH DEPT.


-- | COUNT(*) | AVG(SAL) | DEPTNO |
-- | --- | --- | --- |
-- | 1 | 2850 | 30 |
-- | 3 | 2991.66667 | 20 |
-- | 2 | 5000 | 10 |




SELECT COUNT(*), AVG(SAL), DEPTNO FROM EMP
WHERE SAL > 2000
GROUP BY DEPTNO;



-- ### 20] WAQTD NUMBER OF EMP'S AND TOTAL SAL GIVEN TO ALL THE SALESMAN IN EACH DEPT.


-- | COUNT(*) | SUM(SAL) | DEPTNO |
-- | --- | --- | --- |
-- | 4 | 5600 | 30 |




SELECT COUNT(*), SUM(SAL), DEPTNO FROM EMP
WHERE JOB = 'SALESMAN'
GROUP BY DEPTNO;



-- ### 21] WAQTD NUMBER OF EMP'S WITH THEIR MAX SALARIES IN EACH JOB.

-- | COUNT(*) | MAX(SAL) | JOB |
-- | --- | --- | --- |
-- | 4 | 1300 | CLERK |
-- | 4 | 1600 | SALESMAN |
-- | 1 | 5000 | PRESIDENT |
-- | 3 | 2975 | MANAGER |
-- | 2 | 3000 | ANALYST |




SELECT COUNT(*), MAX(SAL), JOB FROM EMP
GROUP BY JOB;



-- ### 22] WAQTD NUMBER OF TIMES EACH SALARIES ARE PRESENT IN EMP TABLE.


-- | COUNT(*) | SAL |
-- | --- | --- |
-- | 1 | 2450 |
-- | 1 | 5000 |
-- | 1 | 1300 |
-- | 2 | 1250 |
-- | 1 | 2850 |
-- | 1 | 2975 |
-- | 1 | 1100 |
-- | 2 | 3000 |
-- | 1 | 800 |
-- | 1 | 1600 |
-- | 1 | 1500 |
-- | 1 | 950 |


SELECT COUNT(*), SAL FROM EMP
GROUP BY SAL;



-- ### 23] WAQTD NUMBER OF EMP'S WORKING IN EACH DEPT HAVING AT LEAST 2 EMP'S IN EACH DEPT.


-- | COUNT(*) | DEPTNO |
-- | --- | --- |
-- | 6 | 30 |
-- | 5 | 20 |
-- | 3 | 10 |


SELECT COUNT(*), DEPTNO FROM EMP
GROUP BY DEPTNO
HAVING COUNT(*) >= 2;



-- ### 24] WAQTD AVG SAL, MAX SAL, MIN SAL OF EMPS WORKING IN EACH JOB IF EMP'S HIRED AFTER 1980.


-- | AVG(SAL) | MAX(SAL) | MIN(SAL) | JOB |
-- | --- | --- | --- | --- |
-- | 1400 | 1600 | 1250 | SALESMAN |
-- | 1116.66667 | 1300 | 950 | CLERK |
-- | 5000 | 5000 | 5000 | PRESIDENT |
-- | 2758.33333 | 2975 | 2450 | MANAGER |
-- | 3000 | 3000 | 3000 | ANALYST |




SELECT AVG(SAL), MAX(SAL), MIN(SAL), JOB FROM EMP
WHERE HIREDATE > '31-DEC-1980' 
GROUP BY JOB;




-- ### 25] WAQTD NUMBER OF EMP'S EARNING MORE THAN 2000 IN EACH DEPARTMENT WHO HIRED IN THE YEAR 1987.


-- | COUNT(*) | DEPTNO |
-- | --- | --- |
-- | 1 | 20 |



SELECT COUNT(*), DEPTNO FROM EMP
WHERE SAL > 2000 AND HIREDATE LIKE '%87'
GROUP BY DEPTNO;

