-- **1] WAQTD MAXIMUM SALARY IN EMP TABLE.**
-- MAX(SAL)
-- 5000

SELECT MAX(SAL) FROM EMP;

-- **2] WAQTD MIN SAL IN EMP TABLE.**
-- MIN(SAL)
-- 800

SELECT MIN(SAL) FROM EMP;

-- **3] WAQTD MAX SAL IN DEPTNO 10.**

SELECT MAX(SAL) FROM EMP 
WHERE DEPTNO = 10;

-- **4] WAQTD NUMBER OF EMP'S EARNING RS.3000 IN DEPT NO 20.**
-- COUNT(*)
-- 0

SELECT COUNT(*) FROM EMP
WHERE SAL = 3000 AND 
DEPTNO = 20;

---

-- **5] WAQTD NUMBER OF EMP'S EARNING MORE THAN 3000.**
-- COUNT(*)
-- 1

SELECT COUNT(*) FROM EMP 
WHERE SAL > 3000;

-- **6] WAQTD MAX SAL GIVEN TO 'MANAGER'.**
-- MAX(SAL)
-- 2975

SELECT MAX(SAL) FROM EMP 
WHERE JOB = 'MANAGER';

-- **7] WAQTD AVG SAL GIVEN TO 'PRESIDENT'.**
-- 5000

SELECT AVG(SAL) FROM EMP 
WHERE JOB = 'PRESIDENT';

-- **8] WAAQTD NUMBER OF EMP'S HIRED IN THE YEAR 1987.**
-- COUNT(*)
-- 2

SELECT COUNT(*) FROM EMP 
WHERE HIREDATE LIKE '%87';

---

-- **9] WAQTD NUMBER OF EMP'S WORKING AS A 'MANAGER' OR 'SALESMAN'.**
-- COUNT(*)
-- 7

SELECT COUNT(*) FROM EMP 
WHERE JOB IN ('MANAGER', 'SALESMAN');

-- **10] WAQTD NUMBER OF EMP'S HIRED IN THE MONTH OF DEC.**
-- COUNT(*)

SELECT COUNT(*) FROM EMP 
WHERE HIREDATE LIKE '%DEC%';

-- **11] WAQTD MAX SAL GIVEN TO EMP HIRED IN THE MONTH OF FEB.**
-- MAX(SAL)
-- 1500

SELECT MAX(SAL) FROM EMP 
WHERE HIREDATE LIKE '%FEB%';

---

-- **12] WAQTD TOTAL SAL GIVEN TO AN EMP WHO IS HAVING TWO CONSECUTIVE 'T' IN THEIR NAME.**
-- SUM(SAL)
-- 3000

SELECT SUM(SAL) FROM EMP 
WHERE ENAME LIKE '%TT%';

-- **13] WAQTD TOTAL SAL GIVEN TO THE EMP WHOSE NAME ENDS WITH CHAR 'N'**
-- SUM(SAL)
-- 2850

SELECT SUM(SAL) FROM EMP 
WHERE ENAME LIKE '%N';

-- **14] WAQTD NUMBER OF EMP'S WHOSE NAME STARTS WITH 'A'**
-- 2

SELECT COUNT(*) FROM EMP 
WHERE ENAME LIKE 'A%';

---

-- **15] WAQTD NUMBER OF EMP'S EARNING MORE THAN RS.3000 IN DEPARTMENT NO 10 & NAME MUST START WITH 'K' & ENDS WITH 'G'.**
-- COUNT(*)
-- 1

SELECT COUNT(*) FROM EMP 
WHERE SAL > 3000 AND 
DEPTNO = 10 AND 
ENAME LIKE 'K%G';

-- **16] WAQTD MAX SAL GIVEN TO EMP'S HIRED AFTER 82.**
-- MAX(SAL)
-- 3000

SELECT MAX(SAL) FROM EMP 
WHERE HIREDATE > '31-DEC-82';

-- **17] WAQTD MIN SAL GIVEN TO EMP'S NAME STARTS WITH 'A'.**
-- MIN(SAL)

SELECT MIN(SAL) FROM EMP 
WHERE ENAME LIKE 'A%';

---

-- **18] WAQTD AVG SAL GIVEN TO EMP'S NAME ENDS WITH 'T'.**
-- AVG(SAL)
-- 3000

SELECT AVG(SAL) FROM EMP
WHERE ENAME LIKE '%T';

-- **19] WAQTD TOTAL SAL GIVEN TO EMP'S WORKING AS SALESMAN.**
-- SUM(SAL)
-- 5600

SELECT SUM(SAL) FROM EMP 
WHERE JOB = 'SALESMAN';

-- **20] WAQTD COUNT OF EMP'S TAKING COMM.**
-- COUNT(*)
-- 4

SELECT COUNT(*) FROM EMP 
WHERE COMM IS NOT NULL AND COMM > 0;

---

-- **21] WAQTD COUNT OF EMP'S NOT TAKING ANY COMMISSION.**

SELECT COUNT(*) FROM EMP
WHERE COMM IS NULL OR COMM = 0;

-- **22] WAQTD COUNT OF EMP'S EARNING MORE THAN 2000 IN DEPTNO 30.**
-- COUNT(*)
-- 1

SELECT COUNT(*) FROM EMP 
WHERE SAL > 2000 AND DEPTNO = 30;

-- **23] WAQTD MAX SAL EARNING BY EMP'S HIRED BEFORE 87.**
-- MAX(SAL)
-- 5000

SELECT MAX(SAL) FROM EMP 
WHERE HIREDATE < '01-JAN-87';

---

-- **24] WAQTD MAX SAL EARNING BY EMP'S HIRED in 83.**
-- MAX(SAL)

SELECT MAX(SAL) FROM EMP 
WHERE HIREDATE LIKE '%83';

-- **25] WAQTD AVG SAL GIVEN TO EMP'S IN DEPTNO 20 & NAME WITH ' '.**

SELECT AVG(SAL) FROM EMP 
WHERE DEPTNO = 20 AND ENAME LIKE '% %';