-- PROMPT 1] WAQTD NAME OF AN EMP EARNING 2ND MAX SAL.
SELECT ENAME FROM EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP);

-- PROMPT 2] WAQTD  NAME OF EMP WHO ARE EARNING MORE THAN WARD & WORKING IN SAME DEPTNO AS THAT OF BLAKE & HIRED BEFORE TURNER.
SELECT ENAME FORM EMP 
WHERE SAL > (SELECT SAL FORM EMP WHERE ENAME = 'WORD') AND
DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME = 'BLAKE') AND HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME = 'TURNER');

-- PROMPT 3] WAQTD NAMES OF AN EMP HIRED AFTER SMITH, BEFORE MILLER & WORKING IN SAME DESIGNATION AS THAT OF JONES IN SALES DEPTARTMENT.
SELECT ENAME FROM EMP 
WHERE HRIEDATE > (SELECT HIREDATE FROM EMP WHERE ENAME = 'SIMTH') AND 
HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME = 'MILLER') AND 
JOB IN (SELECT JOB FROM EMP WHERE ENAME = 'JONES') AND 
DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME = 'SALES');


-- 4] WAQTD NAMES OF AN EMP EARNING LESS THAN KING & HIRED BEFORE  MILLER IN NEW YORK.
SELECT ENAME FROM EMP
WHERE SAL < (SELECT SAL FROM EMP WHERE ENAME = 'KING') AND
HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME = 'MILLER') AND 
DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME = 'NEW YORK');



-- 5] WAQTD NAME OF EMP EARNING 3RD MIN SAL.
-- ENAME
-- -----
-- ADAMS

SELECT ENAME FROM EMP 
WHERE SAL IN (SELECT MIN(SAL) FROM EMP); 


-- 6] WAQTD LOC OF AN EMP EARNING 3RD MAX SAL.
-- LOC
-- -----
-- DALLAS

SELECT LOC FROM DEPT 
WHERE SAL IN (SELECT MAX(SAL) FROM EMP 
                WHERE SAL <(SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP)));

-- 7] WAQTD NAMES OF EMP HIRED LAST.
-- ENAME
-- ------
-- ADAMS
SELECT ENAME FROM EMP 
WHERE HIREDATE IN (SELECT MAX(HIREDATE) FROM EMP );

-- 8] WAQTD NAME OF THE AN EMP HIRED 2ND.
-- ENAME
-- -------
-- ALLEN
SELECT ENAME FORM EMP 
WHERE HIREDATE IN (SELECT MAX(HIREDATE) FROM EMP 
                        WHERE HIREDATE < (SELECT MAX(HIREDATE) FROM EMP ));

-- 9] WAQTD LOC OF EMP HIRED 2ND LAST.
-- LOC
-- ---------
-- DALLAS
SELECT LOC FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP 
                    WHERE HIREDATE IN (SELECT MAX(HIREDATE) FROM EMP 
                        WHERE HIREDATE < (SELECT MAX(HIREDATE) FROM EMP )));

-- 10] WAQTD NAME OF THE EMP EARNING 5TH MIN SAL.
-- ENAME
-- ------
-- MILLER
SELECT ENAME FORM EMP
WHERE SAL IN (SELECT MIN(SAL) FROM EMP 
                    WHERE SAL > (SELECT MIN(SAL) FROM EMP 
                    WHERE SAL > (SELECT MIN(SAL) FROM EMP 
                    WHERE SAL > (SELECT MIN(SAL) FROM EMP 
                    WHERE SAL > (SELECT MIN(SAL) FROM EMP)))));

-- 11] WAQTD LOCATION OF AN EMP EARNING 2ND MIN SAL.
-- LOC
-- ------
-- CHICAGO
SELECT LOC FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP 
                    WHERE SAL IN (SELECT MIN(SAL) FROM EMP 
                    WHERE SAL > (SELECT MIN(SAL) FROM EMP)));


-- 12] WAQTD NAME OF AN EMP EARNING 4TH MIN SAL.
-- ENAME
-- -------
-- MARTIN
SELECT ENAME FORM EMP
WHERE SAL IN (SELECT MIN(SAL) FROM EMP 
                    WHERE SAL > (SELECT MIN(SAL) FROM EMP 
                    WHERE SAL > (SELECT MIN(SAL) FROM EMP 
                    WHERE SAL >  (SELECT MIN(SAL) FROM EMP))));

-- 13] WAQTD DNAME OF EMP WHOSE NAME IS SMITH.
-- DNAME
-- -------
-- RESEARCH

SELECT DNAME FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FORM EMP WHERE ENAME = 'SMITH');


-- 14] WAQTD DNAME, LOC OF THE EMP'S WHOSE NAME IS KING.
-- DNAME LOC
-- -------------- ----------
-- ACCOUNTING NEW YORK

SELECT DNAME, LOC FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME = 'KING');


-- 15] WAQTD LOC OF EMP WHOSE EMPNO IS 7902.
-- LOC
-- ---------
-- DALLAS
SELECT LOC FROM DEPT 
WHERE DEMPTNO IN (SELECT DEPTNO FROM EMP WHERE EMPNO = 7902);


-- 16] WAQTD DETAILS OF AN EMP WORKING AS PRESIDENT AND EARNING MORE
-- THAN SCOTT AND HIRED AFTER SMITH.
-- EMPNO ENAME JOB MGR HIREDATE SAL COMM DEPTNO
-- ------ ---------- --------- ---------- --------- ---------- ---------- ----------
-- 7839 KING PRESIDENT 17-NOV-81 5000 10


SELECT * FROM EMP 
WHERE JOB = 'PRESEDENT' AND
SAL > (SELECT SAL FROM EMP WHERE ENAME = 'SCOTT') AND 
HIREDATE > (SELECT HIREDATE FROM EMP WHERE ENAME = 'SMITH');

