-- Here is the complete text extracted from the PDF exactly as it appears in the document:

-- ### **SRF QUESTIONS** 



-- * 1] WAQTD DETAILS OF EMP'S HAVING 4 CHARACTERS. 
SELECT * FROM EMP WHERE LENGTH(ENAME) = 4;

-- * 2] WAQTD EMP'S WHOSE JOB IS HAVING 7 CHAR'S. 
SELECT * FROM EMP WHERE LENGTH(JOB) = 7;

-- * 3] WAQTD HOW MANY TIMES LETTES 'L' OCCURS IN 'LANGUAGE'. 
SELECT LENGTH('LANGUAGE') - LENGTH(REPLACE('LANGUAGE', 'L')) "L OCCURS IN /LANGUAGE/" FROM DUAL;

-- * 4] WAQTD NAMES & DESIGNATION OF EMP'S HAVING LAST 3 CHAR'S AS 'MAN'. 


-- * VIKAS KALAL SQL 


-- * 5] WAQTD NUMBER OF EMP'S WHOSE JOB IS HAVING FIRST 3 CHAR'S AS 'PRE'. 


-- * 6] WAQTD NUMBER OF EMP'S WHOSE JOB IS HAVING FIRST 2 CHAR'S AS 'CL'. 


-- * OF EMP'S HAVING EXACTLY 1 'L'.  *(Note: Appears to be missing the question number '7]' in the source text)*


-- * 8] WAQTD DEPT NAMES WHICH ARE HAVING CHAR 'O' IN IT. 


-- * 9] WAQTD NUMER OF 'L' IN STRING 'HELLO'. 


-- * 10] WAQTD DETAILS OF EMP'S WHOSE JOB HAS A STRING 'MAN'. 


-- * 11] WAQTD ALL THE EMP'S WHOSE JON STARTS WITH 'ΜΑΝ'. 


-- * 12] WAQTD ALL THE EMP'S WHOSE JOB ENDS WITH 'MAN'. 


-- * 13] WAQTD FIRST 3 CHAR'S OF NAME IN LOWER CASE & REST EVERYTHING IN UPPER CASE. 


-- * EX: NAME IS VIKAS ==> vikAS. 




-- * 14] WAQTD THE RESULT FROM EMP TABLE AS : 


-- * VIKAS KALAL SOL 


-- * ABC IS A XYZ AND GETS A 


-- * (IF EMP IS WORKING AS A CLERK AND EARNING MORE THAN 1000) 




-- * 15] WAQTD NAME, HIREDATE & HIRED DAY OF EMP'S IF THEY HIRED ON 'WEDNESDAY'. 


-- * WHO HIRED IN THE LEAP YEAR.  *(Note: Appears to be missing the question number '16]' in the source text)*


-- * 17] WAQTD THE EMP'S WHO NOT HIRED IN THE LEAP YEAR. 


-- * 18] WAQTD EMP NAME IF THEY HIRED ON SUNDAY IN THE MONTH OF MAY. 


-- * 19] WAQTD NAMES OF EMP'S WHOSE NAMES STARTS WITH VOWELS. 


-- * 20] WAQTD NAMES OF EMP'S WHOSE NAMES STARTS WITH CONSONENTS. 


-- * VIKAS KALAL SQL