PROMPT "QUE 1] CREATE THE RESPECTIVE TABLES & INSERT TI--IE VALUES AS SHOIivN BELOW" 
PROMPT sqlplus>

IF NOT EXISTS CREATE TABLE VOTING_DETAILS(
    LOCATION VARCHAR(30) NOT NULL,
    VOTE_DATE DATE NOT NULL,
    COUNT_DATE DATE NOT NULL,
    MALE_VOTERS NUMBER(10) NOT NULL,
    FEMALE_VOTERS NUMBER(10) NOT NULL

);
TRUNCATE TABLE VOTING_DETAILS;
-- ADDING DATA IN IT
INSERT INTO VOTING_DETAILS VALUES(
    'PUNE',
    '23-JAN-25',
    '30-JAN-25',
    34524324,
    34325634
);
INSERT INTO VOTING_DETAILS VALUES(
    'MUMBAI',
    '30-APR-25',
    '07-MAY-25',
    23213124,
    12424215
);
INSERT INTO VOTING_DETAILS VALUES(
    'KARNATAKA',
    '05-SEP-2S',
    '12-SEP-2S',
    56481632,
    46846163
);
INSERT INTO VOTING_DETAILS VALUES(
    'LONAVALA',
    '23-AUG-2S',
    '30-AUG-2S',
    15203161,
    15484113
);
INSERT INTO VOTING_DETAILS VALUES(
    'DELHI',
    '06-NOV-25',
    '25-NOV-25',
    65987926,
    65974634
);

IF NOT EXISTS CREATE TABLE CANDISATES(
    C_ID VARCHAR(12) PRIMARY KEY,
    CNAME VARCHAR(30) NOT NULL,
    PARTY VARCHAR(30) NOT NULL,
    SYMBOLS VARCHAR(30),
    LOCATION VARCHAR(30) NOT NULL
);
TRUNCATE TABLE CANDISATES;
INSERT INTO CANDISATES VALUES(
    'C_01',
    'AMAN',
    'BJP',
    'LOTUS',
    'PUNE'
);
INSERT INTO CANDISATES VALUES('C_02', 'KIRAN', 'CONG', NULL, 'PUNE');
INSERT INTO CANDISATES VALUES('C_03', 'DHEERAJ', 'SHIV SENA', 'ARROW', 'PUNE');
INSERT INTO CANDISATES VALUES('C_04', 'VEENA', 'BJP', 'LOTUS', 'MUMBAI');
INSERT INTO CANDISATES VALUES('C_05', 'MEGHA', 'BJP', 'LOTUS', 'LONAVALA');
INSERT INTO CANDISATES VALUES('C_06', 'KARTHIK', 'SHIV SENA', 'ARROW', 'KARNATAKA');
INSERT INTO CANDISATES VALUES('C_07', 'JAYA', 'BJP', 'LOTUS', 'DELHI');
INSERT INTO CANDISATES VALUES('C_08', 'AMAN', 'CONG', 'HAND', 'MUMBAI');
INSERT INTO CANDISATES VALUES('C_09', 'JAYA', 'BJP', 'LOTUS', 'DELHI');
INSERT INTO CANDISATES VALUES('C_10', 'AJAY', 'NPP', NULL, 'KARNATAK');



TRUNCATE TABLE ELECTION_STAFF;
IF NOT EXISTS CREATE TABLE ELECTION_STAFF(
    ID NUMBER(4) PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    AGE NUMBER(3) CHECK(AGE>18) NOT NULL,
    DUTY_LOC VARCHAR(30) NOT NULL,
    MNO NUMBER(10) CHECK(LENGTH(MNO) = 10)
);

INSERT INTO ELECTION_STAFF VALUES(
    101,
    'MANOJ',
    28, 
    'KARNATAKA', 
    '9876543210'
);
INSERT INTO ELECTION_STAFF VALUES(102, 'KIRAN', 35, 'DELHI', '9632587410');
INSERT INTO ELECTION_STAFF VALUES(103, 'BHAVYA', 31, 'KARNATAKA', '9512347826');
INSERT INTO ELECTION_STAFF VALUES(104, 'MANOJ', 33, 'PUNE', NULL);
INSERT INTO ELECTION_STAFF VALUES(105, 'KISHORE', 28, 'MUMBAI', '7895460231');
INSERT INTO ELECTION_STAFF VALUES(106, 'NARAYAN', 34, 'LONAVALA', '9964702837');
INSERT INTO ELECTION_STAFF VALUES(107, 'MARUTHI', 45, 'PUNE', NULL);
INSERT INTO ELECTION_STAFF VALUES(108, 'SAKSHI', 26, 'MUMBAI', '8965471023');

TRUNCATE TABLE PARTY_DTRENGTH;
IF NOT EXISTS CREATE TABLE PARTY_DTRENGTH(
    PARTY VARCHAR(30) NOT NULL,
    SEATS_FIGHT NUMBER(5) NOT NULL,
    WIN_RATE NUMBER(4,2) NOT NULL,
    HEAD_OFFICE VARCHAR(30) NOT NULL
);


INSERT INTO PARTY_STRENGTH VALUES('BJP', 234, 78.59, 'DELHI');
INSERT INTO PARTY_STRENGTH VALUES('CONG', 231, 43.25, 'MUMBAI');
INSERT INTO PARTY_STRENGTH VALUES('AAP', 142, 35.28, 'DELHI');
INSERT INTO PARTY_STRENGTH VALUES('SHIV SENA', 105, 38.76, 'MUMBAI');
INSERT INTO PARTY_STRENGTH VALUES('JDS', 5, 45.68, 'KARNATAKA');
INSERT INTO PARTY_STRENGTH VALUES('NPP', 15, 12.87, 'PUNE');


PROMPT "2] MODIFY CANDIDATE KARTHIK LOCATION TO DELHI."
PROMPT sqlplus>
UPDATE CANDISATES
SET LOCATION = 'DELHI'
WHERE CNAME = 'KARTHIK';

PROMPT "3] DELETE CONGRESS PARTY RECORD FROM PARTY_STRENGTH"
PROMPT sqlplus>
DELETE * FROM PARTY_STRENGTH WHERE PARTY = 'CONG';


PROMPT "4] DELETE MNO OF KISHORE"
PROMPT sqlplus>
DELETE MNO FROM ELECTION_STAFF WHERE NAME = 'KISHOR';

PROMPT "5] GIVE THE PERMISSION OF DELETING RECORD OF ELECTION STAFF TO HR, LOG IN AS HR TO DELETE 108 RECORD LATER TAKE BACK THE PERMISSION"
PROMPT sqlplus>

GRANT DELETE ON ELECTION_STAFF TO HR;
--LOGIN AS HR
CONN HR/KING;

DELETE FROM ELECTION_STAFF WHERE ID = 108;


