Here is a comprehensive "Master Level" SQL practice set. I have designed a robust **Enterprise Tech Company** schema that will allow you to practice all four major SQL sublanguages: **DDL** (Data Definition Language), **DML** (Data Manipulation Language), **DCL** (Data Control Language), and **TCL** (Transaction Control Language).

As requested, this contains exactly 25 questions in your prompt format, with the initial raw data provided in Question 1, and **no answers** for the remaining 24 tasks so you can practice writing them yourself.

***

PROMPT "1] MASTER SETUP [DDL & DML]: CREATE THE TABLES AND INSERT THE BASE DATA AS SHOWN BELOW."
PROMPT sqlplus>

DEPARTMENTS

The following table:
"DEPT_ID", "DEPT_NAME", "LOCATION"
"D10", "ENGINEERING", "PUNE"
"D20", "SALES", "MUMBAI"
"D30", "MARKETING", "DELHI"
"D40", "HR", "BANGALORE"

EMPLOYEES

The following table:
"EMP_ID", "EMP_NAME", "JOB_ROLE", "SALARY", "DEPT_ID"
"E101", "AARAV", "DEVELOPER", "75000", "D10"
"E102", "SNEHA", "MANAGER", "95000", "D20"
"E103", "ROHAN", "ANALYST", "65000", "D30"
"E104", "PRIYA", "DEVELOPER", "80000", "D10"
"E105", "VIKRAM", "RECRUITER", "55000", "D40"
"E106", "ANITA", "VP", "150000", "D20"

PROJECTS

The following table:
"PROJ_ID", "PROJ_NAME", "BUDGET", "STATUS"
"P1", "AI_CORE", "500000", "ACTIVE"
"P2", "CLOUD_MIGRATE", "300000", "ACTIVE"
"P3", "APP_REVAMP", "150000", "DELAYED"
"P4", "NEW_WEBSITE", "80000", "COMPLETED"

---
**--- SECTION A: DDL (DATA DEFINITION LANGUAGE) ---**

PROMPT "2] DDL: ALTER THE EMPLOYEES TABLE TO ADD A NEW COLUMN 'JOIN_DATE' OF TYPE DATE."
PROMPT sqlplus>

PROMPT "3] DDL: MODIFY THE 'BUDGET' COLUMN IN THE PROJECTS TABLE TO ACCEPT NUMBERS UP TO 10 DIGITS."
PROMPT sqlplus>

PROMPT "4] DDL: RENAME THE COLUMN 'JOB_ROLE' IN THE EMPLOYEES TABLE TO 'DESIGNATION'."
PROMPT sqlplus>

PROMPT "5] DDL: ADD A CHECK CONSTRAINT TO THE PROJECTS TABLE ENSURING THAT THE 'BUDGET' IS ALWAYS GREATER THAN 10000."
PROMPT sqlplus>

PROMPT "6] DDL: DROP THE 'STATUS' COLUMN FROM THE PROJECTS TABLE ENTIRELY."
PROMPT sqlplus>

PROMPT "7] DDL: ADD A FOREIGN KEY TO THE EMPLOYEES TABLE SO THAT 'DEPT_ID' REFERENCES 'DEPT_ID' IN THE DEPARTMENTS TABLE."
PROMPT sqlplus>

**--- SECTION B: DML (DATA MANIPULATION LANGUAGE) ---**

PROMPT "8] DML: INSERT A NEW RECORD INTO THE DEPARTMENTS TABLE FOR 'FINANCE' LOCATED IN 'CHENNAI' WITH DEPT_ID 'D50'."
PROMPT sqlplus>

PROMPT "9] DML: UPDATE THE SALARY OF EMPLOYEE 'ROHAN' TO 70000."
PROMPT sqlplus>

PROMPT "10] DML: UPDATE THE LOCATION OF THE 'HR' DEPARTMENT FROM BANGALORE TO 'PUNE'."
PROMPT sqlplus>

PROMPT "11] DML: INCREASE THE SALARY OF ALL EMPLOYEES IN DEPT_ID 'D10' BY 10 PERCENT USING A MATHEMATICAL OPERATION."
PROMPT sqlplus>

PROMPT "12] DML: DELETE THE RECORD OF EMPLOYEE 'VIKRAM' FROM THE EMPLOYEES TABLE."
PROMPT sqlplus>

PROMPT "13] DML: DELETE ALL PROJECTS WHERE THE BUDGET IS LESS THAN 100000."
PROMPT sqlplus>

PROMPT "14] DML: WRITE A SUBQUERY-BASED UPDATE TO SET THE SALARY OF ALL EMPLOYEES IN 'PUNE' LOCATION TO 90000."
PROMPT sqlplus>

**--- SECTION C: DCL (DATA CONTROL LANGUAGE) ---**

PROMPT "15] DCL: GRANT ONLY 'SELECT' PERMISSION ON THE EMPLOYEES TABLE TO A USER NAMED 'HR_ADMIN'."
PROMPT sqlplus>

PROMPT "16] DCL: GRANT 'INSERT' AND 'UPDATE' PERMISSIONS ON THE PROJECTS TABLE TO A USER NAMED 'PROJ_MANAGER'."
PROMPT sqlplus>

PROMPT "17] DCL: REVOKE THE 'UPDATE' PERMISSION ON THE PROJECTS TABLE FROM 'PROJ_MANAGER'."
PROMPT sqlplus>

PROMPT "18] DCL: GRANT 'ALL PRIVILEGES' ON THE DEPARTMENTS TABLE TO A USER NAMED 'SYS_ADMIN' WITH THE ABILITY FOR THEM TO PASS THAT PERMISSION TO OTHERS (GRANT OPTION)."
PROMPT sqlplus>

**--- SECTION D: TCL (TRANSACTION CONTROL LANGUAGE) ---**

PROMPT "19] TCL: UPDATE THE BUDGET OF 'AI_CORE' TO 600000, AND THEN IMMEDIATELY CREATE A SAVEPOINT NAMED 'SP_BUDGET_UPDATE'."
PROMPT sqlplus>

PROMPT "20] TCL: DELETE THE 'APP_REVAMP' PROJECT FROM THE PROJECTS TABLE."
PROMPT sqlplus>

PROMPT "21] TCL: YOU REALIZED THE DELETION WAS A MISTAKE. ROLLBACK THE TRANSACTION ONLY TO THE SAVEPOINT 'SP_BUDGET_UPDATE' SO THE DELETION IS UNDONE BUT THE BUDGET UPDATE REMAINS."
PROMPT sqlplus>

PROMPT "22] TCL: PERMANENTLY SAVE ALL THE PENDING CHANGES TO THE DATABASE EXECUTED BEFORE THE SAVEPOINT."
PROMPT sqlplus>

**--- SECTION E: ADVANCED DDL & COMBINED TASKS ---**

PROMPT "23] DDL: CREATE A VIEW NAMED 'HIGH_SALARY_EMPS' THAT DISPLAYS ONLY THE EMP_NAME AND SALARY OF EMPLOYEES EARNING MORE THAN 80000."
PROMPT sqlplus>

PROMPT "24] DDL: REMOVE ALL DATA FROM THE PROJECTS TABLE INSTANTLY WITHOUT LOGGING INDIVIDUAL ROW DELETIONS (DO NOT DROP THE TABLE STRUCTURE)."
PROMPT sqlplus>

PROMPT "25] DDL: PERMANENTLY DESTROY THE DEPARTMENTS TABLE AND ALL ITS DATA FROM THE DATABASE."
PROMPT sqlplus>