Here is another mock SQL practice set in the exact same format and style as your document, this time using a **Hospital Management System** scenario. 

As requested, I have only provided the questions and data, without the SQL query answers.

***

PROMPT "1] CREATE THE RESPECTIVE TABLES & INSERT THE VALUES AS SHOWN BELOW."
PROMPT sqlplus>

HOSPITAL_BRANCHES

The following table:
"CITY", "ESTB_DATE", "RENEWAL_DATE", "TOTAL_BEDS", "AVAILABLE_BEDS"
"CHENNAI", "15-FEB-25", "25-FEB-25", "1250", "340"
"HYDERABAD", "01-MAR-25", "10-MAR-25", "980", "150"
"BANGALORE", "12-APR-25", "22-APR-25", "1500", "420"
"KOCHI", "05-MAY-25", "15-MAY-25", "600", "85"
"TRIVANDRUM", "20-MAY-25", "30-MAY-25", "850", "210"

DOCTORS

The following table:
"DOC_ID", "DNAME", "SPECIALTY", "EMP_TYPE", "CITY"
"D_01", "ARVIND", "CARDIOLOGY", "PERMANENT", "CHENNAI"
"D_02", "MEERA", "NEUROLOGY", , "CHENNAI"
"D_03", "SANJAY", "ORTHOPEDIC", "VISITING", "HYDERABAD"
"D_04", "KAVITHA", "PEDIATRICS", "PERMANENT", "BANGALORE"
"D_05", "VISHAL", "CARDIOLOGY", "PERMANENT", "KOCHI"
"D_06", "NEHA", "ONCOLOGY", "VISITING", "TRIVANDRUM"
"D_07", "PRATIK", "ORTHOPEDIC", "PERMANENT", "HYDERABAD"
"D_08", "ARVIND", "NEUROLOGY", "PERMANENT", "BANGALORE"

STAFF_DETAILS

The following table:
"EMP_ID", "NAME", "AGE", "WORK_LOC", "CONTACT_NO"
"301", "RAMESH", "34", "CHENNAI", "9845123670"
"302", "SITA", "28", "HYDERABAD", "8754213690"
"303", "GOPAL", "42", "BANGALORE", "7698541230"
"304", "MEERA", "31", "KOCHI", 
"305", "HARISH", "47", "TRIVANDRUM", "6587412309"
"306", "RAMESH", "39", "HYDERABAD", 
"307", "REKHA", "26", "CHENNAI", "9955443322"

WARD_STRENGTH

The following table:
"WARD_TYPE", "TOTAL_STAFF", "OCCUPANCY_RATE", "MAIN_HUB"
"ICU", "150", "92.50", "CHENNAI"
"GENERAL", "320", "85.20", "CHENNAI"
"PEDIATRIC", "110", "65.40", "HYDERABAD"
"MATERNITY", "95", "78.90", "BANGALORE"
"EMERGENCY", "200", "95.60", "TRIVANDRUM"

---

PROMPT "2] MODIFY DOCTOR PRATIK CITY TO BANGALORE."
PROMPT sqlplus>

PROMPT "3] DELETE MATERNITY WARD RECORD FROM WARD_STRENGTH"
PROMPT sqlplus>

PROMPT "4] DELETE CONTACT_NO OF REKHA"
PROMPT sqlplus>

PROMPT "5] GIVE THE PERMISSION OF DELETING RECORD OF STAFF_DETAILS TO IT_ADMIN, LOG IN AS IT_ADMIN TO DELETE 305 RECORD, LATER TAKE BACK THE PERMISSION."
PROMPT sqlplus>